package drizzle

import (
	"testing"

	"github.com/capysquash/pgsquash-engine/internal/types"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestIsDrizzleTimestampPath(t *testing.T) {
	t.Parallel()

	assert.True(t, isDrizzleTimestampPath("drizzle/20260312123045_add_users/migration.sql"))
	assert.False(t, isDrizzleTimestampPath("drizzle/add_users/migration.sql"))
	assert.False(t, isDrizzleTimestampPath("migrations/20260312123045_add_users.sql"))
}

func TestDetectByFilenamePattern(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()
	migrations := []*types.Migration{
		{Filename: "drizzle/20260312123045_add_users/migration.sql"},
	}

	assert.True(t, plugin.Detect(migrations))
}

func TestDetectPatternsIdentityMetadata(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()
	found := plugin.DetectPatterns("CREATE TABLE users (id bigint GENERATED BY DEFAULT AS IDENTITY);")
	require.NotEmpty(t, found)

	var identityPatternType string
	for _, p := range found {
		if p.Name == "drizzle_identity_column" {
			identityPatternType = p.Metadata["type"]
			break
		}
	}

	assert.Equal(t, "BY DEFAULT", identityPatternType)
}

func TestHasIdentityColumn(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()
	assert.True(t, plugin.hasIdentityColumn("id bigint GENERATED ALWAYS AS IDENTITY"))
	assert.False(t, plugin.hasIdentityColumn("id bigint"))
}
