// Package drizzle provides Drizzle ORM integration for pgsquash.
// It handles Drizzle-generated migrations, identity columns, and drizzle-kit patterns.
package drizzle

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/capysquash/pgsquash-engine/internal/errors"
	"github.com/capysquash/pgsquash-engine/internal/plugins"
	"github.com/capysquash/pgsquash-engine/internal/types"
)

// DrizzlePlugin implements Drizzle ORM integration
type DrizzlePlugin struct {
	*plugins.BasePlugin
	config DrizzleConfig
}

// DrizzleConfig holds Drizzle-specific configuration
type DrizzleConfig struct {
	Enabled               bool `json:"enabled"`
	PreferIdentityColumns bool `json:"prefer_identity_columns"` // Prefer IDENTITY over SERIAL
	PreserveDrizzleMeta   bool `json:"preserve_drizzle_meta"`   // Preserve __drizzle_migrations
	OptimizeSequences     bool `json:"optimize_sequences"`      // Optimize sequence configurations
}

// NewDrizzlePlugin creates a new Drizzle plugin instance
func NewDrizzlePlugin() *DrizzlePlugin {
	return &DrizzlePlugin{
		BasePlugin: plugins.NewBasePlugin("drizzle", 75), // ORM priority (same as Prisma)
		config: DrizzleConfig{
			Enabled:               true,
			PreferIdentityColumns: true,
			PreserveDrizzleMeta:   true,
			OptimizeSequences:     true,
		},
	}
}

// Detect checks if migrations contain Drizzle patterns
// Detection patterns:
//  1. GENERATED ALWAYS AS IDENTITY (Drizzle's preferred pattern)
//  2. __drizzle_migrations metadata table
//  3. Drizzle folder structure (drizzle/TIMESTAMP_name/)
//  4. snapshot.json metadata files
//  5. Drizzle-specific SQL comments
func (dp *DrizzlePlugin) Detect(migrations []*types.Migration) bool {
	for _, migration := range migrations {
		filename := strings.ToLower(migration.Filename)

		// Pattern 1: Drizzle timestamp directory pattern
		// Format: drizzle/20242409125510_premium_mister_fear/migration.sql
		if isDrizzleTimestampPath(filename) {
			return true
		}

		// Pattern 2: snapshot.json reference (Drizzle-specific)
		if strings.Contains(filename, "snapshot.json") {
			return true
		}

		for _, stmt := range migration.Statements {
			sql := stmt.SQL
			sqlLower := strings.ToLower(sql)

			// Pattern 3: GENERATED ALWAYS AS IDENTITY (Drizzle preference)
			if strings.Contains(sqlLower, "generated always as identity") ||
				strings.Contains(sqlLower, "generated by default as identity") {
				return true
			}

			// Pattern 4: __drizzle_migrations table
			if strings.Contains(sqlLower, "__drizzle_migrations") {
				return true
			}

			// Pattern 5: Drizzle-style sequence naming
			// Drizzle: table_column_seq format with IDENTITY
			sqlUpper := strings.ToUpper(sql)
			if (containsKeywordSequenceCI(sqlUpper, []string{"GENERATED", "ALWAYS", "AS", "IDENTITY"}) ||
				containsKeywordSequenceCI(sqlUpper, []string{"GENERATED", "BY", "DEFAULT", "AS", "IDENTITY"})) &&
				strings.Contains(sqlUpper, "SEQUENCE") &&
				strings.Contains(sqlUpper, "NAME") &&
				strings.Contains(sqlLower, "_seq\"") {
				return true
			}

			// Pattern 6: Drizzle migration comments
			if strings.Contains(sql, "-- drizzle-kit") ||
				strings.Contains(sql, "-- Drizzle") {
				return true
			}
		}
	}

	return false
}

// Initialize configures the Drizzle plugin
func (dp *DrizzlePlugin) Initialize(ctx context.Context, config any) error {
	if config == nil {
		return nil
	}

	if drizzleConfig, ok := config.(DrizzleConfig); ok {
		dp.config = drizzleConfig
	} else if configMap, ok := config.(map[string]any); ok {
		if enabled, ok := configMap["enabled"].(bool); ok {
			dp.config.Enabled = enabled
		}
		if preferIdentity, ok := configMap["prefer_identity_columns"].(bool); ok {
			dp.config.PreferIdentityColumns = preferIdentity
		}
		if preserveMeta, ok := configMap["preserve_drizzle_meta"].(bool); ok {
			dp.config.PreserveDrizzleMeta = preserveMeta
		}
		if optimizeSeq, ok := configMap["optimize_sequences"].(bool); ok {
			dp.config.OptimizeSequences = optimizeSeq
		}
	}

	return nil
}

// EnrichStatement adds Drizzle-specific metadata to parsed statements
func (dp *DrizzlePlugin) EnrichStatement(ctx context.Context, stmt *types.Statement) error {
	sql := stmt.SQL
	sqlLower := strings.ToLower(sql)

	// Mark __drizzle_migrations table as critical
	if strings.Contains(sqlLower, "__drizzle_migrations") {
		stmt.Category = types.CategoryCritical
		if stmt.Comments == nil {
			stmt.Comments = []string{}
		}
		stmt.Comments = append(stmt.Comments, "Drizzle migration tracking table")
	}

	// Detect IDENTITY column usage
	if dp.hasIdentityColumn(sql) {
		if stmt.Comments == nil {
			stmt.Comments = []string{}
		}
		stmt.Comments = append(stmt.Comments, "Drizzle: Uses IDENTITY columns (PostgreSQL best practice)")
	}

	// Detect generated columns (Drizzle feature)
	if strings.Contains(sqlLower, "generated always as (") {
		if stmt.Comments == nil {
			stmt.Comments = []string{}
		}
		stmt.Comments = append(stmt.Comments, "Drizzle: Generated column")
	}

	return nil
}

// hasIdentityColumn checks if SQL uses IDENTITY columns
func (dp *DrizzlePlugin) hasIdentityColumn(sql string) bool {
	return containsKeywordSequenceCI(sql, []string{"GENERATED", "ALWAYS", "AS", "IDENTITY"}) ||
		containsKeywordSequenceCI(sql, []string{"GENERATED", "BY", "DEFAULT", "AS", "IDENTITY"})
}

// DetectPatterns analyzes SQL for Drizzle-specific patterns
func (dp *DrizzlePlugin) DetectPatterns(sql string) []plugins.Pattern {
	var patterns []plugins.Pattern

	// Pattern 1: IDENTITY columns
	if identityType, found := dp.ExtractIdentityType(sql); found {
		patterns = append(patterns, plugins.Pattern{
			Type:     plugins.PatternTypeORM,
			Name:     "drizzle_identity_column",
			Severity: plugins.SeverityHigh,
			Metadata: map[string]string{
				"type": strings.ToUpper(identityType),
			},
		})
	}

	// Pattern 2: __drizzle_migrations table
	if strings.Contains(strings.ToLower(sql), "__drizzle_migrations") {
		patterns = append(patterns, plugins.Pattern{
			Type:     plugins.PatternTypeSchema,
			Name:     "drizzle_migration_table",
			Severity: plugins.SeverityCritical,
			Metadata: map[string]string{
				"table": "__drizzle_migrations",
			},
		})
	}

	// Pattern 3: Generated columns
	sqlUpper := strings.ToUpper(sql)
	if containsKeywordSequenceCI(sqlUpper, []string{"GENERATED", "ALWAYS", "AS"}) &&
		strings.Contains(sqlUpper, "STORED") &&
		strings.Contains(sql, "(") {
		patterns = append(patterns, plugins.Pattern{
			Type:     plugins.PatternTypeORM,
			Name:     "drizzle_generated_column",
			Severity: plugins.SeverityMedium,
		})
	}

	return patterns
}

// GetConflictingPlugins returns plugins that conflict with Drizzle
func (dp *DrizzlePlugin) GetConflictingPlugins() []string {
	// Drizzle conflicts with other ORMs
	return []string{"prisma", "typeorm"}
}

// GetRequiredExtensions returns PostgreSQL extensions required by Drizzle
func (dp *DrizzlePlugin) GetRequiredExtensions() []string {
	return []string{
		"uuid-ossp", // For UUID generation
		"pgcrypto",  // For gen_random_uuid()
	}
}

// ShouldPreserve determines if a statement should never be consolidated
func (dp *DrizzlePlugin) ShouldPreserve(stmt *types.Statement) bool {
	sqlLower := strings.ToLower(stmt.SQL)

	// Always preserve __drizzle_migrations table
	if dp.config.PreserveDrizzleMeta && strings.Contains(sqlLower, "__drizzle_migrations") {
		return true
	}

	// Preserve IDENTITY column definitions (critical for auto-increment)
	if dp.config.PreferIdentityColumns && dp.hasIdentityColumn(stmt.SQL) {
		return true
	}

	// Preserve generated columns (computed columns)
	if strings.Contains(sqlLower, "generated always as (") &&
		strings.Contains(sqlLower, "stored") {
		return true
	}

	return false
}

// ValidateSchema performs Drizzle-specific schema validation
func (dp *DrizzlePlugin) ValidateSchema(ctx context.Context, db *sql.DB) error {
	// Verify __drizzle_migrations table exists if enabled
	if dp.config.PreserveDrizzleMeta {
		var tableExists bool
		err := db.QueryRowContext(ctx,
			"SELECT EXISTS(SELECT 1 FROM information_schema.tables WHERE table_name = '__drizzle_migrations')").
			Scan(&tableExists)
		if err != nil {
			return errors.Wrap(err, errors.ErrorCodeValidationFailed, errors.CategoryValidation,
				"failed to check __drizzle_migrations table",
				map[string]any{"table": "__drizzle_migrations"})
		}

		if !tableExists {
			return errors.New(errors.ErrorCodeValidationFailed, errors.CategoryValidation,
				"__drizzle_migrations table does not exist (expected for Drizzle project)",
				map[string]any{"table": "__drizzle_migrations"})
		}

		// Verify table structure
		var columnCount int
		err = db.QueryRowContext(ctx,
			"SELECT COUNT(*) FROM information_schema.columns WHERE table_name = '__drizzle_migrations'").
			Scan(&columnCount)
		if err != nil {
			return errors.Wrap(err, errors.ErrorCodeValidationFailed, errors.CategoryValidation,
				"failed to validate __drizzle_migrations structure",
				map[string]any{"table": "__drizzle_migrations"})
		}

		// Expected columns: id, hash, created_at
		if columnCount < 3 {
			return errors.New(errors.ErrorCodeValidationFailed, errors.CategoryValidation,
				"__drizzle_migrations table has incomplete structure",
				map[string]any{
					"table":            "__drizzle_migrations",
					"found_columns":    columnCount,
					"expected_columns": 3,
				})
		}
	}

	// Verify IDENTITY columns are properly configured
	if dp.config.PreferIdentityColumns {
		var identityColumnCount int
		err := db.QueryRowContext(ctx, `
			SELECT COUNT(*)
			FROM information_schema.columns
			WHERE is_identity = 'YES'
		`).Scan(&identityColumnCount)

		if err != nil {
			return errors.Wrap(err, errors.ErrorCodeValidationFailed, errors.CategoryValidation,
				"failed to check IDENTITY columns",
				map[string]any{"operation": "check_identity_columns"})
		}

		if identityColumnCount == 0 {
			// Warning, not error (project might not use auto-increment)
			fmt.Printf("Warning: No IDENTITY columns found (Drizzle typically uses IDENTITY)\n")
		}
	}

	return nil
}

func isDrizzleTimestampPath(path string) bool {
	lowerPath := strings.ToLower(path)
	_, after, ok := strings.Cut(lowerPath, "drizzle/")
	if !ok {
		return false
	}

	segment := after
	underscore := strings.Index(segment, "_")
	if underscore <= 0 {
		return false
	}

	timestamp := segment[:underscore]
	if len(timestamp) != 14 {
		return false
	}

	for i := 0; i < len(timestamp); i++ {
		if timestamp[i] < '0' || timestamp[i] > '9' {
			return false
		}
	}

	return true
}
