package drizzle

import (
	"context"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestOptimizeIdentityColumns(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()

	input := `CREATE TABLE users (
  id integer GENERATED ALWAYS AS IDENTITY (INCREMENT BY 1 START WITH 1 CACHE 1)
);`

	got := plugin.optimizeIdentityColumns(input)
	assert.Contains(t, got, "GENERATED ALWAYS AS IDENTITY")
	assert.NotContains(t, strings.ToUpper(got), "INCREMENT BY 1")
	assert.NotContains(t, strings.ToUpper(got), "START WITH 1")
	assert.NotContains(t, strings.ToUpper(got), "CACHE 1")
}

func TestOptimizeSequenceConfig(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()
	input := "ALTER SEQUENCE users_id_seq INCREMENT BY 1 CACHE 1;"

	got := plugin.optimizeSequenceConfig(input)
	assert.NotContains(t, strings.ToUpper(got), "INCREMENT BY 1")
	assert.NotContains(t, strings.ToUpper(got), "CACHE 1")
}

func TestFixFunctionVolatility(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()

	input := `CREATE FUNCTION public.normalize_email(input text)
RETURNS text
LANGUAGE sql
AS $$ SELECT lower(input); $$;`

	got, err := plugin.FixFunctionVolatility(context.Background(), input)
	assert.NoError(t, err)
	assert.Contains(t, strings.ToUpper(got), "LANGUAGE SQL STABLE AS $$")

	existing := `CREATE FUNCTION public.f() RETURNS text LANGUAGE sql IMMUTABLE AS $$ SELECT 'x'; $$;`
	unchanged, err := plugin.FixFunctionVolatility(context.Background(), existing)
	assert.NoError(t, err)
	assert.Equal(t, existing, unchanged)
}

func TestConvertSerialToIdentity(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()
	input := `CREATE TABLE t (id SERIAL PRIMARY KEY, big_id BIGSERIAL PRIMARY KEY);`

	got := plugin.ConvertSerialToIdentity(input)
	assert.Contains(t, got, "id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY")
	assert.Contains(t, got, "big_id BIGINT PRIMARY KEY GENERATED ALWAYS AS IDENTITY")
}

func TestExtractIdentityType(t *testing.T) {
	t.Parallel()

	plugin := NewDrizzlePlugin()

	typeName, found := plugin.ExtractIdentityType("id bigint GENERATED ALWAYS AS IDENTITY")
	assert.True(t, found)
	assert.Equal(t, "ALWAYS", typeName)

	typeName, found = plugin.ExtractIdentityType("id bigint GENERATED BY DEFAULT AS IDENTITY")
	assert.True(t, found)
	assert.Equal(t, "BY DEFAULT", typeName)

	typeName, found = plugin.ExtractIdentityType("id bigint")
	assert.False(t, found)
	assert.Equal(t, "", typeName)
}
