package drizzle

import (
	"context"
	"strings"

	"github.com/capy-base/pgsquash-engine/internal/utils"
)

// TransformSQL performs Drizzle-specific SQL transformations
func (dp *DrizzlePlugin) TransformSQL(ctx context.Context, sql string) (string, error) {
	transformed := sql

	// Transformation 1: Optimize IDENTITY columns if configured
	if dp.config.PreferIdentityColumns {
		transformed = dp.optimizeIdentityColumns(transformed)
	}

	// Transformation 2: Optimize sequence configurations
	if dp.config.OptimizeSequences {
		transformed = dp.optimizeSequenceConfig(transformed)
	}

	return transformed, nil
}

// optimizeIdentityColumns ensures IDENTITY columns use optimal PostgreSQL configuration
func (dp *DrizzlePlugin) optimizeIdentityColumns(sql string) string {
	// Drizzle generates comprehensive IDENTITY configurations
	// Pattern: GENERATED ALWAYS AS IDENTITY (sequence name "..." INCREMENT BY 1 MINVALUE 1 MAXVALUE ... START WITH ... CACHE 1)
	//
	// Optimization: Remove redundant defaults
	// - CACHE 1 is default (can be removed)
	// - INCREMENT BY 1 is default
	// - START WITH 1 is default

	return transformIdentityClauses(sql, func(clause string) string {
		// Simplify if it's just using defaults
		upperClause := strings.ToUpper(clause)
		if strings.Contains(upperClause, "INCREMENT BY 1") &&
			strings.Contains(upperClause, "START WITH 1") &&
			strings.Contains(upperClause, "CACHE 1") {
			// Can simplify to just GENERATED ALWAYS AS IDENTITY
			if strings.Contains(upperClause, "GENERATED ALWAYS") {
				return "GENERATED ALWAYS AS IDENTITY"
			}
			return "GENERATED BY DEFAULT AS IDENTITY"
		}

		// Keep full configuration if custom values
		return clause
	})
}

// optimizeSequenceConfig removes redundant sequence configuration
func (dp *DrizzlePlugin) optimizeSequenceConfig(sql string) string {
	// Drizzle can generate verbose ALTER SEQUENCE statements
	// Remove redundant default values

	// Remove CACHE 1 (default)
	sql = removeKeywordSequence(sql, []string{"CACHE", "1"})

	// Remove INCREMENT BY 1 (default)
	sql = removeKeywordSequence(sql, []string{"INCREMENT", "BY", "1"})

	return sql
}

// InjectCompatibilityLayer returns SQL for Drizzle compatibility during validation
func (dp *DrizzlePlugin) InjectCompatibilityLayer(ctx context.Context) string {
	if !dp.config.PreserveDrizzleMeta {
		return ""
	}

	return `-- Drizzle Migration Compatibility Layer
-- Create __drizzle_migrations table for migration tracking

CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
    "id" SERIAL PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "created_at" BIGINT
);

-- Insert mock migration record
INSERT INTO "__drizzle_migrations" (hash, created_at)
VALUES ('mock_drizzle_hash', extract(epoch from now())::bigint * 1000)
ON CONFLICT (id) DO NOTHING;
`
}

// FixFunctionVolatility adds volatility markers to Drizzle-generated functions
func (dp *DrizzlePlugin) FixFunctionVolatility(ctx context.Context, functionSQL string) (string, error) {
	// Drizzle rarely generates custom functions
	// But if it does (for generated columns or triggers), mark them appropriately

	if !strings.Contains(strings.ToUpper(functionSQL), "CREATE FUNCTION") {
		return functionSQL, nil
	}

	// Check if volatility marker already exists (using shared utility)
	if utils.HasVolatilityMarker(functionSQL) {
		return functionSQL, nil
	}

	// For generated column functions, use IMMUTABLE (pure computation)
	// For trigger functions, use VOLATILE (modifies data)
	volatility := "STABLE" // Safe default

	if strings.Contains(strings.ToLower(functionSQL), "trigger") {
		volatility = "VOLATILE"
	} else if strings.Contains(strings.ToLower(functionSQL), "generated") {
		volatility = "IMMUTABLE"
	}

	// Add volatility marker before AS keyword
	return insertMarkerBeforeAS(functionSQL, volatility), nil
}

// ConvertSerialToIdentity converts old SERIAL columns to modern IDENTITY
// This is an optional transformation for legacy Drizzle migrations
func (dp *DrizzlePlugin) ConvertSerialToIdentity(sql string) string {
	if !dp.config.PreferIdentityColumns {
		return sql
	}

	converted := replaceColumnTypePrimaryKey(sql, "SERIAL", "INTEGER")
	converted = replaceColumnTypePrimaryKey(converted, "BIGSERIAL", "BIGINT")

	return converted
}

// IsDrizzleGeneratedSQL checks if SQL appears to be Drizzle-generated
func (dp *DrizzlePlugin) IsDrizzleGeneratedSQL(sql string) bool {
	// Check for Drizzle patterns
	patterns := []string{
		"__drizzle_migrations",
		"GENERATED ALWAYS AS IDENTITY",
		"GENERATED BY DEFAULT AS IDENTITY",
	}

	sqlLower := strings.ToLower(sql)
	for _, pattern := range patterns {
		if strings.Contains(sqlLower, strings.ToLower(pattern)) {
			return true
		}
	}

	// Check for Drizzle-specific comments
	if strings.Contains(sql, "-- drizzle-kit") ||
		strings.Contains(sql, "-- Drizzle") {
		return true
	}

	return false
}

// ExtractIdentityType extracts the IDENTITY type from SQL
func (dp *DrizzlePlugin) ExtractIdentityType(sql string) (identityType string, found bool) {
	if containsKeywordSequenceCI(sql, []string{"GENERATED", "ALWAYS", "AS", "IDENTITY"}) {
		return "ALWAYS", true
	}

	if containsKeywordSequenceCI(sql, []string{"GENERATED", "BY", "DEFAULT", "AS", "IDENTITY"}) {
		return "BY DEFAULT", true
	}

	return "", false
}

func transformIdentityClauses(sql string, transform func(clause string) string) string {
	if sql == "" {
		return sql
	}

	var out strings.Builder
	cursor := 0

	for {
		start, end, clause, ok := nextIdentityClause(sql, cursor)
		if !ok {
			out.WriteString(sql[cursor:])
			break
		}

		out.WriteString(sql[cursor:start])
		out.WriteString(transform(clause))
		cursor = end
	}

	return out.String()
}

func nextIdentityClause(sql string, from int) (int, int, string, bool) {
	for i := from; i < len(sql); i++ {
		if !hasKeywordAtCI(sql, i, "GENERATED") {
			continue
		}

		j := i + len("GENERATED")
		j = skipSQLWhitespace(sql, j)

		if hasKeywordAtCI(sql, j, "ALWAYS") {
			j += len("ALWAYS")
		} else if hasKeywordAtCI(sql, j, "BY") {
			j += len("BY")
			j = skipSQLWhitespace(sql, j)
			if !hasKeywordAtCI(sql, j, "DEFAULT") {
				continue
			}
			j += len("DEFAULT")
		} else {
			continue
		}

		j = skipSQLWhitespace(sql, j)
		if !hasKeywordAtCI(sql, j, "AS") {
			continue
		}
		j += len("AS")

		j = skipSQLWhitespace(sql, j)
		if !hasKeywordAtCI(sql, j, "IDENTITY") {
			continue
		}
		j += len("IDENTITY")

		j = skipSQLWhitespace(sql, j)
		if j < len(sql) && sql[j] == '(' {
			close := findMatchingParen(sql, j)
			if close == -1 {
				return i, len(sql), sql[i:], true
			}
			return i, close + 1, sql[i : close+1], true
		}

		return i, j, sql[i:j], true
	}

	return 0, 0, "", false
}

func removeKeywordSequence(sql string, words []string) string {
	if sql == "" || len(words) == 0 {
		return sql
	}

	var out strings.Builder
	cursor := 0

	for {
		start, end, ok := findKeywordSequenceSpan(sql, cursor, words)
		if !ok {
			out.WriteString(sql[cursor:])
			break
		}

		out.WriteString(sql[cursor:start])
		cursor = end
	}

	return out.String()
}

func findKeywordSequenceSpan(sql string, from int, words []string) (int, int, bool) {
	for i := from; i < len(sql); i++ {
		if !hasKeywordAtCI(sql, i, words[0]) {
			continue
		}

		idx := i + len(words[0])
		matched := true
		for w := 1; w < len(words); w++ {
			idx = skipSQLWhitespace(sql, idx)
			if !hasKeywordAtCI(sql, idx, words[w]) {
				matched = false
				break
			}
			idx += len(words[w])
		}

		if !matched {
			continue
		}

		start := i
		for start > 0 && isSQLWhitespace(sql[start-1]) {
			start--
		}

		end := idx
		for end < len(sql) && isSQLWhitespace(sql[end]) {
			end++
		}

		return start, end, true
	}

	return 0, 0, false
}

func insertMarkerBeforeAS(sql string, marker string) string {
	trimmedMarker := strings.TrimSpace(marker)
	if sql == "" || trimmedMarker == "" {
		return sql
	}

	asIdx := findStandaloneASIndex(sql)
	if asIdx == -1 {
		return sql
	}

	prefix := strings.TrimRight(sql[:asIdx], " \t\r\n")
	suffix := strings.TrimLeft(sql[asIdx:], " \t\r\n")
	if prefix == "" {
		return trimmedMarker + " " + suffix
	}

	return prefix + " " + trimmedMarker + " " + suffix
}

func findStandaloneASIndex(sql string) int {
	for i := 0; i < len(sql); i++ {
		if hasKeywordAtCI(sql, i, "AS") {
			return i
		}
	}
	return -1
}

func replaceColumnTypePrimaryKey(sql string, sourceType string, targetType string) string {
	if sql == "" {
		return sql
	}

	var out strings.Builder
	cursor := 0

	for {
		start, end, columnName, ok := findColumnTypePrimaryKeySpan(sql, cursor, sourceType)
		if !ok {
			out.WriteString(sql[cursor:])
			break
		}

		out.WriteString(sql[cursor:start])
		out.WriteString(columnName)
		out.WriteString(" ")
		out.WriteString(targetType)
		out.WriteString(" PRIMARY KEY GENERATED ALWAYS AS IDENTITY")

		cursor = end
	}

	return out.String()
}

func findColumnTypePrimaryKeySpan(sql string, from int, sourceType string) (int, int, string, bool) {
	for i := from; i < len(sql); i++ {
		if !isIdentifierStart(sql[i]) {
			continue
		}

		start := i
		columnName, next, ok := readIdentifier(sql, i)
		if !ok {
			continue
		}

		next = skipSQLWhitespace(sql, next)
		if !hasKeywordAtCI(sql, next, sourceType) {
			continue
		}
		next += len(sourceType)

		next = skipSQLWhitespace(sql, next)
		if !hasKeywordAtCI(sql, next, "PRIMARY") {
			continue
		}
		next += len("PRIMARY")

		next = skipSQLWhitespace(sql, next)
		if !hasKeywordAtCI(sql, next, "KEY") {
			continue
		}
		next += len("KEY")

		return start, next, columnName, true
	}

	return 0, 0, "", false
}

func readIdentifier(sql string, start int) (string, int, bool) {
	if start < 0 || start >= len(sql) {
		return "", 0, false
	}

	if sql[start] == '"' {
		for i := start + 1; i < len(sql); i++ {
			if sql[i] == '"' {
				return sql[start : i+1], i + 1, true
			}
		}
		return "", 0, false
	}

	i := start
	for i < len(sql) && isIdentifierPart(sql[i]) {
		i++
	}
	if i == start {
		return "", 0, false
	}

	return sql[start:i], i, true
}

func containsKeywordSequenceCI(sql string, words []string) bool {
	if sql == "" || len(words) == 0 {
		return false
	}

	for i := 0; i < len(sql); i++ {
		if !hasKeywordAtCI(sql, i, words[0]) {
			continue
		}

		idx := i + len(words[0])
		matched := true
		for w := 1; w < len(words); w++ {
			idx = skipSQLWhitespace(sql, idx)
			if !hasKeywordAtCI(sql, idx, words[w]) {
				matched = false
				break
			}
			idx += len(words[w])
		}

		if matched {
			return true
		}
	}

	return false
}

func hasKeywordAtCI(sql string, pos int, keyword string) bool {
	if pos < 0 || pos+len(keyword) > len(sql) {
		return false
	}

	if pos > 0 && isIdentifierPart(sql[pos-1]) {
		return false
	}

	segment := sql[pos : pos+len(keyword)]
	if !strings.EqualFold(segment, keyword) {
		return false
	}

	end := pos + len(keyword)
	if end < len(sql) && isIdentifierPart(sql[end]) {
		return false
	}

	return true
}

func skipSQLWhitespace(sql string, pos int) int {
	for pos < len(sql) && isSQLWhitespace(sql[pos]) {
		pos++
	}
	return pos
}

func isSQLWhitespace(ch byte) bool {
	switch ch {
	case ' ', '\t', '\n', '\r', '\f', '\v':
		return true
	default:
		return false
	}
}

func isIdentifierStart(ch byte) bool {
	return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') || ch == '_'
}

func isIdentifierPart(ch byte) bool {
	return isIdentifierStart(ch) || (ch >= '0' && ch <= '9')
}

func findMatchingParen(sql string, openIndex int) int {
	if openIndex < 0 || openIndex >= len(sql) || sql[openIndex] != '(' {
		return -1
	}

	depth := 0
	inSingleQuote := false
	inDoubleQuote := false

	for i := openIndex; i < len(sql); i++ {
		ch := sql[i]

		if inSingleQuote {
			if ch == '\'' {
				if i+1 < len(sql) && sql[i+1] == '\'' {
					i++
					continue
				}
				inSingleQuote = false
			}
			continue
		}

		if inDoubleQuote {
			if ch == '"' {
				if i+1 < len(sql) && sql[i+1] == '"' {
					i++
					continue
				}
				inDoubleQuote = false
			}
			continue
		}

		switch ch {
		case '\'':
			inSingleQuote = true
		case '"':
			inDoubleQuote = true
		case '(':
			depth++
		case ')':
			depth--
			if depth == 0 {
				return i
			}
		}
	}

	return -1
}
