package drizzle

import (
	"context"
	"fmt"
	"regexp"
	"strings"

	"github.com/capysquash/pgsquash-engine/internal/utils"
)

// TransformSQL performs Drizzle-specific SQL transformations
func (dp *DrizzlePlugin) TransformSQL(ctx context.Context, sql string) (string, error) {
	transformed := sql

	// Transformation 1: Optimize IDENTITY columns if configured
	if dp.config.PreferIdentityColumns {
		transformed = dp.optimizeIdentityColumns(transformed)
	}

	// Transformation 2: Optimize sequence configurations
	if dp.config.OptimizeSequences {
		transformed = dp.optimizeSequenceConfig(transformed)
	}

	return transformed, nil
}

// optimizeIdentityColumns ensures IDENTITY columns use optimal PostgreSQL configuration
func (dp *DrizzlePlugin) optimizeIdentityColumns(sql string) string {
	// Drizzle generates comprehensive IDENTITY configurations
	// Pattern: GENERATED ALWAYS AS IDENTITY (sequence name "..." INCREMENT BY 1 MINVALUE 1 MAXVALUE ... START WITH ... CACHE 1)
	//
	// Optimization: Remove redundant defaults
	// - CACHE 1 is default (can be removed)
	// - INCREMENT BY 1 is default
	// - START WITH 1 is default

	identityPattern := regexp.MustCompile(`(?i)(GENERATED\s+(?:ALWAYS|BY\s+DEFAULT)\s+AS\s+IDENTITY\s*\([^)]+\))`)

	return identityPattern.ReplaceAllStringFunc(sql, func(match string) string {
		// Simplify if it's just using defaults
		if strings.Contains(match, "INCREMENT BY 1") &&
			strings.Contains(match, "START WITH 1") &&
			strings.Contains(match, "CACHE 1") {
			// Can simplify to just GENERATED ALWAYS AS IDENTITY
			if strings.Contains(strings.ToUpper(match), "GENERATED ALWAYS") {
				return "GENERATED ALWAYS AS IDENTITY"
			}
			return "GENERATED BY DEFAULT AS IDENTITY"
		}

		// Keep full configuration if custom values
		return match
	})
}

// optimizeSequenceConfig removes redundant sequence configuration
func (dp *DrizzlePlugin) optimizeSequenceConfig(sql string) string {
	// Drizzle can generate verbose ALTER SEQUENCE statements
	// Remove redundant default values

	// Remove CACHE 1 (default)
	sql = regexp.MustCompile(`(?i)\s+CACHE\s+1\s*`).ReplaceAllString(sql, " ")

	// Remove INCREMENT BY 1 (default)
	sql = regexp.MustCompile(`(?i)\s+INCREMENT\s+BY\s+1\s*`).ReplaceAllString(sql, " ")

	return sql
}

// InjectCompatibilityLayer returns SQL for Drizzle compatibility during validation
func (dp *DrizzlePlugin) InjectCompatibilityLayer(ctx context.Context) string {
	if !dp.config.PreserveDrizzleMeta {
		return ""
	}

	return `-- Drizzle Migration Compatibility Layer
-- Create __drizzle_migrations table for migration tracking

CREATE TABLE IF NOT EXISTS "__drizzle_migrations" (
    "id" SERIAL PRIMARY KEY,
    "hash" TEXT NOT NULL,
    "created_at" BIGINT
);

-- Insert mock migration record
INSERT INTO "__drizzle_migrations" (hash, created_at)
VALUES ('mock_drizzle_hash', extract(epoch from now())::bigint * 1000)
ON CONFLICT (id) DO NOTHING;
`
}

// FixFunctionVolatility adds volatility markers to Drizzle-generated functions
func (dp *DrizzlePlugin) FixFunctionVolatility(ctx context.Context, functionSQL string) (string, error) {
	// Drizzle rarely generates custom functions
	// But if it does (for generated columns or triggers), mark them appropriately

	if !strings.Contains(strings.ToUpper(functionSQL), "CREATE FUNCTION") {
		return functionSQL, nil
	}

	// Check if volatility marker already exists (using shared utility)
	if utils.HasVolatilityMarker(functionSQL) {
		return functionSQL, nil
	}

	// For generated column functions, use IMMUTABLE (pure computation)
	// For trigger functions, use VOLATILE (modifies data)
	volatility := "STABLE" // Safe default

	if strings.Contains(strings.ToLower(functionSQL), "trigger") {
		volatility = "VOLATILE"
	} else if strings.Contains(strings.ToLower(functionSQL), "generated") {
		volatility = "IMMUTABLE"
	}

	// Add volatility marker before AS keyword
	asPattern := regexp.MustCompile(`(?i)(\s+AS\s+)`)
	fixed := asPattern.ReplaceAllString(functionSQL, fmt.Sprintf(" %s$1", volatility))

	return fixed, nil
}

// ConvertSerialToIdentity converts old SERIAL columns to modern IDENTITY
// This is an optional transformation for legacy Drizzle migrations
func (dp *DrizzlePlugin) ConvertSerialToIdentity(sql string) string {
	if !dp.config.PreferIdentityColumns {
		return sql
	}

	// Pattern: column_name SERIAL PRIMARY KEY
	// Convert to: column_name INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY

	serialPattern := regexp.MustCompile(`(?i)(\w+)\s+SERIAL\s+(PRIMARY\s+KEY)`)
	converted := serialPattern.ReplaceAllString(sql,
		"$1 INTEGER $2 GENERATED ALWAYS AS IDENTITY")

	// Pattern: column_name BIGSERIAL PRIMARY KEY
	bigserialPattern := regexp.MustCompile(`(?i)(\w+)\s+BIGSERIAL\s+(PRIMARY\s+KEY)`)
	converted = bigserialPattern.ReplaceAllString(converted,
		"$1 BIGINT $2 GENERATED ALWAYS AS IDENTITY")

	return converted
}

// IsDrizzleGeneratedSQL checks if SQL appears to be Drizzle-generated
func (dp *DrizzlePlugin) IsDrizzleGeneratedSQL(sql string) bool {
	// Check for Drizzle patterns
	patterns := []string{
		"__drizzle_migrations",
		"GENERATED ALWAYS AS IDENTITY",
		"GENERATED BY DEFAULT AS IDENTITY",
	}

	sqlLower := strings.ToLower(sql)
	for _, pattern := range patterns {
		if strings.Contains(sqlLower, strings.ToLower(pattern)) {
			return true
		}
	}

	// Check for Drizzle-specific comments
	if strings.Contains(sql, "-- drizzle-kit") ||
		strings.Contains(sql, "-- Drizzle") {
		return true
	}

	return false
}

// ExtractIdentityType extracts the IDENTITY type from SQL
func (dp *DrizzlePlugin) ExtractIdentityType(sql string) (identityType string, found bool) {
	alwaysPattern := regexp.MustCompile(`(?i)GENERATED\s+ALWAYS\s+AS\s+IDENTITY`)
	if alwaysPattern.MatchString(sql) {
		return "ALWAYS", true
	}

	defaultPattern := regexp.MustCompile(`(?i)GENERATED\s+BY\s+DEFAULT\s+AS\s+IDENTITY`)
	if defaultPattern.MatchString(sql) {
		return "BY DEFAULT", true
	}

	return "", false
}
