-- Data Operations - Generated by pgsquash
-- IMPORTANT: These are non-idempotent operations (INSERT/UPDATE/DELETE)
-- Run these AFTER the baseline schema is applied
-- Safety level: standard
-- Generated at: 2025-11-07T12:01:08+02:00

-- Total data operations: 14 (sorted by dependencies)

-- INSERT on storage.buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'generated-packages',
  'generated-packages',
  true, -- Public bucket for easy access
  52428800, -- 50MB limit per file
  ARRAY[
    'application/zip',
    'application/x-sh',
    'application/json',
    'text/plain',
    'application/octet-stream'
  ]
) ON CONFLICT (id) DO UPDATE SET
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

-- INSERT on storage.buckets
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'avatars',
  'avatars',
  true, -- Public bucket for easy access to profile images
  2097152, -- 2MB limit for profile images
  ARRAY[
    'image/jpeg',
    'image/jpg',
    'image/png',
    'image/webp',
    'image/gif'
  ]
) ON CONFLICT (id) DO NOTHING;

-- INSERT on public.categories
INSERT INTO public.categories (name, slug, description, icon, category_type, order_index) VALUES
  ('Core Blueprints', 'core', 'Fundamental AI behavior patterns', '🔧', 'core', 1),
  ('Programming Languages', 'languages', 'Language-specific development patterns', '💻', 'language', 2),
  ('Technologies & Frameworks', 'technologies', 'Framework and tool-specific guidelines', '⚡', 'technology', 3),
  ('Technology Stacks', 'stacks', 'Full-stack technology combinations', '🏗️', 'stack', 4),
  ('Development Tasks', 'tasks', 'Executable development workflows', '✅', 'task', 5),
  ('AI Assistants', 'assistants', 'AI platform-specific configurations', '🤖', 'assistant', 6),
  ('Development Tools', 'tools', 'Tool-specific usage patterns', '🛠️', 'tool', 7)
ON CONFLICT (slug) DO UPDATE SET
  category_type = EXCLUDED.category_type,
  metadata = EXCLUDED.metadata;

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'task' WHERE slug IN ('tasks');

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'language' WHERE slug IN ('languages');

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'technology' WHERE slug IN ('technologies');

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'stack' WHERE slug IN ('stacks');

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'assistant' WHERE slug IN ('assistants');

-- UPDATE on public.categories
UPDATE public.categories SET category_type = 'tool' WHERE slug IN ('tools');

-- INSERT on vdk_versions
INSERT INTO vdk_versions (component, version, status, description, created_at) VALUES
('cli', '1.0.0', 'stable', 'Initial stable release of VDK CLI', CURRENT_TIMESTAMP),
('cli', '1.1.0', 'stable', 'Added Windsurf integration support', CURRENT_TIMESTAMP),
('cli', '1.2.0', 'stable', 'Enhanced analytics and platform support', CURRENT_TIMESTAMP),
('cli', '2.0.0', 'stable', 'Major release with full platform parity', CURRENT_TIMESTAMP),
('hub', '1.0.0', 'stable', 'Initial VDK Hub release', CURRENT_TIMESTAMP),
('hub', '2.0.0', 'stable', 'Enhanced Hub with CLI integration', CURRENT_TIMESTAMP)
ON CONFLICT DO NOTHING;

-- UPDATE on public.categories
UPDATE public.categories 
SET supported_platforms = ARRAY[
  'claude-code',
  'claude-desktop',
  'cursor',
  'windsurf',
  'windsurf-next',
  'github-copilot', 
  'zed',
  'vscode',
  'vscode-insiders',
  'vscodium',
  'jetbrains',
  'intellij',
  'webstorm',
  'pycharm',
  'phpstorm',
  'rubymine',
  'clion',
  'datagrip',
  'goland',
  'rider',
  'android-studio',
  'openai',
  'generic-ai'
] 
WHERE supported_platforms = ARRAY['claude-code', 'cursor', 'windsurf', 'github-copilot'];

-- INSERT on community_blueprints
INSERT INTO community_blueprints (
  slug,
  title, 
  description,
  content,
  author_id,
  author_username,
  category,
  framework,
  language,
  tags,
  complexity,
  platforms,
  status,
  published_at
) VALUES 
(
  'react-performance-patterns',
  'React Performance Optimization Patterns',
  'Advanced patterns for optimizing React application performance',
  '# React Performance Optimization
This blueprint provides comprehensive patterns for optimizing React applications:
## Key Patterns
1. **Memoization Strategies**
   - React.memo for component memoization
   - useMemo for expensive calculations
   - useCallback for function references
2. **Code Splitting**
   - Route-based splitting
   - Component-based splitting
   - Dynamic imports
3. **Bundle Optimization**
   - Tree shaking
   - Dead code elimination
   - Chunk optimization
## Implementation
```tsx
import React, { memo, useMemo, useCallback } from ''react'';
const OptimizedComponent = memo(({ data, onUpdate }) => {
  const expensiveValue = useMemo(() => 
    data.reduce((acc, item) => acc + item.value, 0), [data]
  );
  const handleClick = useCallback((id) => {
    onUpdate(id);
  }, [onUpdate]);
  return (
    <div>
      <h2>Total: {expensiveValue}</h2>
      {data.map(item => (
        <Item 
          key={item.id} 
          data={item} 
          onClick={handleClick}
        />
      ))}
    </div>
  );
});
```
## Best Practices
- Always measure before optimizing
- Use React DevTools Profiler
- Implement proper error boundaries
- Optimize re-renders with proper dependencies',
  '00000000-0000-0000-0000-000000000001'::uuid,
  'react-expert',
  'frontend',
  'React',
  'TypeScript',
  '["react", "performance", "optimization", "typescript"]'::jsonb,
  'advanced',
  '{
    "claude-code": {
      "compatible": true,
      "config": {
        "command": true,
        "memory": true,
        "characterLimit": 4000
      },
      "priority": 9
    },
    "cursor": {
      "compatible": true,
      "config": {
        "characterLimit": 6000,
        "directory": ".ai/rules/",
        "format": "mdc"
      },
      "priority": 8
    }
  }'::jsonb,
  'published',
  NOW()
),
(
  'nodejs-api-best-practices',
  'Node.js API Development Best Practices',
  'Comprehensive guide for building robust Node.js APIs',
  '# Node.js API Development Best Practices
## Security
- Input validation and sanitization
- Rate limiting implementation
- Authentication and authorization
- CORS configuration
## Performance
- Database query optimization
- Caching strategies
- Connection pooling
- Response compression
## Error Handling
- Centralized error handling
- Proper HTTP status codes
- Logging and monitoring
- Graceful degradation',
  '00000000-0000-0000-0000-000000000001'::uuid,
  'nodejs-dev',
  'backend',
  'Node.js',
  'JavaScript',
  '["nodejs", "api", "backend", "security"]'::jsonb,
  'intermediate',
  '{
    "claude-code": {"compatible": true, "priority": 8},
    "cursor": {"compatible": true, "priority": 7}
  }'::jsonb,
  'published',
  NOW()
);

-- INSERT on blueprint_usage
INSERT INTO blueprint_usage (
  blueprint_id,
  session_id,
  framework,
  language,
  platform,
  cli_version,
  success,
  platforms_deployed,
  adaptation_count,
  compatibility_score,
  deployed_at
) VALUES 
(
  (SELECT id FROM community_blueprints WHERE slug = 'react-performance-patterns'),
  'session_001',
  'nextjs',
  'typescript',
  'claude-code',
  '2.0.0',
  true,
  '["claude-code", "cursor"]'::jsonb,
  2,
  0.95,
  NOW() - INTERVAL '2 days'
),
(
  (SELECT id FROM community_blueprints WHERE slug = 'react-performance-patterns'),
  'session_002',
  'react',
  'typescript',
  'cursor',
  '2.0.0',
  true,
  '["cursor"]'::jsonb,
  1,
  0.88,
  NOW() - INTERVAL '1 day'
),
(
  (SELECT id FROM community_blueprints WHERE slug = 'nodejs-api-best-practices'),
  'session_003',
  'express',
  'javascript',
  'claude-code',
  '2.0.0',
  true,
  '["claude-code"]'::jsonb,
  0,
  0.92,
  NOW() - INTERVAL '3 hours'
);

-- INSERT on blueprint_votes
INSERT INTO blueprint_votes (
  blueprint_id,
  user_id,
  vote_type,
  rating,
  comment
) VALUES 
(
  (SELECT id FROM community_blueprints WHERE slug = 'react-performance-patterns'),
  '00000000-0000-0000-0000-000000000002'::uuid,
  'up',
  5,
  'Excellent patterns! Helped optimize our app significantly.'
),
(
  (SELECT id FROM community_blueprints WHERE slug = 'react-performance-patterns'),
  '00000000-0000-0000-0000-000000000003'::uuid,
  'up',
  4,
  'Very useful, clear examples and good explanations.'
),
(
  (SELECT id FROM community_blueprints WHERE slug = 'nodejs-api-best-practices'),
  '00000000-0000-0000-0000-000000000002'::uuid,
  'up',
  4,
  'Solid foundation for API development.'
);

