// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type PgAm struct {
	Oid    sql.NullInt64  `json:"oid"`
	Amname sql.NullString `json:"amname"`
}

type PgAttrdef struct {
	Adrelid sql.NullInt64  `json:"adrelid"`
	Adnum   sql.NullInt32  `json:"adnum"`
	Adbin   sql.NullString `json:"adbin"`
}

type PgAttribute struct {
	Attrelid     sql.NullInt64  `json:"attrelid"`
	Attnum       sql.NullInt32  `json:"attnum"`
	Attname      sql.NullString `json:"attname"`
	Atttypid     sql.NullInt64  `json:"atttypid"`
	Atttypmod    sql.NullInt32  `json:"atttypmod"`
	Attnotnull   sql.NullBool   `json:"attnotnull"`
	Attisdropped sql.NullBool   `json:"attisdropped"`
}

type PgClass struct {
	Oid            sql.NullInt64  `json:"oid"`
	Relname        sql.NullString `json:"relname"`
	Relnamespace   sql.NullInt64  `json:"relnamespace"`
	Relkind        sql.NullString `json:"relkind"`
	Relam          sql.NullInt64  `json:"relam"`
	Relrowsecurity sql.NullBool   `json:"relrowsecurity"`
}

type PgConstraint struct {
	Oid           sql.NullInt64  `json:"oid"`
	Conname       sql.NullString `json:"conname"`
	Connamespace  sql.NullInt64  `json:"connamespace"`
	Condeferrable sql.NullBool   `json:"condeferrable"`
	Condeferred   sql.NullBool   `json:"condeferred"`
	Conrelid      sql.NullInt64  `json:"conrelid"`
}

type PgDepend struct {
	Objid       sql.NullInt64  `json:"objid"`
	Deptype     sql.NullString `json:"deptype"`
	Refobjid    sql.NullInt64  `json:"refobjid"`
	Refobjsubid sql.NullInt32  `json:"refobjsubid"`
}

type PgDescription struct {
	Objoid      sql.NullInt64  `json:"objoid"`
	Objsubid    sql.NullInt32  `json:"objsubid"`
	Description sql.NullString `json:"description"`
}

type PgEnum struct {
	Enumtypid     sql.NullInt64   `json:"enumtypid"`
	Enumlabel     sql.NullString  `json:"enumlabel"`
	Enumsortorder sql.NullFloat64 `json:"enumsortorder"`
}

type PgExtension struct {
	Oid            sql.NullInt64  `json:"oid"`
	Extname        sql.NullString `json:"extname"`
	Extversion     sql.NullString `json:"extversion"`
	Extnamespace   sql.NullInt64  `json:"extnamespace"`
	Extrelocatable sql.NullBool   `json:"extrelocatable"`
}

type PgIndex struct {
	Indrelid     sql.NullInt64  `json:"indrelid"`
	Indexrelid   sql.NullInt64  `json:"indexrelid"`
	Indkey       []int32        `json:"indkey"`
	Indisunique  sql.NullBool   `json:"indisunique"`
	Indisprimary sql.NullBool   `json:"indisprimary"`
	Indpred      sql.NullString `json:"indpred"`
}

type PgLanguage struct {
	Oid     sql.NullInt64  `json:"oid"`
	Lanname sql.NullString `json:"lanname"`
}

type PgMatview struct {
	Schemaname  sql.NullString `json:"schemaname"`
	Matviewname sql.NullString `json:"matviewname"`
	Definition  sql.NullString `json:"definition"`
	Ispopulated sql.NullBool   `json:"ispopulated"`
}

type PgNamespace struct {
	Oid     sql.NullInt64  `json:"oid"`
	Nspname sql.NullString `json:"nspname"`
}

type PgPolicy struct {
	Polname       sql.NullString `json:"polname"`
	Polcmd        sql.NullString `json:"polcmd"`
	Polpermissive sql.NullBool   `json:"polpermissive"`
	Polroles      []int64        `json:"polroles"`
	Polqual       sql.NullString `json:"polqual"`
	Polwithcheck  sql.NullString `json:"polwithcheck"`
	Polrelid      sql.NullInt64  `json:"polrelid"`
}

type PgProc struct {
	Oid          sql.NullInt64  `json:"oid"`
	Proname      sql.NullString `json:"proname"`
	Pronamespace sql.NullInt64  `json:"pronamespace"`
	Prolang      sql.NullInt64  `json:"prolang"`
	Provolatile  sql.NullString `json:"provolatile"`
	Proisstrict  sql.NullBool   `json:"proisstrict"`
	Prosecdef    sql.NullBool   `json:"prosecdef"`
	Prokind      sql.NullString `json:"prokind"`
}

type PgRole struct {
	Oid     sql.NullInt64  `json:"oid"`
	Rolname sql.NullString `json:"rolname"`
}

type PgSequence struct {
	Seqrelid     sql.NullInt64 `json:"seqrelid"`
	Seqtypid     sql.NullInt64 `json:"seqtypid"`
	Seqstart     sql.NullInt64 `json:"seqstart"`
	Seqincrement sql.NullInt64 `json:"seqincrement"`
	Seqmin       sql.NullInt64 `json:"seqmin"`
	Seqmax       sql.NullInt64 `json:"seqmax"`
	Seqcache     sql.NullInt64 `json:"seqcache"`
	Seqcycle     sql.NullBool  `json:"seqcycle"`
}

type PgTrigger struct {
	Oid          sql.NullInt64  `json:"oid"`
	Tgname       sql.NullString `json:"tgname"`
	Tgrelid      sql.NullInt64  `json:"tgrelid"`
	Tgfoid       sql.NullInt64  `json:"tgfoid"`
	Tgtype       sql.NullInt32  `json:"tgtype"`
	Tgqual       sql.NullString `json:"tgqual"`
	Tgenabled    sql.NullString `json:"tgenabled"`
	Tgisinternal sql.NullBool   `json:"tgisinternal"`
}

type PgType struct {
	Oid          sql.NullInt64  `json:"oid"`
	Typname      sql.NullString `json:"typname"`
	Typnamespace sql.NullInt64  `json:"typnamespace"`
	Typtype      sql.NullString `json:"typtype"`
}
