// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"

	"github.com/lib/pq"
)

const getPostgresVersion = `-- name: GetPostgresVersion :one
SELECT version() AS version
`

func (q *Queries) GetPostgresVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPostgresVersion)
	var version string
	err := row.Scan(&version)
	return version, err
}

const getSearchPath = `-- name: GetSearchPath :one
SELECT current_setting('search_path') AS search_path
`

func (q *Queries) GetSearchPath(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getSearchPath)
	var search_path string
	err := row.Scan(&search_path)
	return search_path, err
}

const getTableRowSecurity = `-- name: GetTableRowSecurity :one
SELECT COALESCE(c.relrowsecurity, false) AS row_security
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = $1::text
  AND c.relname = $2::text
LIMIT 1
`

type GetTableRowSecurityParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

func (q *Queries) GetTableRowSecurity(ctx context.Context, arg GetTableRowSecurityParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, getTableRowSecurity, arg.SchemaName, arg.TableName)
	var row_security bool
	err := row.Scan(&row_security)
	return row_security, err
}

const getTypeDefinition = `-- name: GetTypeDefinition :one
SELECT COALESCE(pg_catalog.format_type(t.oid, NULL), '')::text AS definition
FROM pg_type t
JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE t.typname = $1::text
  AND n.nspname = $2::text
LIMIT 1
`

type GetTypeDefinitionParams struct {
	TypeName   string `json:"type_name"`
	SchemaName string `json:"schema_name"`
}

func (q *Queries) GetTypeDefinition(ctx context.Context, arg GetTypeDefinitionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getTypeDefinition, arg.TypeName, arg.SchemaName)
	var definition string
	err := row.Scan(&definition)
	return definition, err
}

const listColumnsForTable = `-- name: ListColumnsForTable :many
SELECT
  c.column_name::text AS column_name,
  c.data_type::text AS data_type,
  (c.is_nullable = 'YES') AS is_nullable,
  COALESCE(c.column_default, '')::text AS column_default,
  (c.is_generated = 'ALWAYS') AS is_generated,
  COALESCE(c.generation_expression, '')::text AS generation_expression,
  (c.is_identity = 'YES') AS is_identity,
  COALESCE(c.identity_generation, '')::text AS identity_generation,
  COALESCE(c.collation_name, '')::text AS collation_name,
  COALESCE(
    col_description(
      (quote_ident($1::text) || '.' || quote_ident($2::text))::regclass,
      c.ordinal_position
    ),
    ''
  )::text AS column_comment
FROM information_schema.columns c
WHERE c.table_schema = $1::text
  AND c.table_name = $2::text
ORDER BY c.ordinal_position
`

type ListColumnsForTableParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

type ListColumnsForTableRow struct {
	ColumnName           string `json:"column_name"`
	DataType             string `json:"data_type"`
	IsNullable           bool   `json:"is_nullable"`
	ColumnDefault        string `json:"column_default"`
	IsGenerated          bool   `json:"is_generated"`
	GenerationExpression string `json:"generation_expression"`
	IsIdentity           bool   `json:"is_identity"`
	IdentityGeneration   string `json:"identity_generation"`
	CollationName        string `json:"collation_name"`
	ColumnComment        string `json:"column_comment"`
}

func (q *Queries) ListColumnsForTable(ctx context.Context, arg ListColumnsForTableParams) ([]ListColumnsForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listColumnsForTable, arg.SchemaName, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListColumnsForTableRow
	for rows.Next() {
		var i ListColumnsForTableRow
		if err := rows.Scan(
			&i.ColumnName,
			&i.DataType,
			&i.IsNullable,
			&i.ColumnDefault,
			&i.IsGenerated,
			&i.GenerationExpression,
			&i.IsIdentity,
			&i.IdentityGeneration,
			&i.CollationName,
			&i.ColumnComment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConstraintsForTable = `-- name: ListConstraintsForTable :many
SELECT
  tc.constraint_name::text AS constraint_name,
  tc.constraint_type::text AS constraint_type,
  COALESCE(
    array_agg(DISTINCT kcu.column_name ORDER BY kcu.ordinal_position)
      FILTER (WHERE kcu.column_name IS NOT NULL),
    ARRAY[]::text[]
  )::text[] AS columns,
  COALESCE(MAX(ccu.table_name), '')::text AS ref_table,
  COALESCE(
    array_agg(DISTINCT ccu.column_name ORDER BY ccu.column_name)
      FILTER (WHERE ccu.column_name IS NOT NULL),
    ARRAY[]::text[]
  )::text[] AS ref_columns,
  COALESCE(MAX(rc.delete_rule), '')::text AS on_delete,
  COALESCE(MAX(rc.update_rule), '')::text AS on_update,
  COALESCE(bool_or(pgc.condeferrable), false)::boolean AS is_deferrable,
  COALESCE(bool_or(pgc.condeferred), false)::boolean AS initially_deferred,
  COALESCE(MAX(pg_get_constraintdef(pgc.oid)), '')::text AS check_expr
FROM information_schema.table_constraints tc
LEFT JOIN information_schema.key_column_usage kcu
  ON tc.constraint_name = kcu.constraint_name
  AND tc.table_schema = kcu.table_schema
  AND tc.table_name = kcu.table_name
LEFT JOIN information_schema.constraint_column_usage ccu
  ON tc.constraint_name = ccu.constraint_name
  AND tc.table_schema = ccu.constraint_schema
LEFT JOIN information_schema.referential_constraints rc
  ON tc.constraint_name = rc.constraint_name
  AND tc.table_schema = rc.constraint_schema
LEFT JOIN pg_constraint pgc
  ON pgc.conname = tc.constraint_name
  AND pgc.connamespace = (SELECT oid FROM pg_namespace WHERE nspname = tc.table_schema)
WHERE tc.table_schema = $1::text
  AND tc.table_name = $2::text
GROUP BY tc.constraint_name, tc.constraint_type
ORDER BY tc.constraint_name
`

type ListConstraintsForTableParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

type ListConstraintsForTableRow struct {
	ConstraintName    string   `json:"constraint_name"`
	ConstraintType    string   `json:"constraint_type"`
	Columns           []string `json:"columns"`
	RefTable          string   `json:"ref_table"`
	RefColumns        []string `json:"ref_columns"`
	OnDelete          string   `json:"on_delete"`
	OnUpdate          string   `json:"on_update"`
	IsDeferrable      bool     `json:"is_deferrable"`
	InitiallyDeferred bool     `json:"initially_deferred"`
	CheckExpr         string   `json:"check_expr"`
}

func (q *Queries) ListConstraintsForTable(ctx context.Context, arg ListConstraintsForTableParams) ([]ListConstraintsForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listConstraintsForTable, arg.SchemaName, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListConstraintsForTableRow
	for rows.Next() {
		var i ListConstraintsForTableRow
		if err := rows.Scan(
			&i.ConstraintName,
			&i.ConstraintType,
			pq.Array(&i.Columns),
			&i.RefTable,
			pq.Array(&i.RefColumns),
			&i.OnDelete,
			&i.OnUpdate,
			&i.IsDeferrable,
			&i.InitiallyDeferred,
			&i.CheckExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExtensions = `-- name: ListExtensions :many
SELECT
  e.extname::text AS name,
  e.extversion::text AS version,
  COALESCE(n.nspname, '')::text AS schema,
  COALESCE(d.description, '')::text AS comment,
  e.extrelocatable AS relocatable
FROM pg_extension e
LEFT JOIN pg_namespace n ON n.oid = e.extnamespace
LEFT JOIN pg_description d ON d.objoid = e.oid AND d.objsubid = 0
ORDER BY e.extname
`

type ListExtensionsRow struct {
	Name        string       `json:"name"`
	Version     string       `json:"version"`
	Schema      string       `json:"schema"`
	Comment     string       `json:"comment"`
	Relocatable sql.NullBool `json:"relocatable"`
}

func (q *Queries) ListExtensions(ctx context.Context) ([]ListExtensionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExtensionsRow
	for rows.Next() {
		var i ListExtensionsRow
		if err := rows.Scan(
			&i.Name,
			&i.Version,
			&i.Schema,
			&i.Comment,
			&i.Relocatable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFunctionsForSchema = `-- name: ListFunctionsForSchema :many
SELECT
  p.proname::text AS function_name,
  pg_get_function_identity_arguments(p.oid)::text AS signature,
  l.lanname::text AS language,
  pg_get_function_result(p.oid)::text AS return_type,
  pg_get_functiondef(p.oid)::text AS body,
  CASE p.provolatile
    WHEN 'i' THEN 'IMMUTABLE'
    WHEN 's' THEN 'STABLE'
    ELSE 'VOLATILE'
  END::text AS volatility,
  p.proisstrict AS is_strict,
  CASE p.prosecdef
    WHEN true THEN 'DEFINER'
    ELSE 'INVOKER'
  END::text AS security,
  COALESCE(obj_description(p.oid, 'pg_proc'), '')::text AS comment
FROM pg_proc p
JOIN pg_namespace n ON n.oid = p.pronamespace
JOIN pg_language l ON l.oid = p.prolang
WHERE n.nspname = $1::text
  AND p.prokind = 'f'
ORDER BY p.proname, p.oid
`

type ListFunctionsForSchemaRow struct {
	FunctionName string       `json:"function_name"`
	Signature    string       `json:"signature"`
	Language     string       `json:"language"`
	ReturnType   string       `json:"return_type"`
	Body         string       `json:"body"`
	Volatility   string       `json:"volatility"`
	IsStrict     sql.NullBool `json:"is_strict"`
	Security     string       `json:"security"`
	Comment      string       `json:"comment"`
}

func (q *Queries) ListFunctionsForSchema(ctx context.Context, schemaName string) ([]ListFunctionsForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listFunctionsForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFunctionsForSchemaRow
	for rows.Next() {
		var i ListFunctionsForSchemaRow
		if err := rows.Scan(
			&i.FunctionName,
			&i.Signature,
			&i.Language,
			&i.ReturnType,
			&i.Body,
			&i.Volatility,
			&i.IsStrict,
			&i.Security,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIndexesForTable = `-- name: ListIndexesForTable :many
SELECT
  ic.relname::text AS index_name,
  COALESCE(
    array_agg(a.attname ORDER BY array_position(i.indkey, a.attnum))
      FILTER (WHERE a.attname IS NOT NULL),
    ARRAY[]::text[]
  )::text[] AS columns,
  am.amname::text AS index_method,
  i.indisunique AS is_unique,
  i.indisprimary AS is_primary,
  COALESCE(pg_get_expr(i.indpred, i.indrelid), '')::text AS where_clause,
  COALESCE(pg_get_indexdef(i.indexrelid), '')::text AS definition
FROM pg_index i
JOIN pg_class c ON c.oid = i.indrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_class ic ON ic.oid = i.indexrelid
JOIN pg_am am ON am.oid = ic.relam
LEFT JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
WHERE n.nspname = $1::text
  AND c.relname = $2::text
GROUP BY ic.relname, am.amname, i.indisunique, i.indisprimary, i.indpred, i.indrelid, i.indexrelid
ORDER BY ic.relname
`

type ListIndexesForTableParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

type ListIndexesForTableRow struct {
	IndexName   string       `json:"index_name"`
	Columns     []string     `json:"columns"`
	IndexMethod string       `json:"index_method"`
	IsUnique    sql.NullBool `json:"is_unique"`
	IsPrimary   sql.NullBool `json:"is_primary"`
	WhereClause string       `json:"where_clause"`
	Definition  string       `json:"definition"`
}

func (q *Queries) ListIndexesForTable(ctx context.Context, arg ListIndexesForTableParams) ([]ListIndexesForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listIndexesForTable, arg.SchemaName, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIndexesForTableRow
	for rows.Next() {
		var i ListIndexesForTableRow
		if err := rows.Scan(
			&i.IndexName,
			pq.Array(&i.Columns),
			&i.IndexMethod,
			&i.IsUnique,
			&i.IsPrimary,
			&i.WhereClause,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterializedViewsForSchema = `-- name: ListMaterializedViewsForSchema :many
SELECT
  m.matviewname::text AS matview_name,
  COALESCE(m.definition, '')::text AS definition,
  m.ispopulated AS is_populated,
  COALESCE(
    obj_description((quote_ident($1::text) || '.' || quote_ident(m.matviewname))::regclass),
    ''
  )::text AS comment
FROM pg_matviews m
WHERE m.schemaname = $1::text
ORDER BY m.matviewname
`

type ListMaterializedViewsForSchemaRow struct {
	MatviewName string       `json:"matview_name"`
	Definition  string       `json:"definition"`
	IsPopulated sql.NullBool `json:"is_populated"`
	Comment     string       `json:"comment"`
}

func (q *Queries) ListMaterializedViewsForSchema(ctx context.Context, schemaName string) ([]ListMaterializedViewsForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listMaterializedViewsForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMaterializedViewsForSchemaRow
	for rows.Next() {
		var i ListMaterializedViewsForSchemaRow
		if err := rows.Scan(
			&i.MatviewName,
			&i.Definition,
			&i.IsPopulated,
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPoliciesForTable = `-- name: ListPoliciesForTable :many
SELECT
  pol.polname::text AS policy_name,
  CASE pol.polcmd
    WHEN 'r' THEN 'SELECT'
    WHEN 'a' THEN 'INSERT'
    WHEN 'w' THEN 'UPDATE'
    WHEN 'd' THEN 'DELETE'
    ELSE 'ALL'
  END::text AS command,
  pol.polpermissive AS permissive,
  COALESCE(
    array_agg(r.rolname ORDER BY r.rolname) FILTER (WHERE r.rolname IS NOT NULL),
    ARRAY[]::text[]
  )::text[] AS roles,
  COALESCE(pg_get_expr(pol.polqual, pol.polrelid), '')::text AS using_expr,
  COALESCE(pg_get_expr(pol.polwithcheck, pol.polrelid), '')::text AS with_check_expr
FROM pg_policy pol
JOIN pg_class c ON c.oid = pol.polrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
LEFT JOIN pg_roles r ON r.oid = ANY(pol.polroles)
WHERE n.nspname = $1::text
  AND c.relname = $2::text
GROUP BY pol.polname, pol.polcmd, pol.polpermissive, pol.polrelid, pol.polqual, pol.polwithcheck
ORDER BY pol.polname
`

type ListPoliciesForTableParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

type ListPoliciesForTableRow struct {
	PolicyName    string       `json:"policy_name"`
	Command       string       `json:"command"`
	Permissive    sql.NullBool `json:"permissive"`
	Roles         []string     `json:"roles"`
	UsingExpr     string       `json:"using_expr"`
	WithCheckExpr string       `json:"with_check_expr"`
}

func (q *Queries) ListPoliciesForTable(ctx context.Context, arg ListPoliciesForTableParams) ([]ListPoliciesForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listPoliciesForTable, arg.SchemaName, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPoliciesForTableRow
	for rows.Next() {
		var i ListPoliciesForTableRow
		if err := rows.Scan(
			&i.PolicyName,
			&i.Command,
			&i.Permissive,
			pq.Array(&i.Roles),
			&i.UsingExpr,
			&i.WithCheckExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSequencesForSchema = `-- name: ListSequencesForSchema :many
SELECT
  c.relname::text AS sequence_name,
  format_type(s.seqtypid, NULL)::text AS data_type,
  s.seqstart::bigint AS start_value,
  s.seqincrement::bigint AS increment,
  s.seqmin::bigint AS min_value,
  s.seqmax::bigint AS max_value,
  s.seqcache::bigint AS cache_size,
  s.seqcycle AS is_cycle,
  COALESCE(
    (SELECT attrelid::regclass::text || '.' || attname
     FROM pg_attribute
     WHERE attrelid = d.refobjid AND attnum = d.refobjsubid),
    ''
  )::text AS owned_by
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_sequence s ON s.seqrelid = c.oid
LEFT JOIN pg_depend d ON d.objid = c.oid AND d.deptype = 'a'
WHERE n.nspname = $1::text
  AND c.relkind = 'S'
ORDER BY c.relname
`

type ListSequencesForSchemaRow struct {
	SequenceName string       `json:"sequence_name"`
	DataType     string       `json:"data_type"`
	StartValue   int64        `json:"start_value"`
	Increment    int64        `json:"increment"`
	MinValue     int64        `json:"min_value"`
	MaxValue     int64        `json:"max_value"`
	CacheSize    int64        `json:"cache_size"`
	IsCycle      sql.NullBool `json:"is_cycle"`
	OwnedBy      string       `json:"owned_by"`
}

func (q *Queries) ListSequencesForSchema(ctx context.Context, schemaName string) ([]ListSequencesForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listSequencesForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSequencesForSchemaRow
	for rows.Next() {
		var i ListSequencesForSchemaRow
		if err := rows.Scan(
			&i.SequenceName,
			&i.DataType,
			&i.StartValue,
			&i.Increment,
			&i.MinValue,
			&i.MaxValue,
			&i.CacheSize,
			&i.IsCycle,
			&i.OwnedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureConstraints = `-- name: ListSignatureConstraints :many
SELECT
  n.nspname::text AS schema_name,
  c.relname::text AS table_name,
  con.conname::text AS constraint_name,
  pg_catalog.pg_get_constraintdef(con.oid, true)::text AS definition
FROM pg_catalog.pg_constraint con
JOIN pg_catalog.pg_class c ON c.oid = con.conrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
ORDER BY n.nspname, c.relname, con.conname
`

type ListSignatureConstraintsRow struct {
	SchemaName     string `json:"schema_name"`
	TableName      string `json:"table_name"`
	ConstraintName string `json:"constraint_name"`
	Definition     string `json:"definition"`
}

func (q *Queries) ListSignatureConstraints(ctx context.Context) ([]ListSignatureConstraintsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureConstraints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureConstraintsRow
	for rows.Next() {
		var i ListSignatureConstraintsRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.ConstraintName,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureExtensions = `-- name: ListSignatureExtensions :many
SELECT
  extname::text AS name,
  extversion::text AS version
FROM pg_catalog.pg_extension
ORDER BY extname
`

type ListSignatureExtensionsRow struct {
	Name    string `json:"name"`
	Version string `json:"version"`
}

func (q *Queries) ListSignatureExtensions(ctx context.Context) ([]ListSignatureExtensionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureExtensions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureExtensionsRow
	for rows.Next() {
		var i ListSignatureExtensionsRow
		if err := rows.Scan(&i.Name, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureFunctions = `-- name: ListSignatureFunctions :many
SELECT
  n.nspname::text AS schema_name,
  p.proname::text AS function_name,
  pg_catalog.pg_get_function_identity_arguments(p.oid)::text AS identity_arguments,
  pg_catalog.pg_get_functiondef(p.oid)::text AS definition
FROM pg_catalog.pg_proc p
JOIN pg_catalog.pg_namespace n ON n.oid = p.pronamespace
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
	AND p.prokind IN ('f', 'p', 'w')
ORDER BY n.nspname, p.proname, pg_catalog.pg_get_function_identity_arguments(p.oid), p.oid
`

type ListSignatureFunctionsRow struct {
	SchemaName        string `json:"schema_name"`
	FunctionName      string `json:"function_name"`
	IdentityArguments string `json:"identity_arguments"`
	Definition        string `json:"definition"`
}

func (q *Queries) ListSignatureFunctions(ctx context.Context) ([]ListSignatureFunctionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureFunctions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureFunctionsRow
	for rows.Next() {
		var i ListSignatureFunctionsRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.FunctionName,
			&i.IdentityArguments,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureIndexes = `-- name: ListSignatureIndexes :many
SELECT
  schemaname::text AS schema_name,
  tablename::text AS table_name,
  indexname::text AS index_name,
  indexdef::text AS definition
FROM pg_catalog.pg_indexes
WHERE schemaname NOT IN ('pg_catalog', 'information_schema')
  AND schemaname NOT LIKE 'pg_toast%'
  AND schemaname NOT LIKE 'pg_temp_%'
ORDER BY schemaname, tablename, indexname
`

type ListSignatureIndexesRow struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
	IndexName  string `json:"index_name"`
	Definition string `json:"definition"`
}

func (q *Queries) ListSignatureIndexes(ctx context.Context) ([]ListSignatureIndexesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureIndexes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureIndexesRow
	for rows.Next() {
		var i ListSignatureIndexesRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.IndexName,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignaturePolicies = `-- name: ListSignaturePolicies :many
SELECT
  n.nspname::text AS schema_name,
  c.relname::text AS table_name,
  p.polname::text AS policy_name,
  p.polcmd::text AS command,
  p.polpermissive AS permissive,
  COALESCE(pg_catalog.pg_get_expr(p.polqual, p.polrelid, true), '')::text AS using_expr,
  COALESCE(pg_catalog.pg_get_expr(p.polwithcheck, p.polrelid, true), '')::text AS check_expr
FROM pg_catalog.pg_policy p
JOIN pg_catalog.pg_class c ON c.oid = p.polrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
ORDER BY n.nspname, c.relname, p.polname
`

type ListSignaturePoliciesRow struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
	PolicyName string `json:"policy_name"`
	Command    string `json:"command"`
	Permissive bool   `json:"permissive"`
	UsingExpr  string `json:"using_expr"`
	CheckExpr  string `json:"check_expr"`
}

func (q *Queries) ListSignaturePolicies(ctx context.Context) ([]ListSignaturePoliciesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignaturePolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignaturePoliciesRow
	for rows.Next() {
		var i ListSignaturePoliciesRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.PolicyName,
			&i.Command,
			&i.Permissive,
			&i.UsingExpr,
			&i.CheckExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureTableColumns = `-- name: ListSignatureTableColumns :many
SELECT
  n.nspname::text AS schema_name,
  c.relname::text AS table_name,
  a.attnum::int AS attnum,
  a.attname::text AS column_name,
  pg_catalog.format_type(a.atttypid, a.atttypmod)::text AS data_type,
  a.attnotnull AS not_null,
  COALESCE(pg_catalog.pg_get_expr(ad.adbin, ad.adrelid), '')::text AS default_expr
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
JOIN pg_catalog.pg_attribute a ON a.attrelid = c.oid
LEFT JOIN pg_catalog.pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
WHERE c.relkind IN ('r', 'p')
  AND a.attnum > 0
  AND NOT a.attisdropped
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
ORDER BY n.nspname, c.relname, a.attnum
`

type ListSignatureTableColumnsRow struct {
	SchemaName  string `json:"schema_name"`
	TableName   string `json:"table_name"`
	Attnum      int32  `json:"attnum"`
	ColumnName  string `json:"column_name"`
	DataType    string `json:"data_type"`
	NotNull     bool   `json:"not_null"`
	DefaultExpr string `json:"default_expr"`
}

func (q *Queries) ListSignatureTableColumns(ctx context.Context) ([]ListSignatureTableColumnsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureTableColumns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureTableColumnsRow
	for rows.Next() {
		var i ListSignatureTableColumnsRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.Attnum,
			&i.ColumnName,
			&i.DataType,
			&i.NotNull,
			&i.DefaultExpr,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureTriggers = `-- name: ListSignatureTriggers :many
SELECT
  n.nspname::text AS schema_name,
  c.relname::text AS table_name,
  t.tgname::text AS trigger_name,
  pg_catalog.pg_get_triggerdef(t.oid, true)::text AS definition
FROM pg_catalog.pg_trigger t
JOIN pg_catalog.pg_class c ON c.oid = t.tgrelid
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE NOT t.tgisinternal
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
ORDER BY n.nspname, c.relname, t.tgname
`

type ListSignatureTriggersRow struct {
	SchemaName  string `json:"schema_name"`
	TableName   string `json:"table_name"`
	TriggerName string `json:"trigger_name"`
	Definition  string `json:"definition"`
}

func (q *Queries) ListSignatureTriggers(ctx context.Context) ([]ListSignatureTriggersRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureTriggers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureTriggersRow
	for rows.Next() {
		var i ListSignatureTriggersRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.TableName,
			&i.TriggerName,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSignatureViews = `-- name: ListSignatureViews :many
SELECT
  n.nspname::text AS schema_name,
  c.relname::text AS view_name,
  c.relkind::text AS rel_kind,
  pg_catalog.pg_get_viewdef(c.oid, true)::text AS definition
FROM pg_catalog.pg_class c
JOIN pg_catalog.pg_namespace n ON n.oid = c.relnamespace
WHERE c.relkind IN ('v', 'm')
  AND n.nspname NOT IN ('pg_catalog', 'information_schema')
  AND n.nspname NOT LIKE 'pg_toast%'
  AND n.nspname NOT LIKE 'pg_temp_%'
ORDER BY n.nspname, c.relname
`

type ListSignatureViewsRow struct {
	SchemaName string `json:"schema_name"`
	ViewName   string `json:"view_name"`
	RelKind    string `json:"rel_kind"`
	Definition string `json:"definition"`
}

func (q *Queries) ListSignatureViews(ctx context.Context) ([]ListSignatureViewsRow, error) {
	rows, err := q.db.QueryContext(ctx, listSignatureViews)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSignatureViewsRow
	for rows.Next() {
		var i ListSignatureViewsRow
		if err := rows.Scan(
			&i.SchemaName,
			&i.ViewName,
			&i.RelKind,
			&i.Definition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTablesForSchema = `-- name: ListTablesForSchema :many
SELECT
  c.relname::text AS table_name,
  COALESCE(obj_description(c.oid, 'pg_class'), '')::text AS table_comment
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = $1::text
  AND c.relkind IN ('r', 'p')
ORDER BY c.relname
`

type ListTablesForSchemaRow struct {
	TableName    string `json:"table_name"`
	TableComment string `json:"table_comment"`
}

func (q *Queries) ListTablesForSchema(ctx context.Context, schemaName string) ([]ListTablesForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listTablesForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTablesForSchemaRow
	for rows.Next() {
		var i ListTablesForSchemaRow
		if err := rows.Scan(&i.TableName, &i.TableComment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTriggersForTable = `-- name: ListTriggersForTable :many
SELECT
  t.tgname::text AS trigger_name,
  p.proname::text AS function_name,
  CASE t.tgtype & 66
    WHEN 2 THEN 'BEFORE'
    WHEN 64 THEN 'INSTEAD OF'
    ELSE 'AFTER'
  END::text AS timing,
  CASE t.tgtype & 1
    WHEN 1 THEN 'ROW'
    ELSE 'STATEMENT'
  END::text AS level,
  COALESCE(
    array_remove(ARRAY[
      CASE WHEN t.tgtype & 4 = 4 THEN 'INSERT' END,
      CASE WHEN t.tgtype & 8 = 8 THEN 'DELETE' END,
      CASE WHEN t.tgtype & 16 = 16 THEN 'UPDATE' END,
      CASE WHEN t.tgtype & 32 = 32 THEN 'TRUNCATE' END
    ], NULL),
    ARRAY[]::text[]
  )::text[] AS events,
  COALESCE(pg_get_expr(t.tgqual, t.tgrelid), '')::text AS condition,
  (t.tgenabled = 'O') AS is_enabled
FROM pg_trigger t
JOIN pg_class c ON c.oid = t.tgrelid
JOIN pg_namespace n ON n.oid = c.relnamespace
JOIN pg_proc p ON p.oid = t.tgfoid
WHERE n.nspname = $1::text
  AND c.relname = $2::text
  AND NOT t.tgisinternal
ORDER BY t.tgname
`

type ListTriggersForTableParams struct {
	SchemaName string `json:"schema_name"`
	TableName  string `json:"table_name"`
}

type ListTriggersForTableRow struct {
	TriggerName  string   `json:"trigger_name"`
	FunctionName string   `json:"function_name"`
	Timing       string   `json:"timing"`
	Level        string   `json:"level"`
	Events       []string `json:"events"`
	Condition    string   `json:"condition"`
	IsEnabled    bool     `json:"is_enabled"`
}

func (q *Queries) ListTriggersForTable(ctx context.Context, arg ListTriggersForTableParams) ([]ListTriggersForTableRow, error) {
	rows, err := q.db.QueryContext(ctx, listTriggersForTable, arg.SchemaName, arg.TableName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTriggersForTableRow
	for rows.Next() {
		var i ListTriggersForTableRow
		if err := rows.Scan(
			&i.TriggerName,
			&i.FunctionName,
			&i.Timing,
			&i.Level,
			pq.Array(&i.Events),
			&i.Condition,
			&i.IsEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypesForSchema = `-- name: ListTypesForSchema :many
SELECT
  t.typname::text AS type_name,
  CASE t.typtype
    WHEN 'e' THEN 'ENUM'
    WHEN 'c' THEN 'COMPOSITE'
    WHEN 'd' THEN 'DOMAIN'
    WHEN 'r' THEN 'RANGE'
    ELSE 'OTHER'
  END::text AS type_kind,
  COALESCE(
    (SELECT array_agg(enumlabel ORDER BY enumsortorder)
     FROM pg_enum
     WHERE enumtypid = t.oid),
    ARRAY[]::text[]
  )::text[] AS enum_elements,
  COALESCE(obj_description(t.oid, 'pg_type'), '')::text AS comment
FROM pg_type t
JOIN pg_namespace n ON n.oid = t.typnamespace
WHERE n.nspname = $1::text
  AND t.typtype IN ('e', 'c', 'd', 'r')
ORDER BY t.typname
`

type ListTypesForSchemaRow struct {
	TypeName     string   `json:"type_name"`
	TypeKind     string   `json:"type_kind"`
	EnumElements []string `json:"enum_elements"`
	Comment      string   `json:"comment"`
}

func (q *Queries) ListTypesForSchema(ctx context.Context, schemaName string) ([]ListTypesForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listTypesForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTypesForSchemaRow
	for rows.Next() {
		var i ListTypesForSchemaRow
		if err := rows.Scan(
			&i.TypeName,
			&i.TypeKind,
			pq.Array(&i.EnumElements),
			&i.Comment,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserSchemas = `-- name: ListUserSchemas :many
SELECT schema_name::text AS schema_name
FROM information_schema.schemata
WHERE schema_name NOT IN ('information_schema', 'pg_catalog', 'pg_toast')
  AND schema_name NOT LIKE 'pg_temp_%'
  AND schema_name NOT LIKE 'pg_toast_%'
ORDER BY schema_name
`

func (q *Queries) ListUserSchemas(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listUserSchemas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var schema_name string
		if err := rows.Scan(&schema_name); err != nil {
			return nil, err
		}
		items = append(items, schema_name)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listViewsForSchema = `-- name: ListViewsForSchema :many
SELECT
  v.table_name::text AS view_name,
  COALESCE(v.view_definition, '')::text AS definition,
  COALESCE(
    obj_description((quote_ident($1::text) || '.' || quote_ident(v.table_name))::regclass),
    ''
  )::text AS comment
FROM information_schema.views v
WHERE v.table_schema = $1::text
ORDER BY v.table_name
`

type ListViewsForSchemaRow struct {
	ViewName   string `json:"view_name"`
	Definition string `json:"definition"`
	Comment    string `json:"comment"`
}

func (q *Queries) ListViewsForSchema(ctx context.Context, schemaName string) ([]ListViewsForSchemaRow, error) {
	rows, err := q.db.QueryContext(ctx, listViewsForSchema, schemaName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListViewsForSchemaRow
	for rows.Next() {
		var i ListViewsForSchemaRow
		if err := rows.Scan(&i.ViewName, &i.Definition, &i.Comment); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
