-- Data Operations - Generated by pgsquash
-- IMPORTANT: These are non-idempotent operations (INSERT/UPDATE/DELETE)
-- Run these AFTER the baseline schema is applied
-- Safety level: standard
-- Generated at: 2025-11-06T19:38:15+02:00

-- Total data operations: 3 (sorted by dependencies)

-- UPDATE on public.memory_cards
update public.memory_cards 
set search_vector = 
    setweight(to_tsvector('english', coalesce(trigger_phrase, '')), 'A') ||
    setweight(to_tsvector('english', coalesce(content, '')), 'B') ||
    setweight(to_tsvector('english', coalesce(array_to_string(tags, ' '), '')), 'C')
where search_vector is null;

-- INSERT on public.recovery_activities
insert into public.recovery_activities (name, type, description, duration_minutes, energy_restoration_rate, difficulty_level, requirements, tags, icon, is_default) values
('5-Minute Breathing', 'mental', 'Simple breathing exercises to reduce stress and restore calm.', 5, 2, 'minimal', '{}', '{quick, stress-relief, anywhere}', 'wind', true),
('Nature Soundscape', 'sensory', 'Listen to calming nature sounds for sensory regulation.', 15, 3, 'minimal', '{headphones}', '{sensory, calming, audio}', 'tree-pine', true),
('Gentle Stretching', 'physical', 'Light stretching to release physical tension.', 10, 4, 'low', '{comfortable space}', '{movement, tension-relief, physical}', 'sparkles', true),
('Mindful Tea Time', 'restorative', 'Mindful tea preparation and consumption for deep relaxation.', 20, 5, 'low', '{tea, quiet space}', '{mindfulness, ritual, comfort}', 'coffee', true),
('Creative Doodling', 'creative', 'Free-form creative expression to process emotions.', 25, 4, 'low', '{paper, pen/pencils}', '{creative, processing, expression}', 'star', true),
('Guided Meditation', 'mental', 'Structured meditation for deep mental restoration.', 15, 6, 'medium', '{headphones, quiet space}', '{meditation, deep-recovery, mental}', 'moon', true),
('Sensory Bath/Shower', 'sensory', 'Sensory-focused bathing for comprehensive restoration.', 30, 7, 'medium', '{bathroom, preferred temperature}', '{sensory, water, deep-recovery}', 'waves', true);

-- INSERT on public.system_settings
insert into public.system_settings (category, setting_key, setting_value, description, is_public) values
('rate_limit', 'requests_per_minute', '60', 'Maximum API requests per minute per user', false),
('rate_limit', 'tokens_per_minute', '10000', 'Maximum tokens per minute per user', false),
('security', 'max_failed_logins', '5', 'Maximum failed login attempts before lockout', false),
('security', 'session_timeout_hours', '24', 'User session timeout in hours', false),
('crisis', 'detection_sensitivity', '"medium"', 'Crisis detection sensitivity level', false),
('crisis', 'auto_intervention', 'true', 'Enable automatic crisis interventions', false),
('monitoring', 'enable_metrics', 'true', 'Enable system metrics collection', false),
('monitoring', 'log_level', '"info"', 'System logging level', false),
('general', 'maintenance_mode', 'false', 'System maintenance mode flag', true),
('general', 'feature_flags', '{"recovery_system": true, "crisis_detection": true, "social_battery": true}', 'Feature availability flags', true)
on conflict (category, setting_key) do nothing;

