-- Create table with IDENTITY columns (PostgreSQL 10+)
CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Create table with GENERATED columns (PostgreSQL 12+)
CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    discount_price DECIMAL(10,2) GENERATED ALWAYS AS (price * 0.9) STORED,
    final_price DECIMAL(10,2) GENERATED ALWAYS AS (
        CASE
            WHEN price > 100 THEN price * 0.85
            ELSE price * 0.95
        END
    ) STORED,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Add indexes on generated columns
CREATE INDEX idx_products_discount_price ON products (discount_price);
CREATE INDEX idx_products_final_price ON products (final_price);
