-- Add table with SERIAL vs IDENTITY comparison
CREATE TABLE orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users(id),
    order_number VARCHAR(20) GENERATED ALWAYS AS ('ORD-' || id::text) STORED,
    total_amount DECIMAL(10,2) NOT NULL,
    tax_amount DECIMAL(10,2) GENERATED ALWAYS AS (total_amount * 0.08) STORED,
    final_amount DECIMAL(10,2) GENERATED ALWAYS AS (total_amount + tax_amount) STORED,
    created_at TIMESTAMP DEFAULT NOW()
);

-- Add more complex generated column
ALTER TABLE products ADD COLUMN search_vector TSVECTOR GENERATED ALWAYS AS (
    to_tsvector('english', name || ' ' || COALESCE(description, ''))
) STORED;

-- Create index on generated column
CREATE INDEX idx_products_search ON products USING GIN (search_vector);
