-- Add table with virtual generated columns (PostgreSQL 15+)
CREATE TABLE inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    base_price DECIMAL(10,2) NOT NULL,
    discount_percent DECIMAL(5,2) DEFAULT 0 CHECK (discount_percent >= 0 AND discount_percent <= 100),
    final_price DECIMAL(10,2) GENERATED ALWAYS AS (base_price * (1 - discount_percent/100)) STORED,
    price_category VARCHAR(20) GENERATED ALWAYS AS (
        CASE
            WHEN base_price < 50 THEN 'budget'
            WHEN base_price < 200 THEN 'standard'
            ELSE 'premium'
        END
    ) STORED,
    updated_at TIMESTAMP DEFAULT NOW()
);

-- Test SERIAL to IDENTITY conversion scenarios
CREATE TABLE legacy_table (
    id SERIAL PRIMARY KEY,
    data TEXT
);

-- Add constraints involving generated columns
ALTER TABLE orders ADD CONSTRAINT check_positive_amount
    CHECK (final_amount > 0);

-- Complex generated column with JSON
ALTER TABLE users ADD COLUMN settings JSONB;
ALTER TABLE users ADD COLUMN theme VARCHAR(50) GENERATED ALWAYS AS (
    COALESCE(settings->>'theme', 'default')
) STORED;
