-- Generated by pgsquash with modern PostgreSQL patterns
-- Safety level: standard
-- Generated at: 2025-11-07T10:45:20+02:00


-- === AUTH COMPATIBILITY LAYER ===
-- Auto-injected stubs for Supabase/Clerk authentication

-- Clerk Authentication Compatibility Layer
CREATE SCHEMA IF NOT EXISTS auth;

-- Create common Supabase/Clerk roles (used in RLS policies)
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN;
  END IF;
END
$$;

-- Mock Clerk auth.jwt() function
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  -- Return a mock Clerk JWT payload for validation purposes
  RETURN jsonb_build_object(
    'o', jsonb_build_object(
      'id', 'org_mock_organization_id',
      'role', 'admin',
      'name', 'Mock Organization',
      'slug', 'mock-org'
    ),
    'sub', 'user_mock_user_id',
    'email', 'mock@clerk.dev',
    'email_verified', true,
    'iat', extract(epoch from now()),
    'exp', extract(epoch from now()) + 3600,
    'iss', 'https://mock-clerk.clerk.accounts.dev'
  );
END;
$$;

-- Mock current_user_id helper (common in Clerk setups)
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION current_user_id() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt() ->> 'sub')::text;
END;
$$;

-- Mock organization helpers
-- NOTE: No volatility markers - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION current_organization_id() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt()->'o'->>'id')::text;
END;
$$;

CREATE OR REPLACE FUNCTION current_organization_role() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt()->'o'->>'role')::text;
END;
$$;

CREATE OR REPLACE FUNCTION current_organization_name() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt()->'o'->>'name')::text;
END;
$$;

-- Create Supabase Realtime publication if it doesn't exist (often used with Clerk)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END
$$;


-- === POSTGRESQL ROLES ===
-- Roles must be created before policies that reference them

DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN;
  END IF;
END
$$;


-- === EXTENSIONS OBJECTS ===

create extension if not exists "uuid-ossp";

create extension if not exists "pg_trgm";

create extension if not exists "pgcrypto";


-- === FOUNDATION OBJECTS ===

create table if not exists public.usage_analytics (
    id uuid primary key default gen_random_uuid(),
    date date not null,
    primary_support text,
    energy_level text,
    ui_state text,
    total_conversations integer default 0,
    total_tokens integer default 0,
    total_cost_usd decimal default 0.00,
    tools_used jsonb default '[]'::jsonb,
    average_response_time decimal,
    error_count integer default 0,
    successful_interactions integer default 0,
    memory_cards_created integer default 0,
    crisis_interventions integer default 0,
    helpful_responses integer default 0,
    created_at timestamp with time zone default now(),
    unique(date, primary_support, energy_level, ui_state)
);

create table if not exists public.user_profiles (
    id uuid primary key default gen_random_uuid(),
    clerk_user_id text unique not null,
    email text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    primary_support text check (primary_support in ('adhd', 'autism', 'dyslexia', 'executiveDysfunction', 'workingMemory', 'sensoryProcessing')),
    communication_style text default 'balanced' check (communication_style in ('literal', 'balanced', 'warm')),
    preferred_response_length text default 'standard' check (preferred_response_length in ('tldr', 'standard', 'detailed')),
    timing_preference text default 'gentle-awareness' check (timing_preference in ('no-pressure', 'gentle-awareness', 'structured')),
    daily_cost_budget decimal default 10.00,
    daily_token_limit integer default 5000,
    crisis_support_enabled boolean default true,
    memory_sharing_enabled boolean default false,
    analytics_enabled boolean default true,
    success_patterns jsonb default '[]'::jsonb,
    stress_triggers jsonb default '[]'::jsonb,
    recovery_strategies jsonb default '[]'::jsonb,
    energy_patterns jsonb default '{}'::jsonb,
    timezone text default 'UTC',
    language text default 'en',
    accessibility_preferences jsonb default '{}'::jsonb,
    energy_level text DEFAULT 'medium' CHECK (energy_level IN ('low', 'medium', 'high')),
    ui_state text DEFAULT 'explore' CHECK (ui_state IN ('calm', 'focus', 'explore', 'crisis', 'flow', 'social', 'planning', 'recovery')),
    task_breakdown_enabled boolean DEFAULT true,
    progress_celebration_enabled boolean DEFAULT true,
    current_stress_level integer DEFAULT 3 CHECK (current_stress_level >= 1 AND current_stress_level <= 10),
    current_social_battery integer DEFAULT 8 CHECK (current_social_battery >= 0 AND current_social_battery <= 10),
    burnout_risk_score integer DEFAULT 0 CHECK (burnout_risk_score >= 0 AND burnout_risk_score <= 100),
    crisis_mode_active boolean DEFAULT false,
    last_crisis_event timestamp with time zone,
    onboarding_completed boolean DEFAULT false,
    onboarding_responses jsonb DEFAULT '{}'::jsonb,
    first_name text,
    last_name text,
    current_org_id TEXT,
    current_org_role TEXT,
    current_org_name TEXT
);

create table if not exists public.admin_action_logs (
    id uuid primary key default gen_random_uuid(),
    admin_user_id text not null, -- Clerk admin user ID
    admin_email text,
    action_type text not null check (action_type in (
        'user_activate', 'user_deactivate', 'user_exit_crisis',
        'provider_create', 'provider_update', 'provider_delete', 'provider_test',
        'settings_update', 'system_restart', 'data_export',
        'crisis_intervention_manual', 'emergency_broadcast'
    )),
    resource_type text not null check (resource_type in ('user', 'provider', 'setting', 'system')),
    resource_id text, -- ID of affected resource
    action_details jsonb default '{}'::jsonb,
    previous_state jsonb,
    new_state jsonb,
    success boolean not null,
    error_message text,
    ip_address inet,
    user_agent text,
    timestamp timestamp with time zone default now()
);

create table if not exists public.system_settings (
    id uuid primary key default gen_random_uuid(),
    category text not null check (category in ('rate_limit', 'security', 'crisis', 'monitoring', 'general')),
    setting_key text not null,
    setting_value jsonb not null,
    description text,
    is_public boolean default false, -- Can be read by non-admin users
    requires_restart boolean default false,
    version integer default 1,
    previous_value jsonb,
    created_by text, -- Admin user who created/updated
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique(category, setting_key)
);

create table if not exists public.ai_providers (
    id uuid primary key default gen_random_uuid(),
    provider_id text unique not null,
    name text not null,
    provider_type text not null check (provider_type in ('openai', 'anthropic', 'azure', 'google', 'custom')),
    enabled boolean default true,
    priority integer default 5 check (priority >= 0 and priority <= 10),
    model_name text,
    api_key_encrypted text,
    endpoint_url text,
    temperature decimal default 0.7 check (temperature >= 0 and temperature <= 2),
    max_tokens integer default 4000,
    requests_per_minute integer,
    tokens_per_minute integer,
    last_health_check timestamp with time zone,
    health_status text default 'unknown' check (health_status in ('healthy', 'unhealthy', 'unknown')),
    average_latency decimal,
    error_rate decimal default 0,
    total_requests integer default 0,
    total_tokens integer default 0,
    total_cost_usd decimal default 0.00,
    last_used timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.system_monitoring (
    id uuid primary key default gen_random_uuid(),
    timestamp timestamp with time zone default now(),
    cpu_usage_percent decimal,
    memory_usage_percent decimal,
    disk_usage_percent decimal,
    database_connections_active integer,
    database_connections_max integer,
    avg_response_time_ms decimal,
    error_rate_percent decimal,
    requests_per_minute integer,
    active_users integer,
    active_crisis_sessions integer default 0,
    high_risk_users integer default 0,
    crisis_interventions_today integer default 0,
    provider_health jsonb default '{}'::jsonb, -- Status of each provider
    custom_metrics jsonb default '{}'::jsonb
);

create table if not exists public.system_analytics (
    id uuid primary key default gen_random_uuid(),
    date date not null,
    period_type text not null check (period_type in ('hour', 'day', 'week', 'month')),
    total_conversations integer default 0,
    active_users integer default 0,
    new_users integer default 0,
    returning_users integer default 0,
    crisis_interventions integer default 0,
    crisis_resolutions integer default 0,
    auto_detection_rate decimal default 0,
    intervention_success_rate decimal default 0,
    avg_response_time_ms decimal default 0,
    uptime_percentage decimal default 100,
    error_count integer default 0,
    provider_usage jsonb default '{}'::jsonb,
    provider_costs jsonb default '{}'::jsonb,
    recovery_sessions_started integer default 0,
    recovery_sessions_completed integer default 0,
    avg_recovery_effectiveness decimal default 0,
    created_at timestamp with time zone default now(),
    unique(date, period_type)
);

create table if not exists public.recovery_activities (
    id uuid primary key default gen_random_uuid(),
    name text not null,
    type text not null check (type in ('sensory', 'physical', 'mental', 'creative', 'restorative')),
    description text,
    duration_minutes integer not null,
    energy_restoration_rate integer not null check (energy_restoration_rate >= 1 and energy_restoration_rate <= 10),
    difficulty_level text not null check (difficulty_level in ('minimal', 'low', 'medium')),
    requirements text[] default '{}',
    tags text[] default '{}',
    icon text, -- Icon identifier for UI
    is_default boolean default false,
    is_active boolean default true,
    created_at timestamp with time zone default now()
);

create table if not exists public.crisis_baselines (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade unique,
    avg_clicks_per_minute decimal default 5.0,
    avg_response_length integer default 25,
    avg_error_rate decimal default 0.05,
    avg_task_switches integer default 2,
    typical_response_time_ms integer default 3000,
    avg_energy_level decimal default 7.0,
    avg_stress_level decimal default 3.0,
    avg_cognitive_load decimal default 4.0,
    avg_social_battery decimal default 8.0,
    avg_session_duration_minutes integer default 45,
    preferred_working_hours integer[] default '{9,10,11,12,13,14,15,16,17}',
    sample_size integer default 0,
    last_calculated timestamp with time zone default now(),
    confidence_score decimal default 0.5,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.crisis_events (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    severity_level text not null check (severity_level in ('mild', 'moderate', 'severe', 'critical')),
    confidence_score decimal not null check (confidence_score >= 0 and confidence_score <= 100),
    escalation_risk decimal not null check (escalation_risk >= 0 and escalation_risk <= 100),
    primary_triggers text[] default '{}',
    detected_indicators jsonb default '{}'::jsonb, -- All detected crisis indicators
    recommended_interventions text[] default '{}',
    time_to_intervention_minutes integer,
    intervention_taken text,
    intervention_successful boolean,
    detection_timestamp timestamp with time zone default now(),
    intervention_timestamp timestamp with time zone,
    resolution_timestamp timestamp with time zone,
    user_feedback text,
    follow_up_needed boolean default false,
    follow_up_completed boolean default false,
    detection_method text default 'automatic',
    false_positive boolean default false,
    created_at timestamp with time zone default now()
);

create table if not exists public.planning_preferences (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade unique,
    max_tasks_per_day integer default 8,
    preferred_planning_time text default 'morning',
    use_time_blocking boolean default false,
    enable_energy_tracking boolean default true,
    executive_function_level integer default 5 check (executive_function_level >= 1 and executive_function_level <= 10),
    auto_breakdown_threshold integer default 60, -- minutes
    hyperfocus_mode boolean default false,
    transition_time integer default 5, -- minutes between tasks
    cognitive_load_warnings boolean default true,
    pomodoro_enabled boolean default false,
    pomodoro_work_duration integer default 25,
    pomodoro_break_duration integer default 5,
    deadline_warnings boolean default true,
    energy_budget_alerts boolean default true,
    daily_planning_reminder boolean default true,
    daily_planning_time time default '09:00',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.energy_patterns (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    energy_level integer not null check (energy_level >= 1 and energy_level <= 10),
    stress_level integer not null check (stress_level >= 1 and stress_level <= 10),
    cognitive_load integer not null check (cognitive_load >= 1 and cognitive_load <= 10),
    social_battery integer not null check (social_battery >= 1 and social_battery <= 10),
    activity_type text not null,
    ui_state text,
    time_of_day integer check (time_of_day >= 0 and time_of_day <= 23),
    day_of_week integer check (day_of_week >= 0 and day_of_week <= 6),
    sleep_quality integer check (sleep_quality >= 1 and sleep_quality <= 10),
    physical_comfort integer check (physical_comfort >= 1 and physical_comfort <= 10),
    timestamp timestamp with time zone default now()
);

create table if not exists public.behavioral_patterns (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    interaction_type text not null check (interaction_type in ('click', 'input', 'scroll', 'focus', 'blur', 'keypress', 'error')),
    timestamp timestamp with time zone default now(),
    duration_ms integer, -- Duration of interaction if applicable
    intensity decimal, -- Intensity/pressure if available
    metadata jsonb default '{}'::jsonb, -- Additional context data
    session_id text not null,
    created_at timestamp with time zone default now()
);

create table if not exists public.planning_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    focus_area text not null,
    start_time timestamp with time zone not null default now(),
    end_time timestamp with time zone,
    tasks_planned integer default 0,
    tasks_completed integer default 0,
    energy_used integer default 0,
    quality text check (quality in ('poor', 'good', 'excellent')),
    notes text,
    achievements jsonb default '[]'::jsonb,
    lessons_learned jsonb default '[]'::jsonb,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.task_templates (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    name text not null,
    title_template text not null,
    description_template text,
    category text not null,
    default_priority text default 'medium',
    default_energy_cost integer default 3,
    default_estimated_time integer default 30,
    default_breakdown_level integer default 3,
    default_hyperfocus_warning boolean default false,
    default_transition_support boolean default false,
    default_sensory_considerations text[] default '{}',
    times_used integer default 0,
    last_used timestamp with time zone,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique(user_id, name)
);

create table if not exists public.crisis_support_logs (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    crisis_type text check (crisis_type in ('overwhelm', 'anxiety', 'meltdown', 'shutdown', 'general')),
    severity text check (severity in ('mild', 'moderate', 'severe')),
    trigger_context text,
    strategies_provided jsonb default '[]'::jsonb,
    resources_offered jsonb default '[]'::jsonb,
    user_feedback_immediate text,
    follow_up_needed boolean default false,
    professional_referral_suggested boolean default false,
    emergency_resources_provided boolean default false,
    crisis_started timestamp with time zone default now(),
    crisis_resolved timestamp with time zone,
    follow_up_date timestamp with time zone,
    anonymized boolean default false
);

create table if not exists public.memory_cards (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    trigger_phrase text not null,
    content text not null,
    context_info text,
    category text not null check (category in ('personal', 'work', 'health', 'projects', 'communications', 'learning', 'coping', 'achievements')),
    importance text default 'medium' check (importance in ('low', 'medium', 'high', 'critical')),
    cognitive_type text default 'fact' check (cognitive_type in ('fact', 'process', 'template', 'reminder', 'accomplishment', 'strategy')),
    energy_level_created text check (energy_level_created in ('low', 'medium', 'high', 'crisis')),
    ui_state_created text,
    accessibility_notes text,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(), -- CONSOLIDATED FROM MIGRATION 13
    last_accessed timestamp with time zone default now(),
    access_count integer default 0,
    relevance_score decimal default 1.0,
    surfacing_keywords text[] default '{}',
    surfacing_contexts text[] default '{}',
    surfacing_energy_states text[] default '{}',
    surfacing_ui_states text[] default '{}',
    daily_reminder boolean default false,
    specific_times time[],
    day_of_week integer[], -- 0-6 (Sunday-Saturday)
    related_card_ids uuid[] default '{}',
    tags text[] default '{}',
    search_vector tsvector
);

create table if not exists public.social_interactions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    interaction_type text not null check (interaction_type in ('meeting', 'chat', 'call', 'email', 'social_media', 'group', 'presentation', 'networking', 'other')),
    duration_minutes integer,
    energy_cost integer check (energy_cost >= 1 and energy_cost <= 10),
    energy_gained integer check (energy_gained >= 0 and energy_gained <= 10),
    context text, -- Optional description
    people_count integer default 1,
    was_planned boolean default false,
    started_at timestamp with time zone default now(),
    ended_at timestamp with time zone,
    created_at timestamp with time zone default now()
);

create table if not exists public.user_activity_snapshots (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    snapshot_date timestamp with time zone default now(),
    total_conversations integer default 0,
    conversations_last_7_days integer default 0,
    conversations_last_30_days integer default 0,
    last_active timestamp with time zone,
    current_energy_level integer,
    current_stress_level integer,
    in_crisis_mode boolean default false,
    crisis_events_count integer default 0,
    recovery_sessions_count integer default 0,
    avg_recovery_effectiveness decimal default 0,
    memory_cards_count integer default 0,
    memory_cards_accessed_last_week integer default 0,
    is_active boolean default true,
    requires_admin_attention boolean default false,
    attention_reason text,
    data_retention_expires timestamp with time zone
);

create table if not exists public.tasks (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    title text not null,
    description text,
    priority text not null check (priority in ('low', 'medium', 'high', 'urgent')),
    energy_cost integer not null check (energy_cost >= 1 and energy_cost <= 10),
    estimated_time integer not null, -- in minutes
    actual_time integer, -- in minutes, filled when completed
    completed boolean default false,
    category text not null,
    deadline timestamp with time zone,
    breakdown_level integer default 3 check (breakdown_level >= 0 and breakdown_level <= 8),
    cognitive_load integer not null check (cognitive_load >= 1 and cognitive_load <= 10),
    sequencing boolean default true,
    timing_support boolean default true,
    hyperfocus_warning boolean default false,
    transition_support boolean default false,
    sensory_considerations text[] default '{}',
    dopamine_boosts text[] default '{}',
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    completed_at timestamp with time zone
);

create table if not exists public.conversations (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    conversation_id text not null, -- Client-generated conversation session ID
    user_message text not null,
    ai_response text not null,
    response_metadata jsonb default '{}'::jsonb, -- Tools used, tokens, etc.
    ui_state text,
    energy_level text,
    cognitive_load text,
    timestamp timestamp with time zone default now(),
    updated_at timestamp with time zone default now(), -- CONSOLIDATED FROM MIGRATION 13
    user_feedback integer check (user_feedback in (-1, 0, 1)), -- thumbs down, neutral, thumbs up
    was_helpful boolean,
    follow_up_needed boolean default false,
    extracted_facts jsonb default '[]'::jsonb,
    extracted_learnings jsonb default '[]'::jsonb,
    extracted_preferences jsonb default '[]'::jsonb,
    extracted_strategies jsonb default '[]'::jsonb,
    archived boolean default false,
    archive_date timestamp with time zone
);

create table if not exists public.recovery_preferences (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade unique,
    preferred_activity_types text[] default '{}',
    max_session_duration_minutes integer default 60,
    adaptive_scheduling boolean default true,
    gentle_reminders boolean default true,
    progress_tracking boolean default true,
    sensory_regulation boolean default true,
    environmental_controls jsonb default '{
        "lighting": "normal",
        "soundscape": "silent", 
        "temperature": "neutral",
        "aromatherapy": false
    }'::jsonb,
    emergency_break_triggers jsonb default '{
        "stressThreshold": 8,
        "energyThreshold": 20,
        "burnoutRiskThreshold": 70
    }'::jsonb,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.task_categories (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    name text not null,
    color text default '#3B82F6',
    icon text default 'folder',
    default_energy_cost integer default 3,
    default_time_estimate integer default 30,
    auto_breakdown boolean default false,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    unique(user_id, name)
);

create table if not exists public.recovery_plans (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    name text not null,
    description text,
    target_recovery_time_minutes integer not null,
    activity_ids uuid[] default '{}',
    break_intervals_minutes integer default 5,
    adaptive_difficulty boolean default true,
    environmental_needs text[] default '{}',
    emergency_protocols text[] default '{}',
    times_used integer default 0,
    effectiveness_rating decimal default 0,
    last_used timestamp with time zone,
    is_active boolean default true,
    is_default boolean default false,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now()
);

create table if not exists public.recovery_sessions (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    activity_id uuid references public.recovery_activities(id),
    start_time timestamp with time zone default now(),
    end_time timestamp with time zone,
    planned_duration_minutes integer not null,
    actual_duration_minutes integer,
    energy_before integer check (energy_before >= 1 and energy_before <= 10),
    stress_before integer check (stress_before >= 1 and stress_before <= 10),
    energy_after integer check (energy_after >= 1 and energy_after <= 10),
    stress_after integer check (stress_after >= 1 and stress_after <= 10),
    quality text check (quality in ('poor', 'good', 'excellent')),
    completion_rate integer default 100 check (completion_rate >= 0 and completion_rate <= 100),
    interruptions integer default 0,
    notes text,
    environmental_settings jsonb default '{}'::jsonb, -- lighting, sound, etc.
    was_scheduled boolean default false,
    was_emergency boolean default false,
    created_at timestamp with time zone default now()
);

create table if not exists public.subtasks (
    id uuid primary key default gen_random_uuid(),
    task_id uuid references public.tasks(id) on delete cascade,
    title text not null,
    completed boolean default false,
    estimated_time integer not null, -- in minutes
    order_position integer not null,
    created_at timestamp with time zone default now(),
    updated_at timestamp with time zone default now(),
    completed_at timestamp with time zone
);

create table if not exists public.social_battery (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.user_profiles(id) on delete cascade,
    current_level integer not null check (current_level >= 0 and current_level <= 100),
    max_capacity integer not null default 100 check (max_capacity >= 1 and max_capacity <= 100),
    drain_rate decimal default 1.0,
    recharge_rate decimal default 2.0,
    last_interaction_id uuid references public.social_interactions(id),
    last_recovery_session_id uuid references public.recovery_sessions(id),
    timestamp timestamp with time zone default now(),
    unique(user_id, timestamp)
);


-- === FUNCTIONS OBJECTS ===

CREATE OR REPLACE FUNCTION current_clerk_org_id()
RETURNS TEXT AS $$
  SELECT (auth.jwt()->'o'->>'id')::TEXT;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION check_jwt_v2_compatibility()
RETURNS TABLE(
  component TEXT,
  jwt_v2_support BOOLEAN, 
  status TEXT
) AS $$
BEGIN
  RETURN QUERY
  SELECT 
    'RLS Policies'::TEXT as component,
    EXISTS(
      SELECT 1 FROM pg_policies 
      WHERE definition ~ 'validate_jwt_version\(\)' OR 
            definition ~ 'current_clerk_user_id\(\)' OR
            definition ~ 'current_clerk_org_'
    ) as jwt_v2_support,
    CASE 
      WHEN EXISTS(SELECT 1 FROM pg_policies WHERE definition ~ 'auth\.jwt\(\)->>')
           AND EXISTS(SELECT 1 FROM pg_policies WHERE definition ~ 'validate_jwt_version\(\)')
      THEN 'JWT v2 READY'
      ELSE 'NEEDS JWT v2 UPGRADE'
    END as status;
END $$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.get_user_profile_data(clerk_id TEXT)
RETURNS TABLE (
    id UUID,
    communication_style TEXT,
    preferred_response_length TEXT,
    timing_preference TEXT,
    primary_support TEXT,
    daily_cost_budget DECIMAL,
    daily_token_limit INTEGER,
    accessibility_preferences JSONB,
    energy_patterns JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    PERFORM set_config('app.current_clerk_user_id', clerk_id, true);
    RETURN QUERY
    SELECT 
        up.id,
        up.communication_style,
        up.preferred_response_length,
        up.timing_preference,
        up.primary_support,
        up.daily_cost_budget,
        up.daily_token_limit,
        up.accessibility_preferences,
        up.energy_patterns
    FROM public.user_profiles up
    WHERE up.clerk_user_id = clerk_id;
END;
$$;

create or replace function public.calculate_crisis_confidence(user_uuid uuid, time_window_minutes integer default 30)
returns jsonb
language plpgsql
security definer
as $$
declare
    baseline_data record;
    recent_patterns record;
    confidence_score decimal := 0;
    indicators jsonb := '{}';
begin
    select * into baseline_data from public.crisis_baselines where user_id = user_uuid;
    if baseline_data is null then
        return jsonb_build_object('confidence', 0, 'message', 'No baseline data available');
    end if;
    select 
        count(*) as total_interactions,
        count(case when interaction_type = 'click' then 1 end) as clicks,
        count(case when interaction_type = 'error' then 1 end) as errors,
        avg(duration_ms) as avg_duration
    into recent_patterns
    from public.behavioral_patterns 
    where user_id = user_uuid 
    and timestamp >= now() - (time_window_minutes || ' minutes')::interval;
    if recent_patterns.clicks > (baseline_data.avg_clicks_per_minute * time_window_minutes * 2) then
        confidence_score := confidence_score + 25;
        indicators := indicators || jsonb_build_object('rapid_clicking', true);
    end if;
    if recent_patterns.errors > (baseline_data.avg_error_rate * recent_patterns.total_interactions * 3) then
        confidence_score := confidence_score + 20;
        indicators := indicators || jsonb_build_object('error_spikes', true);
    end if;
    if recent_patterns.avg_duration > (baseline_data.typical_response_time_ms * 1.5) then
        confidence_score := confidence_score + 15;
        indicators := indicators || jsonb_build_object('delayed_responses', true);
    end if;
    confidence_score := least(confidence_score, 100);
    return jsonb_build_object(
        'confidence', confidence_score,
        'indicators', indicators,
        'sample_size', recent_patterns.total_interactions,
        'time_window_minutes', time_window_minutes
    );
end;
$$;

CREATE OR REPLACE FUNCTION public.update_memory_card_timestamp()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    NEW.last_accessed = NOW();
    RETURN NEW;
END;
$$;

create or replace function public.update_memory_card_relevance()
returns trigger
language plpgsql
as $$
begin
    NEW.relevance_score := greatest(0.1, 
        least(2.0, 
            (ln(NEW.access_count + 1) * 0.4) +
            (case 
                when NEW.last_accessed > now() - interval '7 days' then 0.6
                when NEW.last_accessed > now() - interval '30 days' then 0.3
                else 0.1
            end) +
            (case NEW.importance
                when 'critical' then 0.5
                when 'high' then 0.3
                when 'medium' then 0.0
                else -0.2
            end)
        )
    );
    return NEW;
end;
$$;

create or replace function public.get_or_create_user_profile(clerk_id text)
returns uuid
language plpgsql
security definer
as $$
declare
    user_id uuid;
begin
    select id into user_id 
    from public.user_profiles 
    where clerk_user_id = clerk_id;
    if user_id is null then
        insert into public.user_profiles (clerk_user_id)
        values (clerk_id)
        returning id into user_id;
    end if;
    return user_id;
end;
$$;

create or replace function public.log_admin_action(
    p_admin_user_id text,
    p_admin_email text,
    p_action_type text,
    p_resource_type text,
    p_resource_id text default null,
    p_action_details jsonb default '{}',
    p_success boolean default true,
    p_error_message text default null
)
returns uuid
language plpgsql
security definer
as $$
declare
    log_id uuid;
begin
    insert into public.admin_action_logs (
        admin_user_id,
        admin_email,
        action_type,
        resource_type,
        resource_id,
        action_details,
        success,
        error_message
    ) values (
        p_admin_user_id,
        p_admin_email,
        p_action_type,
        p_resource_type,
        p_resource_id,
        p_action_details,
        p_success,
        p_error_message
    ) returning id into log_id;
    return log_id;
end;
$$;

CREATE OR REPLACE FUNCTION current_clerk_user_id()
RETURNS TEXT AS $$
  SELECT (auth.jwt()->>'sub')::TEXT;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION validate_jwt_version()
RETURNS BOOLEAN AS $$
  SELECT COALESCE((auth.jwt()->'v')::INTEGER >= 2, false);
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

create or replace function public.generate_daily_analytics(target_date date default current_date)
returns void
language plpgsql
security definer
as $$
declare
    analytics_record record;
begin
    select
        coalesce(count(distinct c.user_id), 0) as active_users,
        coalesce(count(c.id), 0) as total_conversations,
        coalesce(count(distinct case when up.created_at::date = target_date then up.id end), 0) as new_users,
        coalesce(count(ce.id), 0) as crisis_interventions,
        coalesce(count(case when ce.intervention_successful = true then 1 end), 0) as crisis_resolutions,
        coalesce(count(rs.id), 0) as recovery_sessions_started,
        coalesce(count(case when rs.end_time is not null then 1 end), 0) as recovery_sessions_completed,
        coalesce(avg(case when rs.quality = 'excellent' then 3 when rs.quality = 'good' then 2 when rs.quality = 'poor' then 1 end), 0) as avg_recovery_effectiveness
    into analytics_record
    from public.conversations c
    full outer join public.user_profiles up on c.user_id = up.id
    full outer join public.crisis_events ce on c.user_id = ce.user_id and ce.detection_timestamp::date = target_date
    full outer join public.recovery_sessions rs on c.user_id = rs.user_id and rs.start_time::date = target_date
    where c.timestamp::date = target_date or up.created_at::date = target_date;
    insert into public.system_analytics (
        date,
        period_type,
        total_conversations,
        active_users,
        new_users,
        crisis_interventions,
        crisis_resolutions,
        recovery_sessions_started,
        recovery_sessions_completed,
        avg_recovery_effectiveness
    ) values (
        target_date,
        'day',
        analytics_record.total_conversations,
        analytics_record.active_users,
        analytics_record.new_users,
        analytics_record.crisis_interventions,
        analytics_record.crisis_resolutions,
        analytics_record.recovery_sessions_started,
        analytics_record.recovery_sessions_completed,
        analytics_record.avg_recovery_effectiveness
    ) on conflict (date, period_type) do update set
        total_conversations = excluded.total_conversations,
        active_users = excluded.active_users,
        new_users = excluded.new_users,
        crisis_interventions = excluded.crisis_interventions,
        crisis_resolutions = excluded.crisis_resolutions,
        recovery_sessions_started = excluded.recovery_sessions_started,
        recovery_sessions_completed = excluded.recovery_sessions_completed,
        avg_recovery_effectiveness = excluded.avg_recovery_effectiveness,
        updated_at = now();
end;
$$;

CREATE OR REPLACE FUNCTION public.search_memory_cards(
    user_clerk_id TEXT,
    search_query TEXT DEFAULT '',
    categories TEXT[] DEFAULT NULL,
    energy_state TEXT DEFAULT NULL,
    ui_state_filter TEXT DEFAULT NULL,
    limit_results INTEGER DEFAULT 10
)
RETURNS TABLE (
    id UUID,
    trigger_phrase TEXT,
    content TEXT,
    category TEXT,
    importance TEXT,
    relevance_score DECIMAL,
    last_accessed TIMESTAMP WITH TIME ZONE,
    access_count INTEGER,
    tags TEXT[],
    rank REAL
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_profile_id UUID;
BEGIN
    SELECT up.id INTO user_profile_id
    FROM public.user_profiles up
    WHERE up.clerk_user_id = user_clerk_id;
    IF user_profile_id IS NULL THEN
        RETURN;
    END IF;
    PERFORM set_config('app.current_clerk_user_id', user_clerk_id, true);
    RETURN QUERY
    SELECT 
        mc.id,
        mc.trigger_phrase,
        mc.content,
        mc.category,
        mc.importance,
        mc.relevance_score,
        mc.last_accessed,
        mc.access_count,
        mc.tags,
        CASE 
            WHEN search_query = '' THEN mc.relevance_score::REAL
            ELSE ts_rank_cd(mc.search_vector, plainto_tsquery('english', search_query))
        END as rank
    FROM public.memory_cards mc
    WHERE mc.user_id = user_profile_id
    AND (categories IS NULL OR mc.category = ANY(categories))
    AND (energy_state IS NULL OR energy_state = ANY(mc.surfacing_energy_states))
    AND (ui_state_filter IS NULL OR ui_state_filter = ANY(mc.surfacing_ui_states))
    AND (
        search_query = '' 
        OR mc.search_vector @@ plainto_tsquery('english', search_query)
        OR mc.trigger_phrase ILIKE '%' || search_query || '%'
        OR mc.content ILIKE '%' || search_query || '%'
    )
    ORDER BY 
        CASE 
            WHEN search_query = '' THEN mc.relevance_score::REAL
            ELSE ts_rank_cd(mc.search_vector, plainto_tsquery('english', search_query))
        END DESC,
        mc.last_accessed DESC
    LIMIT limit_results;
END;
$$;

create or replace function public.update_user_baselines(user_uuid uuid)
returns void
language plpgsql
security definer
as $$
declare
    behavior_stats record;
    energy_stats record;
begin
    select 
        count(case when interaction_type = 'click' then 1 end)::decimal / nullif(extract(epoch from max(timestamp) - min(timestamp)) / 60, 0) as clicks_per_minute,
        avg(case when interaction_type = 'input' and (metadata->>'characterCount')::integer > 0 then (metadata->>'characterCount')::integer end) as avg_input_length,
        count(case when interaction_type = 'error' then 1 end)::decimal / nullif(count(*), 0) as error_rate,
        avg(duration_ms) as avg_duration,
        count(*) as sample_size
    into behavior_stats
    from (
        select * from public.behavioral_patterns 
        where user_id = user_uuid 
        order by timestamp desc 
        limit 100
    ) recent_behaviors;
    select 
        avg(energy_level) as avg_energy,
        avg(stress_level) as avg_stress,
        avg(cognitive_load) as avg_cognitive_load,
        avg(social_battery) as avg_social_battery
    into energy_stats
    from (
        select * from public.energy_patterns 
        where user_id = user_uuid 
        order by timestamp desc 
        limit 50
    ) recent_energy;
    insert into public.crisis_baselines (
        user_id,
        avg_clicks_per_minute,
        avg_response_length,
        avg_error_rate,
        typical_response_time_ms,
        avg_energy_level,
        avg_stress_level,
        avg_cognitive_load,
        avg_social_battery,
        sample_size,
        confidence_score,
        updated_at
    ) values (
        user_uuid,
        coalesce(behavior_stats.clicks_per_minute, 5.0),
        coalesce(behavior_stats.avg_input_length::integer, 25),
        coalesce(behavior_stats.error_rate, 0.05),
        coalesce(behavior_stats.avg_duration::integer, 3000),
        coalesce(energy_stats.avg_energy, 7.0),
        coalesce(energy_stats.avg_stress, 3.0),
        coalesce(energy_stats.avg_cognitive_load, 4.0),
        coalesce(energy_stats.avg_social_battery, 8.0),
        coalesce(behavior_stats.sample_size, 0),
        case when behavior_stats.sample_size >= 50 then 0.8 else 0.3 end,
        now()
    ) on conflict (user_id) do update set
        avg_clicks_per_minute = excluded.avg_clicks_per_minute,
        avg_response_length = excluded.avg_response_length,
        avg_error_rate = excluded.avg_error_rate,
        typical_response_time_ms = excluded.typical_response_time_ms,
        avg_energy_level = excluded.avg_energy_level,
        avg_stress_level = excluded.avg_stress_level,
        avg_cognitive_load = excluded.avg_cognitive_load,
        avg_social_battery = excluded.avg_social_battery,
        sample_size = excluded.sample_size,
        confidence_score = excluded.confidence_score,
        updated_at = excluded.updated_at;
end;
$$;

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ language 'plpgsql';

create or replace function public.record_system_metrics()
returns void
language plpgsql
security definer
as $$
begin
    insert into public.system_monitoring (
        cpu_usage_percent,
        memory_usage_percent,
        database_connections_active,
        database_connections_max,
        avg_response_time_ms,
        error_rate_percent,
        requests_per_minute,
        active_users,
        active_crisis_sessions,
        high_risk_users,
        crisis_interventions_today
    ) select
        45.0, -- CPU usage (placeholder)
        62.0, -- Memory usage (placeholder)
        15, -- DB connections active
        50, -- DB connections max
        145.0, -- Avg response time
        0.01, -- Error rate
        120, -- Requests per minute
        (select count(*) from public.user_profiles where updated_at >= now() - interval '1 hour'), -- Active users
        (select count(*) from public.crisis_events where resolution_timestamp is null), -- Active crisis sessions
        (select count(*) from public.crisis_events where severity_level in ('severe', 'critical') and detection_timestamp >= now() - interval '1 day'), -- High risk users
        (select count(*) from public.crisis_events where detection_timestamp >= current_date) -- Crisis interventions today
    ;
end;
$$;

create or replace function get_planning_analytics(user_uuid uuid, days_back integer default 30)
returns jsonb as $$
declare
    result jsonb;
    total_tasks integer;
    completed_tasks integer;
    completion_rate decimal;
    avg_energy_per_task decimal;
    avg_time_accuracy decimal;
    overdue_count integer;
begin
    select 
        count(*) filter (where created_at >= now() - interval '1 day' * days_back),
        count(*) filter (where completed = true and created_at >= now() - interval '1 day' * days_back),
        count(*) filter (where deadline < now() and completed = false)
    into total_tasks, completed_tasks, overdue_count
    from public.tasks 
    where user_id = user_uuid;
    completion_rate := case when total_tasks > 0 then (completed_tasks::decimal / total_tasks * 100) else 0 end;
    select coalesce(avg(energy_cost), 0)
    into avg_energy_per_task
    from public.tasks 
    where user_id = user_uuid and created_at >= now() - interval '1 day' * days_back;
    select coalesce(avg(case when estimated_time > 0 then (actual_time::decimal / estimated_time * 100) else null end), 0)
    into avg_time_accuracy
    from public.tasks 
    where user_id = user_uuid and actual_time is not null and created_at >= now() - interval '1 day' * days_back;
    result := jsonb_build_object(
        'totalTasks', total_tasks,
        'completedTasks', completed_tasks,
        'completionRate', completion_rate,
        'avgEnergyPerTask', avg_energy_per_task,
        'avgTimeAccuracy', avg_time_accuracy,
        'overdueCount', overdue_count,
        'generatedAt', now()
    );
    return result;
end;
$$ language plpgsql security definer;

create or replace function public.update_memory_card_search_vector()
returns trigger
language plpgsql
as $$
begin
    NEW.search_vector := 
        setweight(to_tsvector('english', coalesce(NEW.trigger_phrase, '')), 'A') ||
        setweight(to_tsvector('english', coalesce(NEW.content, '')), 'B') ||
        setweight(to_tsvector('english', coalesce(array_to_string(NEW.tags, ' '), '')), 'C');
    return NEW;
end;
$$;

create or replace function public.archive_old_conversations()
returns integer
language plpgsql
security definer
as $$
declare
    archived_count integer;
begin
    update public.conversations 
    set archived = true, archive_date = now()
    where timestamp < now() - interval '90 days'
    and archived = false
    and (user_feedback is null or user_feedback != 1); -- Keep helpful conversations longer
    get diagnostics archived_count = row_count;
    return archived_count;
end;
$$;

CREATE OR REPLACE FUNCTION public.get_contextual_memories(
    user_clerk_id TEXT,
    current_input TEXT,
    ui_state_context TEXT DEFAULT 'explore',
    energy_level TEXT DEFAULT 'medium',
    limit_results INTEGER DEFAULT 5
)
RETURNS TABLE (
    id UUID,
    trigger_phrase TEXT,
    content TEXT,
    category TEXT,
    relevance_score DECIMAL,
    surfacing_reason TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_profile_id UUID;
    input_keywords TEXT[];
BEGIN
    SELECT up.id INTO user_profile_id
    FROM public.user_profiles up
    WHERE up.clerk_user_id = user_clerk_id;
    IF user_profile_id IS NULL THEN
        RETURN;
    END IF;
    SELECT array_agg(word) INTO input_keywords
    FROM (
        SELECT unnest(string_to_array(lower(current_input), ' ')) as word
        WHERE char_length(unnest(string_to_array(lower(current_input), ' '))) > 3
        LIMIT 10
    ) keywords;
    PERFORM set_config('app.current_clerk_user_id', user_clerk_id, true);
    RETURN QUERY
    SELECT 
        mc.id,
        mc.trigger_phrase,
        mc.content,
        mc.category,
        mc.relevance_score,
        CASE 
            WHEN mc.surfacing_keywords && input_keywords THEN 'Keyword match'
            WHEN ui_state_context = ANY(mc.surfacing_ui_states) THEN 'UI state relevance'
            WHEN energy_level = ANY(mc.surfacing_energy_states) THEN 'Energy level match'
            ELSE 'Context similarity'
        END as surfacing_reason
    FROM public.memory_cards mc
    WHERE mc.user_id = user_profile_id
    AND (
        mc.surfacing_keywords && input_keywords
        OR ui_state_context = ANY(mc.surfacing_ui_states)
        OR energy_level = ANY(mc.surfacing_energy_states)
        OR mc.search_vector @@ plainto_tsquery('english', current_input)
    )
    ORDER BY mc.relevance_score DESC, mc.last_accessed DESC
    LIMIT limit_results;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_memory_card(
    user_clerk_id TEXT,
    trigger_text TEXT,
    content_text TEXT,
    context_info TEXT DEFAULT '',
    category_type TEXT DEFAULT 'personal',
    importance_level TEXT DEFAULT 'medium',
    cognitive_type_val TEXT DEFAULT 'fact',
    energy_level_created TEXT DEFAULT 'medium',
    ui_state_created TEXT DEFAULT 'explore',
    surfacing_keywords TEXT[] DEFAULT '{}',
    surfacing_contexts TEXT[] DEFAULT '{}',
    surfacing_energy_states TEXT[] DEFAULT '{}',
    surfacing_ui_states TEXT[] DEFAULT '{}',
    tags_array TEXT[] DEFAULT '{}'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_profile_id UUID;
    new_card_id UUID;
BEGIN
    SELECT up.id INTO user_profile_id
    FROM public.user_profiles up
    WHERE up.clerk_user_id = user_clerk_id;
    IF user_profile_id IS NULL THEN
        RAISE EXCEPTION 'User profile not found for clerk_id: %', user_clerk_id;
    END IF;
    PERFORM set_config('app.current_clerk_user_id', user_clerk_id, true);
    INSERT INTO public.memory_cards (
        user_id,
        trigger_phrase,
        content,
        context_info,
        category,
        importance,
        cognitive_type,
        energy_level_created,
        ui_state_created,
        surfacing_keywords,
        surfacing_contexts,
        surfacing_energy_states,
        surfacing_ui_states,
        tags,
        access_count,
        relevance_score
    ) VALUES (
        user_profile_id,
        trigger_text,
        content_text,
        context_info,
        category_type,
        importance_level,
        cognitive_type_val,
        energy_level_created,
        ui_state_created,
        surfacing_keywords,
        surfacing_contexts,
        surfacing_energy_states,
        surfacing_ui_states,
        tags_array,
        0,
        1.0
    ) RETURNING id INTO new_card_id;
    RETURN new_card_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_user_preferences(clerk_id text)
RETURNS json
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_prefs json;
BEGIN
    SELECT json_build_object(
        'primarySupport', COALESCE(primary_support, 'adhd'),
        'communicationStyle', COALESCE(communication_style, 'balanced'),
        'responseLength', COALESCE(preferred_response_length, 'standard'),
        'energyLevel', COALESCE(energy_level, 'medium'),
        'uiState', COALESCE(ui_state, 'explore'),
        'reducedMotion', COALESCE((accessibility_preferences->>'reducedMotion')::boolean, false),
        'highContrast', COALESCE((accessibility_preferences->>'highContrast')::boolean, false),
        'textToSpeech', COALESCE((accessibility_preferences->>'textToSpeech')::boolean, false),
        'literalLanguageMode', COALESCE((accessibility_preferences->>'literalLanguageMode')::boolean, false),
        'taskBreakdownEnabled', COALESCE(task_breakdown_enabled, true),
        'memoryAidsEnabled', COALESCE(memory_sharing_enabled, true),
        'crisisDetectionEnabled', COALESCE(crisis_support_enabled, true),
        'progressCelebrationEnabled', COALESCE(progress_celebration_enabled, true),
        'currentStressLevel', COALESCE(current_stress_level, 3),
        'currentSocialBattery', COALESCE(current_social_battery, 8),
        'burnoutRiskScore', COALESCE(burnout_risk_score, 0),
        'crisisModeActive', COALESCE(crisis_mode_active, false),
        'costBudget', COALESCE(daily_cost_budget, 10.0),
        'dailyTokenLimit', COALESCE(daily_token_limit, 5000)
    )
    INTO user_prefs
    FROM public.user_profiles 
    WHERE clerk_user_id = clerk_id;
    RETURN COALESCE(user_prefs, json_build_object(
        'primarySupport', 'adhd',
        'communicationStyle', 'balanced',
        'responseLength', 'standard',
        'energyLevel', 'medium',
        'uiState', 'explore',
        'reducedMotion', false,
        'highContrast', false,
        'textToSpeech', false,
        'literalLanguageMode', false,
        'taskBreakdownEnabled', true,
        'memoryAidsEnabled', true,
        'crisisDetectionEnabled', true,
        'progressCelebrationEnabled', true,
        'currentStressLevel', 3,
        'currentSocialBattery', 8,
        'burnoutRiskScore', 0,
        'crisisModeActive', false,
        'costBudget', 10.0,
        'dailyTokenLimit', 5000
    ));
END;
$$;

CREATE OR REPLACE FUNCTION current_clerk_org_role()
RETURNS TEXT AS $$
  SELECT (auth.jwt()->'o'->>'role')::TEXT;
$$ LANGUAGE SQL STABLE SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.access_memory_card(
    card_id UUID,
    user_clerk_id TEXT
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
    user_profile_id UUID;
BEGIN
    SELECT up.id INTO user_profile_id
    FROM public.user_profiles up
    WHERE up.clerk_user_id = user_clerk_id;
    IF user_profile_id IS NULL THEN
        RETURN FALSE;
    END IF;
    PERFORM set_config('app.current_clerk_user_id', user_clerk_id, true);
    UPDATE public.memory_cards
    SET 
        access_count = access_count + 1,
        last_accessed = NOW()
    WHERE id = card_id 
    AND user_id = user_profile_id;
    RETURN FOUND;
END;
$$;

create or replace function public.cleanup_expired_memory_cards()
returns integer
language plpgsql
security definer
as $$
declare
    deleted_count integer;
begin
    delete from public.memory_cards 
    where importance = 'low'
    and access_count < 3
    and last_accessed < now() - interval '1 year'
    and created_at < now() - interval '1 year';
    get diagnostics deleted_count = row_count;
    return deleted_count;
end;
$$;

create or replace function check_task_completion()
returns trigger as $$
begin
    if new.completed = true and old.completed = false then
        if (select count(*) from public.subtasks where task_id = new.task_id and completed = false) = 0 then
            update public.tasks 
            set completed = true, completed_at = now(), updated_at = now()
            where id = new.task_id and completed = false;
        end if;
    end if;
    return new;
end;
$$ language plpgsql;

CREATE OR REPLACE FUNCTION public.set_session_user(clerk_user_id TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    PERFORM set_config('app.current_clerk_user_id', clerk_user_id, true);
    IF NOT validate_jwt_version() THEN
        RAISE EXCEPTION 'JWT v2 or higher required';
    END IF;
END;
$$;


-- === TRIGGERS OBJECTS ===

create trigger update_memory_search_vector_trigger
    before insert or update on public.memory_cards
    for each row
    execute function public.update_memory_card_search_vector();

create trigger update_planning_preferences_updated_at
    before update on public.planning_preferences
    for each row execute function public.update_updated_at_column();

create trigger update_task_templates_updated_at
    before update on public.task_templates
    for each row execute function public.update_updated_at_column();

create trigger update_task_categories_updated_at
    before update on public.task_categories
    for each row execute function public.update_updated_at_column();

create trigger update_memory_relevance_trigger
    before update on public.memory_cards
    for each row
    execute function public.update_memory_card_relevance();

create trigger update_subtasks_updated_at
    before update on public.subtasks
    for each row execute function public.update_updated_at_column();

CREATE TRIGGER update_conversations_updated_at
    BEFORE UPDATE ON public.conversations
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

create trigger update_planning_sessions_updated_at
    before update on public.planning_sessions
    for each row execute function public.update_updated_at_column();

CREATE TRIGGER update_user_profiles_updated_at
    BEFORE UPDATE ON public.user_profiles
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

create trigger auto_complete_task_on_subtasks
    after update on public.subtasks
    for each row execute function check_task_completion();

CREATE TRIGGER update_memory_cards_updated_at
    BEFORE UPDATE ON public.memory_cards
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_memory_card_timestamp_trigger
    BEFORE UPDATE ON public.memory_cards
    FOR EACH ROW
    WHEN (OLD.access_count IS DISTINCT FROM NEW.access_count)
    EXECUTE FUNCTION public.update_memory_card_timestamp();

create trigger update_tasks_updated_at
    before update on public.tasks
    for each row execute function public.update_updated_at_column();


-- === INDEXES OBJECTS ===

-- CONSOLIDATED FROM MIGRATION 13
create index if not exists idx_memory_cards_user_updated on public.memory_cards(user_id, updated_at desc);

create index if not exists idx_conversations_conversation_id on public.conversations(conversation_id);

create index if not exists idx_tasks_completed on public.tasks(completed);

create index if not exists idx_system_settings_key on public.system_settings(setting_key);

create index if not exists idx_user_profiles_burnout_risk on public.user_profiles(burnout_risk_score) where burnout_risk_score > 50;

create index if not exists idx_admin_action_logs_timestamp on public.admin_action_logs(timestamp);

create index if not exists idx_behavioral_patterns_session on public.behavioral_patterns(session_id);

create index if not exists idx_energy_patterns_user_id on public.energy_patterns(user_id);

create index if not exists idx_user_profiles_primary_support on public.user_profiles(primary_support);

create index if not exists idx_memory_cards_keywords on public.memory_cards using gin(surfacing_keywords);

create index if not exists idx_crisis_events_detection_time on public.crisis_events(detection_timestamp);

create index if not exists idx_crisis_logs_user_id on public.crisis_support_logs(user_id);

create index if not exists idx_user_activity_snapshots_active on public.user_activity_snapshots(is_active);

create index if not exists idx_behavioral_patterns_user_id on public.behavioral_patterns(user_id);

create index if not exists idx_admin_action_logs_resource on public.admin_action_logs(resource_type, resource_id);

create index if not exists idx_user_profiles_onboarding_completed on public.user_profiles(onboarding_completed);

create index if not exists idx_admin_action_logs_action_type on public.admin_action_logs(action_type);

create index if not exists idx_subtasks_task_id on public.subtasks(task_id);

create index if not exists idx_planning_sessions_start_time on public.planning_sessions(start_time);

create index if not exists idx_system_analytics_period on public.system_analytics(period_type);

create index if not exists idx_behavioral_patterns_timestamp on public.behavioral_patterns(timestamp);

create index if not exists idx_tasks_category on public.tasks(category);

create index if not exists idx_system_analytics_date on public.system_analytics(date);

create index if not exists idx_tasks_priority on public.tasks(priority);

create index if not exists idx_system_monitoring_recent on public.system_monitoring(timestamp desc);

create index if not exists idx_memory_cards_updated_at on public.memory_cards(updated_at desc);

create index if not exists idx_social_battery_timestamp on public.social_battery(timestamp);

create index if not exists idx_user_profiles_stress_level on public.user_profiles(current_stress_level);

create index if not exists idx_user_activity_snapshots_user_id on public.user_activity_snapshots(user_id);

create index if not exists idx_user_profiles_crisis_mode on public.user_profiles(crisis_mode_active) where crisis_mode_active = true;

create index if not exists idx_energy_patterns_activity on public.energy_patterns(activity_type);

create index if not exists idx_crisis_logs_timestamp on public.crisis_support_logs(crisis_started);

create index if not exists idx_user_activity_snapshots_attention on public.user_activity_snapshots(requires_admin_attention) where requires_admin_attention = true;

create index if not exists idx_conversations_timestamp on public.conversations(timestamp);

create index if not exists idx_system_monitoring_timestamp on public.system_monitoring(timestamp);

create index if not exists idx_user_profiles_energy_level on public.user_profiles(energy_level);

-- CONSOLIDATED FROM MIGRATION 13
create index if not exists idx_usage_analytics_date on public.usage_analytics(date);

create index if not exists idx_recovery_activities_difficulty on public.recovery_activities(difficulty_level);

create index if not exists idx_recovery_sessions_activity_id on public.recovery_sessions(activity_id);

create index if not exists idx_admin_action_logs_admin on public.admin_action_logs(admin_user_id);

-- CONSOLIDATED FROM MIGRATION 13
create index if not exists idx_conversations_user_id on public.conversations(user_id);

CREATE INDEX IF NOT EXISTS idx_memory_cards_user_energy ON public.memory_cards USING gin(surfacing_energy_states);

create index if not exists idx_recovery_sessions_start_time on public.recovery_sessions(start_time);

create index if not exists idx_behavioral_patterns_type on public.behavioral_patterns(interaction_type);

create index if not exists idx_recovery_activities_type on public.recovery_activities(type);

create index if not exists idx_tasks_deadline on public.tasks(deadline);

create index if not exists idx_conversations_updated_at on public.conversations(updated_at desc);

create index if not exists idx_social_interactions_user_id on public.social_interactions(user_id);

create index if not exists idx_system_settings_public on public.system_settings(is_public) where is_public = true;

create index if not exists idx_system_settings_category on public.system_settings(category);

create index if not exists idx_user_profiles_ui_state on public.user_profiles(ui_state);

create index if not exists idx_memory_cards_category on public.memory_cards(category);

create index if not exists idx_user_activity_snapshots_date on public.user_activity_snapshots(snapshot_date);

create index if not exists idx_crisis_events_user_id on public.crisis_events(user_id);

CREATE INDEX IF NOT EXISTS idx_memory_cards_user_ui_states ON public.memory_cards USING gin(surfacing_ui_states);

create index if not exists idx_planning_sessions_user_id on public.planning_sessions(user_id);

create index if not exists idx_crisis_baselines_user_id on public.crisis_baselines(user_id);

create index if not exists idx_memory_cards_user_id on public.memory_cards(user_id);

create index if not exists idx_recovery_activities_active on public.recovery_activities(is_active);

create index if not exists idx_task_templates_user_id on public.task_templates(user_id);

create index if not exists idx_social_battery_user_id on public.social_battery(user_id);

create index if not exists idx_subtasks_order on public.subtasks(task_id, order_position);

create index if not exists idx_memory_cards_tags on public.memory_cards using gin(tags);

CREATE INDEX IF NOT EXISTS idx_user_profiles_clerk_id ON public.user_profiles(clerk_user_id);

create index if not exists idx_tasks_user_id on public.tasks(user_id);

create index if not exists idx_memory_cards_search_vector on public.memory_cards using gin(search_vector);

create index if not exists idx_recovery_plans_active on public.recovery_plans(is_active);

create index if not exists idx_task_categories_user_id on public.task_categories(user_id);

create index if not exists idx_social_interactions_started_at on public.social_interactions(started_at);

create index if not exists idx_tasks_created_at on public.tasks(created_at);

create index if not exists idx_crisis_events_unresolved on public.crisis_events(resolution_timestamp) where resolution_timestamp is null;

create index if not exists idx_social_interactions_interaction_type on public.social_interactions(interaction_type);

create index if not exists idx_memory_cards_importance on public.memory_cards(importance);

create index if not exists idx_recovery_plans_user_id on public.recovery_plans(user_id);

create index if not exists idx_crisis_events_severity on public.crisis_events(severity_level);

CREATE INDEX IF NOT EXISTS idx_memory_cards_user_contexts ON public.memory_cards USING gin(surfacing_contexts);

create index if not exists idx_recovery_sessions_user_id on public.recovery_sessions(user_id);

create index if not exists idx_recovery_preferences_user_id on public.recovery_preferences(user_id);

create index if not exists idx_planning_sessions_active on public.planning_sessions(user_id, end_time) where end_time is null;

create index if not exists idx_energy_patterns_timestamp on public.energy_patterns(timestamp);

create index if not exists idx_recovery_sessions_quality on public.recovery_sessions(quality);

create index if not exists idx_subtasks_completed on public.subtasks(completed);


-- === SECURITY OBJECTS ===

CREATE POLICY "tasks_user_access_jwt_v2" ON public.tasks
    FOR ALL 
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM public.user_profiles 
            WHERE clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

CREATE POLICY "crisis_baselines_jwt_v2" ON public.crisis_baselines
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "admin_user_snapshots_jwt_v2" ON public.user_activity_snapshots
    FOR ALL 
    TO authenticated
    USING (
        (current_clerk_org_role() IN ('admin', 'owner') OR 
         (auth.jwt()->>'role') = 'service_role') AND
        validate_jwt_version()
    );

CREATE POLICY "conversations_jwt_v2" ON public.conversations
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "public_settings_readable_jwt_v2" ON public.system_settings
    FOR SELECT 
    TO authenticated
    USING (
        is_public = true AND 
        validate_jwt_version()
    );

CREATE POLICY "recovery_activities_admin_delete" ON public.recovery_activities
  FOR DELETE 
  TO authenticated 
  USING (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  );

CREATE POLICY "memory_cards_jwt_v2" ON public.memory_cards
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "energy_patterns_jwt_v2" ON public.energy_patterns
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "crisis_logs_jwt_v2" ON public.crisis_support_logs
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "recovery_activities_read_all" ON public.recovery_activities
  FOR SELECT 
  TO authenticated 
  USING (validate_jwt_version());

CREATE POLICY "recovery_preferences_jwt_v2" ON public.recovery_preferences
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "usage_analytics_service_only" ON public.usage_analytics
  FOR ALL 
  TO authenticated
  USING (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  );

CREATE POLICY "user_profiles_jwt_v2" ON public.user_profiles
  FOR ALL 
  TO authenticated 
  USING (
    clerk_user_id = current_clerk_user_id() AND
    validate_jwt_version()
  );

CREATE POLICY "social_interactions_jwt_v2" ON public.social_interactions
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "recovery_plans_jwt_v2" ON public.recovery_plans
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "planning_preferences_user_access_jwt_v2" ON public.planning_preferences
    FOR ALL 
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM public.user_profiles 
            WHERE clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

CREATE POLICY "recovery_sessions_jwt_v2" ON public.recovery_sessions
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "ai_providers_service_only" ON public.ai_providers
  FOR ALL 
  TO authenticated
  USING (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  );

CREATE POLICY "admin_system_settings_jwt_v2" ON public.system_settings
    FOR ALL 
    TO authenticated
    USING (
        (current_clerk_org_role() IN ('admin', 'owner') OR 
         (auth.jwt()->>'role') = 'service_role') AND
        validate_jwt_version()
    );

CREATE POLICY "admin_analytics_jwt_v2" ON public.system_analytics
    FOR ALL 
    TO authenticated
    USING (
        (current_clerk_org_role() IN ('admin', 'owner') OR 
         (auth.jwt()->>'role') = 'service_role') AND
        validate_jwt_version()
    );

CREATE POLICY "social_battery_jwt_v2" ON public.social_battery
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "subtasks_user_access_jwt_v2" ON public.subtasks
    FOR ALL 
    TO authenticated
    USING (
        task_id IN (
            SELECT t.id FROM public.tasks t
            JOIN public.user_profiles up ON t.user_id = up.id
            WHERE up.clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

CREATE POLICY "admin_monitoring_data_jwt_v2" ON public.system_monitoring
    FOR ALL 
    TO authenticated
    USING (
        (current_clerk_org_role() IN ('admin', 'owner') OR 
         (auth.jwt()->>'role') = 'service_role') AND
        validate_jwt_version()
    );

CREATE POLICY "behavioral_patterns_jwt_v2" ON public.behavioral_patterns
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "task_categories_user_access_jwt_v2" ON public.task_categories
    FOR ALL 
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM public.user_profiles 
            WHERE clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

CREATE POLICY "admin_action_logs_jwt_v2" ON public.admin_action_logs
    FOR ALL 
    TO authenticated
    USING (
        (current_clerk_org_role() IN ('admin', 'owner') OR 
         (auth.jwt()->>'role') = 'service_role') AND
        validate_jwt_version()
    );

CREATE POLICY "crisis_events_jwt_v2" ON public.crisis_events
  FOR ALL 
  TO authenticated 
  USING (
    user_id IN (
      SELECT id FROM public.user_profiles 
      WHERE clerk_user_id = current_clerk_user_id()
    ) AND validate_jwt_version()
  );

CREATE POLICY "recovery_activities_admin_modify" ON public.recovery_activities
  FOR INSERT 
  TO authenticated 
  WITH CHECK (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  );

CREATE POLICY "task_templates_user_access_jwt_v2" ON public.task_templates
    FOR ALL 
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM public.user_profiles 
            WHERE clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

CREATE POLICY "recovery_activities_admin_update" ON public.recovery_activities
  FOR UPDATE 
  TO authenticated 
  USING (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  )
  WITH CHECK (
    (auth.jwt()->>'role') = 'service_role' AND
    validate_jwt_version()
  );

CREATE POLICY "planning_sessions_user_access_jwt_v2" ON public.planning_sessions
    FOR ALL 
    TO authenticated
    USING (
        user_id IN (
            SELECT id FROM public.user_profiles 
            WHERE clerk_user_id = current_clerk_user_id()
        ) AND validate_jwt_version()
    );

