-- Generated by pgsquash with modern PostgreSQL patterns
-- Safety level: aggressive
-- Generated at: 2025-11-07T10:46:02+02:00


-- === AUTH COMPATIBILITY LAYER ===
-- Auto-injected stubs for Supabase/Clerk authentication

-- Supabase Authentication Compatibility Layer
CREATE SCHEMA IF NOT EXISTS auth;

-- Create auth.users table stub for foreign key references
-- This allows migrations to reference auth.users(id) without errors
CREATE TABLE IF NOT EXISTS auth.users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email TEXT,
    encrypted_password TEXT,
    email_confirmed_at TIMESTAMPTZ,
    invited_at TIMESTAMPTZ,
    confirmation_token TEXT,
    confirmation_sent_at TIMESTAMPTZ,
    recovery_token TEXT,
    recovery_sent_at TIMESTAMPTZ,
    email_change_token_new TEXT,
    email_change TEXT,
    email_change_sent_at TIMESTAMPTZ,
    last_sign_in_at TIMESTAMPTZ,
    raw_app_meta_data JSONB,
    raw_user_meta_data JSONB,
    is_super_admin BOOLEAN,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    phone TEXT,
    phone_confirmed_at TIMESTAMPTZ,
    phone_change TEXT,
    phone_change_token TEXT,
    phone_change_sent_at TIMESTAMPTZ,
    confirmed_at TIMESTAMPTZ,
    email_change_token_current TEXT,
    email_change_confirm_status SMALLINT,
    banned_until TIMESTAMPTZ,
    reauthentication_token TEXT,
    reauthentication_sent_at TIMESTAMPTZ,
    is_sso_user BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMPTZ
);

-- Create Supabase roles (used in RLS policies)
DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'anon') THEN
    CREATE ROLE anon NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'authenticated') THEN
    CREATE ROLE authenticated NOLOGIN;
  END IF;
  IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'service_role') THEN
    CREATE ROLE service_role NOLOGIN;
  END IF;
END
$$;

-- Mock Supabase auth.uid() function
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION auth.uid() RETURNS uuid LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11'::uuid;
END;
$$;

-- Mock Supabase auth.jwt() function
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN jsonb_build_object(
    'sub', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11',
    'email', 'mock@supabase.io',
    'role', 'authenticated',
    'iat', extract(epoch from now()),
    'exp', extract(epoch from now()) + 3600
  );
END;
$$;

-- Mock Supabase auth.email() function (commonly used in RLS policies)
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION auth.email() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt() ->> 'email')::text;
END;
$$;

-- Mock Supabase auth.role() function (commonly used in RLS policies)
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION auth.role() RETURNS text LANGUAGE plpgsql SECURITY DEFINER AS $$
BEGIN
  RETURN (auth.jwt() ->> 'role')::text;
END;
$$;

-- Create Supabase Realtime publication if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    CREATE PUBLICATION supabase_realtime;
  END IF;
END
$$;

-- Create storage schema and buckets table stub (Supabase Storage)
CREATE SCHEMA IF NOT EXISTS storage;

CREATE TABLE IF NOT EXISTS storage.buckets (
    id TEXT PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    owner UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    public BOOLEAN DEFAULT FALSE,
    avif_autodetection BOOLEAN DEFAULT FALSE,
    file_size_limit BIGINT,
    allowed_mime_types TEXT[]
);

CREATE TABLE IF NOT EXISTS storage.objects (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    bucket_id TEXT REFERENCES storage.buckets(id),
    name TEXT NOT NULL,
    owner UUID REFERENCES auth.users(id),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    last_accessed_at TIMESTAMPTZ,
    metadata JSONB,
    UNIQUE(bucket_id, name)
);

-- Mock Supabase storage.foldername() function (extracts folder path components)
-- NOTE: No volatility marker - let PostgreSQL use defaults for test mocks
CREATE OR REPLACE FUNCTION storage.foldername(name TEXT) RETURNS TEXT[] LANGUAGE plpgsql AS $$
BEGIN
  -- Split path by '/' and return array of folder components
  -- Example: 'user_id/avatars/image.png' returns ['user_id', 'avatars', 'image.png']
  RETURN string_to_array(name, '/');
END;
$$;


-- === STORAGE SCHEMA ===
-- Storage schema must exist before policies that reference storage.objects/buckets

CREATE SCHEMA IF NOT EXISTS storage;


-- === EXTENSIONS OBJECTS ===

CREATE EXTENSION IF NOT EXISTS "pg_trgm";


-- === FOUNDATION OBJECTS ===

CREATE TABLE IF NOT EXISTS public.sync_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sync_type TEXT NOT NULL, -- 'github', 'local', 'manual', 'scheduled'
  added_count INTEGER DEFAULT 0,
  updated_count INTEGER DEFAULT 0,
  error_count INTEGER DEFAULT 0,
  errors JSONB DEFAULT '[]'::JSONB,
  duration_ms INTEGER,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT UNIQUE NOT NULL,
  name TEXT,
  github_username TEXT,
  avatar_url TEXT,
  preferred_language TEXT,
  preferred_theme TEXT DEFAULT 'system',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE cli_performance_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cli_version TEXT NOT NULL,
  command TEXT NOT NULL,
  operation TEXT NOT NULL, -- e.g., "project_scan", "blueprint_generation", "file_write"
  duration_ms INTEGER NOT NULL,
  memory_usage_mb NUMERIC,
  files_processed INTEGER,
  platform TEXT NOT NULL,
  session_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS vdk_versions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    component TEXT NOT NULL, -- 'cli', 'hub', 'blueprints'
    version TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'stable', -- 'stable', 'beta', 'alpha', 'critical'
    description TEXT,
    security_patch BOOLEAN DEFAULT FALSE,
    download_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cli_error_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cli_version TEXT NOT NULL,
  command TEXT NOT NULL,
  error_type TEXT NOT NULL,
  error_message TEXT NOT NULL,
  stack_trace TEXT,
  platform TEXT NOT NULL,
  node_version TEXT,
  user_id TEXT,
  session_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  context JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS team_configurations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    team_id TEXT NOT NULL,
    user_id UUID NOT NULL,
    team_name TEXT DEFAULT 'Team',
    main_config JSONB DEFAULT '{}',
    rules_config JSONB DEFAULT '{}',
    settings_config JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(team_id, user_id)
);

CREATE TABLE IF NOT EXISTS vdk_analytics (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID,
    project_id TEXT,
    event_type TEXT NOT NULL,
    event_data JSONB DEFAULT '{}',
    metadata JSONB DEFAULT '{}',
    ip_address TEXT,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_command_stats (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL,
    command TEXT NOT NULL,
    usage_count INTEGER DEFAULT 1,
    last_used TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, command)
);

-- For better text search
CREATE TABLE IF NOT EXISTS public.categories (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL,
  icon TEXT,
  parent_id UUID REFERENCES public.categories (id) ON DELETE SET NULL,
  order_index INTEGER DEFAULT 0,
  category_type TEXT DEFAULT 'universal' CHECK (category_type IN ('core', 'language', 'technology', 'stack', 'task', 'assistant', 'tool', 'project', 'universal')),
  platform_specific BOOLEAN DEFAULT false,
  supported_platforms TEXT[] DEFAULT ARRAY[
    'claude-code', 'claude-desktop', 'cursor', 'windsurf', 'windsurf-next', 'github-copilot',
    'zed', 'vscode', 'vscode-insiders', 'vscodium', 'jetbrains', 'intellij', 'webstorm',
    'pycharm', 'phpstorm', 'rubymine', 'clion', 'datagrip', 'goland', 'rider',
    'android-studio', 'openai', 'generic-ai'
  ],
  metadata JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cli_deployments (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    deployment_id TEXT NOT NULL UNIQUE,
    project_name TEXT NOT NULL,
    project_signature JSONB NOT NULL,
    team_name TEXT,
    blueprints_count INTEGER NOT NULL DEFAULT 0,
    metadata JSONB DEFAULT '{}',
    deployed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS vdk_error_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID,
    project_id TEXT,
    error_type TEXT NOT NULL,
    error_message TEXT,
    stack_trace TEXT,
    context JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS cli_recommendations (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    recommendation_id TEXT NOT NULL UNIQUE,
    project_signature JSONB NOT NULL,
    blueprints_recommended INTEGER NOT NULL DEFAULT 0,
    max_blueprints_requested INTEGER DEFAULT 20,
    excluded_blueprint_ids TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.admins (
  email TEXT PRIMARY KEY,
  added_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE cli_integration_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cli_version TEXT NOT NULL,
  integration_type TEXT NOT NULL CHECK (
    integration_type IN ('claude-code', 'cursor', 'windsurf', 'github-copilot', 'vscode', 'other')
  ),
  action TEXT NOT NULL CHECK (
    action IN ('detected', 'configured', 'activated', 'error')
  ),
  success BOOLEAN NOT NULL DEFAULT true,
  error_message TEXT,
  integration_version TEXT,
  configuration_details JSONB DEFAULT '{}'::jsonb,
  user_id TEXT,
  session_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS community_blueprints (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug VARCHAR(255) UNIQUE NOT NULL,
  title VARCHAR(500) NOT NULL,
  description TEXT,
  content TEXT NOT NULL,
  author_id UUID NOT NULL,
  author_username VARCHAR(255) NOT NULL,
  category VARCHAR(100),
  framework VARCHAR(100),
  language VARCHAR(100),
  tags JSONB DEFAULT '[]'::jsonb,
  complexity VARCHAR(50) DEFAULT 'intermediate' CHECK (complexity IN ('beginner', 'intermediate', 'advanced')),
  platforms JSONB DEFAULT '{}'::jsonb,
  relationships JSONB DEFAULT '{}'::jsonb,
  usage_count INTEGER DEFAULT 0 CHECK (usage_count >= 0),
  rating DECIMAL(3,2) DEFAULT 0 CHECK (rating >= 0 AND rating <= 5),
  vote_count INTEGER DEFAULT 0 CHECK (vote_count >= 0),
  deployment_success_rate DECIMAL(3,2) DEFAULT 0 CHECK (deployment_success_rate >= 0 AND deployment_success_rate <= 1),
  status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  published_at TIMESTAMP WITH TIME ZONE
);

CREATE TABLE cli_usage_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  cli_version TEXT NOT NULL,
  command TEXT NOT NULL,
  platform TEXT NOT NULL, -- OS platform (darwin, linux, win32)
  node_version TEXT,
  execution_time_ms INTEGER NOT NULL,
  success BOOLEAN NOT NULL DEFAULT true,
  error_message TEXT,
  project_type TEXT, -- Detected project type (react, nextjs, vue, etc.)
  blueprints_generated INTEGER,
  integrations_detected TEXT[], -- Array of detected IDE/AI assistants
  user_id TEXT, -- Optional user identification
  session_id TEXT NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  metadata JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_project_stats (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL,
    project_id TEXT NOT NULL,
    last_sync TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    sync_count INTEGER DEFAULT 1,
    blueprints_synced INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, project_id)
);

CREATE TABLE IF NOT EXISTS public.collections (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  is_public BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_platform_stats (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL,
    platform TEXT NOT NULL,
    usage_count INTEGER DEFAULT 1,
    last_used TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, platform)
);

CREATE TABLE IF NOT EXISTS public.wizard_configurations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE SET NULL, -- Optional for anonymous users
  session_id TEXT,                  -- For anonymous users
  stack_choices JSONB NOT NULL,     -- Selected frameworks (React, Vue, etc.)
  language_choices JSONB NOT NULL,  -- Programming languages (TS, JS, etc.)
  tool_preferences JSONB NOT NULL,  -- Development tools (ESLint, Prettier, etc.)
  environment_details JSONB NOT NULL, -- Environment specifics (Node version, etc.)
  ai_assistant_choices JSONB DEFAULT '{}' NOT NULL, -- Selected AI assistants (Claude Code, Cursor, Windsurf, GitHub Copilot)
  output_format TEXT DEFAULT 'zip', -- Preferred output format
  custom_requirements TEXT,         -- Additional user requirements
  generated_blueprints TEXT[],           -- Array of blueprint IDs included in generation
  generation_timestamp TIMESTAMPTZ DEFAULT NOW(),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.generation_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL UNIQUE,        -- 'bash-script', 'zip-archive', 'docker-setup'
  description TEXT,
  template_content TEXT NOT NULL,   -- Template file content with placeholders
  output_format TEXT NOT NULL,      -- File extension or format type
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS user_api_tokens (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    token_name TEXT NOT NULL DEFAULT 'CLI Token',
    token_hash TEXT NOT NULL UNIQUE,
    token_prefix TEXT NOT NULL, -- First 8 chars for display
    last_used TIMESTAMP WITH TIME ZONE,
    expires_at TIMESTAMP WITH TIME ZONE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.blueprints (
  id TEXT PRIMARY KEY, -- Using text ID for GitHub path-based IDs
  title TEXT NOT NULL,
  slug TEXT NOT NULL,
  description TEXT NOT NULL,
  content TEXT NOT NULL,
  path TEXT NOT NULL UNIQUE, -- Original GitHub path
  category_id UUID NOT NULL REFERENCES public.categories (id) ON DELETE CASCADE,
  version TEXT NOT NULL DEFAULT '1.0.0',
  downloads INTEGER DEFAULT 0,
  votes INTEGER DEFAULT 0,
  globs TEXT[] DEFAULT '{}',
  tags TEXT[] DEFAULT '{}',
  examples JSONB DEFAULT '{}'::JSONB,
  compatibility JSONB DEFAULT '{"ides": [], "aiAssistants": [], "frameworks": [], "mcpServers": []}'::JSONB,
  always_apply BOOLEAN DEFAULT FALSE,
  frontmatter JSONB DEFAULT '{}',
  subcategory TEXT,
  framework TEXT,
  language TEXT,
  stack TEXT,
  complexity TEXT CHECK (complexity IN ('simple', 'medium', 'complex')),
  scope TEXT CHECK (scope IN ('file', 'component', 'feature', 'project', 'system')),
  audience TEXT CHECK (audience IN ('developer', 'architect', 'team-lead', 'junior', 'senior', 'any')),
  maturity TEXT CHECK (maturity IN ('experimental', 'beta', 'stable', 'deprecated')),
  repository_url TEXT,
  license TEXT,
  schema_version TEXT DEFAULT '2.1.0',
  content_sections JSONB DEFAULT '[]',
  author TEXT DEFAULT 'community',
  contributors TEXT[] DEFAULT '{}',
  discussion_url TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  last_updated TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS cli_deployment_blueprints (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    deployment_id TEXT NOT NULL REFERENCES cli_deployments(deployment_id) ON DELETE CASCADE,
    blueprint_name TEXT NOT NULL,
    blueprint_content TEXT NOT NULL,
    blueprint_path TEXT NOT NULL,
    blueprint_size INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS blueprint_usage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id UUID NOT NULL REFERENCES community_blueprints(id) ON DELETE CASCADE,
  session_id VARCHAR(255) NOT NULL,
  framework VARCHAR(100),
  language VARCHAR(100),
  platform VARCHAR(100),
  cli_version VARCHAR(50),
  success BOOLEAN DEFAULT false,
  platforms_deployed JSONB DEFAULT '[]'::jsonb,
  adaptation_count INTEGER DEFAULT 0 CHECK (adaptation_count >= 0),
  compatibility_score DECIMAL(3,2) CHECK (compatibility_score IS NULL OR (compatibility_score >= 0 AND compatibility_score <= 1)),
  deployed_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS blueprint_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id UUID NOT NULL REFERENCES community_blueprints(id) ON DELETE CASCADE,
  user_id UUID NOT NULL,
  vote_type VARCHAR(10) NOT NULL CHECK (vote_type IN ('up', 'down')),
  rating INTEGER CHECK (rating IS NULL OR (rating >= 1 AND rating <= 5)),
  comment TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(blueprint_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.generated_packages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  configuration_id UUID REFERENCES public.wizard_configurations(id) ON DELETE SET NULL,
  package_type TEXT NOT NULL,       -- 'bash', 'zip', 'config', etc.
  download_url TEXT,               -- S3/Storage URL for generated package
  file_size INTEGER,               -- Package size in bytes
  blueprint_count INTEGER,              -- Number of blueprints included
  download_count INTEGER DEFAULT 0, -- Download tracking
  expires_at TIMESTAMPTZ,          -- Package expiration date
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blueprint_validations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  schema_version TEXT NOT NULL,
  validation_status TEXT NOT NULL CHECK (validation_status IN ('valid', 'warning', 'error')),
  validation_errors JSONB DEFAULT '[]',
  validation_warnings JSONB DEFAULT '[]',
  validated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blueprint_dependencies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  depends_on_blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  dependency_type TEXT CHECK (dependency_type IN ('requires', 'conflicts', 'enhances')),
  condition_tags JSONB,             -- Conditional dependencies based on tech stack
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(blueprint_id, depends_on_blueprint_id, dependency_type)
);

CREATE TABLE IF NOT EXISTS public.commands (
  id TEXT PRIMARY KEY, -- Uses kebab-case command ID from schema
  name TEXT NOT NULL,
  description TEXT NOT NULL CHECK (char_length(description) >= 10 AND char_length(description) <= 200),
  target TEXT NOT NULL DEFAULT 'claude-code' CHECK (target IN ('claude-code')),
  command_type TEXT NOT NULL CHECK (command_type IN ('slash', 'custom-slash', 'mcp', 'workflow', 'hook')),
  version TEXT CHECK (version ~ '^\d+\.\d+\.\d+$'),
  scope TEXT DEFAULT 'project' CHECK (scope IN ('user', 'project', 'global')),
  permissions JSONB DEFAULT '{}',
  claude_code_config JSONB DEFAULT '{}',
  examples JSONB DEFAULT '[]',
  installation JSONB DEFAULT '{}',
  tags TEXT[] DEFAULT '{}',
  category TEXT CHECK (category IN ('development', 'testing', 'debugging', 'refactoring', 'documentation', 'git', 'analysis', 'security', 'performance')),
  author TEXT,
  last_updated DATE,
  compatibility_notes TEXT,
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE SET NULL,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  CONSTRAINT valid_name_length CHECK (char_length(name) >= 1 AND char_length(name) <= 50),
  CONSTRAINT valid_id_format CHECK (id ~ '^[a-z0-9-]+$')
);

CREATE TABLE IF NOT EXISTS public.user_votes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(user_id, blueprint_id)
);

CREATE TABLE IF NOT EXISTS public.blueprint_relationships (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  related_blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  relationship_type TEXT NOT NULL CHECK (relationship_type IN ('requires', 'suggests', 'conflicts', 'supersedes', 'enhances')),
  condition_tags JSONB DEFAULT '[]',
  condition_platforms TEXT[] DEFAULT '{}',
  condition_stack TEXT,
  priority INTEGER DEFAULT 1 CHECK (priority >= 1 AND priority <= 10),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(blueprint_id, related_blueprint_id, relationship_type)
);

CREATE TABLE IF NOT EXISTS user_blueprint_usage (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID NOT NULL,
    blueprint_id TEXT NOT NULL REFERENCES blueprints(id) ON DELETE CASCADE,
    usage_count INTEGER DEFAULT 1,
    last_used TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, blueprint_id)
);

CREATE TABLE IF NOT EXISTS public.blueprint_compatibility (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  technology TEXT NOT NULL,         -- 'react', 'typescript', 'eslint', etc.
  version_pattern TEXT,             -- Semantic version pattern (^18.0.0, >=16.0.0)
  compatibility_type TEXT CHECK (compatibility_type IN ('required', 'recommended', 'optional', 'incompatible')),
  notes TEXT,                       -- Additional compatibility notes
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.blueprint_platforms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  platform_type TEXT NOT NULL CHECK (platform_type IN (
    'claude-code', 'claude-desktop', 'cursor', 'windsurf', 'windsurf-next', 'github-copilot',
    'zed', 'vscode', 'vscode-insiders', 'vscodium', 'jetbrains', 'intellij', 'webstorm',
    'pycharm', 'phpstorm', 'rubymine', 'clion', 'datagrip', 'goland', 'rider',
    'android-studio', 'openai', 'generic-ai'
  )),
  platform_config JSONB NOT NULL DEFAULT '{}',
  is_compatible BOOLEAN DEFAULT true,
  priority INTEGER DEFAULT 5 CHECK (priority >= 1 AND priority <= 10),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(blueprint_id, platform_type)
);

CREATE TABLE IF NOT EXISTS public.platform_commands (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  platform_type TEXT NOT NULL CHECK (platform_type IN (
    'claude-code', 'claude-desktop', 'cursor', 'windsurf', 'windsurf-next', 'github-copilot',
    'zed', 'vscode', 'vscode-insiders', 'vscodium', 'jetbrains', 'intellij', 'webstorm',
    'pycharm', 'phpstorm', 'rubymine', 'clion', 'datagrip', 'goland', 'rider',
    'android-studio', 'openai', 'generic-ai'
  )),
  command_name TEXT NOT NULL,
  command_content TEXT NOT NULL,
  command_metadata JSONB DEFAULT '{}',
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(blueprint_id, platform_type, command_name)
);

CREATE TABLE IF NOT EXISTS public.blueprint_versions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  version TEXT NOT NULL,
  content TEXT NOT NULL,
  changes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE OR REPLACE VIEW cli_deployment_summary AS
SELECT
    d.deployment_id,
    d.project_name,
    d.team_name,
    d.blueprints_count,
    d.deployed_at,
    d.project_signature,
    COUNT(r.id) as actual_blueprints_stored,
    COALESCE(SUM(r.blueprint_size), 0) as total_blueprints_size
FROM cli_deployments d
LEFT JOIN cli_deployment_blueprints r ON d.deployment_id = r.deployment_id
GROUP BY d.deployment_id, d.project_name, d.team_name, d.blueprints_count, d.deployed_at, d.project_signature
ORDER BY d.deployed_at DESC;

CREATE TABLE IF NOT EXISTS public.collection_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  collection_id UUID REFERENCES public.collections(id) ON DELETE CASCADE,
  blueprint_id TEXT REFERENCES public.blueprints(id) ON DELETE CASCADE,
  added_at TIMESTAMPTZ DEFAULT NOW(),
  UNIQUE(collection_id, blueprint_id),
    command_id TEXT REFERENCES commands(id) ON DELETE CASCADE,
    item_type TEXT GENERATED ALWAYS AS ( CASE WHEN blueprint_id IS NOT NULL THEN 'blueprint' WHEN command_id IS NOT NULL THEN 'command' ELSE NULL END ) STORED,
    CONSTRAINT collection_items_item_type_check CHECK ( (blueprint_id IS NOT NULL AND command_id IS NULL) OR (blueprint_id IS NULL AND command_id IS NOT NULL) )
);

CREATE OR REPLACE VIEW public.command_search_view AS
SELECT 
  c.*,
  b.title as blueprint_title,
  b.slug as blueprint_slug,
  cat.name as blueprint_category
FROM public.commands c
LEFT JOIN public.blueprints b ON c.blueprint_id = b.id
LEFT JOIN public.categories cat ON b.category_id = cat.id
WHERE c.is_active = true;

CREATE OR REPLACE VIEW collection_contents AS
SELECT 
  ci.id,
  ci.collection_id,
  ci.added_at,
  ci.item_type,
  ci.blueprint_id,
  ci.command_id,
  COALESCE(b.title, c.name) as item_name,
  COALESCE(b.description, c.description) as item_description,
  COALESCE(b.slug, c.id) as item_slug,
  b.category_id as blueprint_category_id,
  c.category as command_category,
  c.command_type,
  c.scope as command_scope
FROM collection_items ci
LEFT JOIN blueprints b ON ci.blueprint_id = b.id
LEFT JOIN commands c ON ci.command_id = c.id;


-- === FUNCTIONS OBJECTS ===

CREATE OR REPLACE FUNCTION trigger_set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION upsert_user_blueprint_usage(
    p_user_id UUID,
    p_blueprint_id TEXT
)
RETURNS void AS $$
BEGIN
    INSERT INTO user_blueprint_usage (user_id, blueprint_id, usage_count, last_used)
    VALUES (p_user_id, p_blueprint_id, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (user_id, blueprint_id)
    DO UPDATE SET
        usage_count = user_blueprint_usage.usage_count + 1,
        last_used = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_blueprint_relationships(
  blueprint_id TEXT,
  relationship_types TEXT[] DEFAULT '{"requires", "suggests", "conflicts", "supersedes", "enhances"}'
)
RETURNS TABLE (
  relationship_type TEXT,
  related_blueprint jsonb,
  condition_tags jsonb,
  condition_platforms TEXT[],
  condition_stack TEXT,
  priority INTEGER
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    rr.relationship_type,
    to_jsonb(related_blueprint.*) as related_blueprint,
    rr.condition_tags,
    rr.condition_platforms,
    rr.condition_stack,
    rr.priority
  FROM public.blueprint_relationships rr
  JOIN public.blueprints related_blueprint ON rr.related_blueprint_id = related_blueprint.id
  WHERE rr.blueprint_id = blueprint_id
    AND rr.relationship_type = ANY(relationship_types)
  ORDER BY rr.priority DESC, rr.relationship_type;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_blueprint_for_platform(
  blueprint_id TEXT,
  platform TEXT
)
RETURNS TABLE (
  blueprint_data jsonb,
  platform_config jsonb,
  commands jsonb
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    to_jsonb(r.*) as blueprint_data,
    COALESCE(rp.platform_config, '{}'::jsonb) as platform_config,
    COALESCE(
      (SELECT jsonb_agg(
        jsonb_build_object(
          'name', pc.command_name,
          'content', pc.command_content,
          'metadata', pc.command_metadata
        )
      ) FROM public.platform_commands pc
      WHERE pc.blueprint_id = r.id AND pc.platform_type = platform AND pc.is_active = true),
      '[]'::jsonb
    ) as commands
  FROM public.blueprints r
  LEFT JOIN public.blueprint_platforms rp ON r.id = rp.blueprint_id AND rp.platform_type = platform
  WHERE r.id = blueprint_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.remove_blueprint_vote(target_blueprint_id TEXT)
RETURNS VOID AS $$
BEGIN
  DELETE FROM public.user_votes
  WHERE user_id = auth.uid() AND blueprint_id = target_blueprint_id;
  UPDATE public.blueprints
  SET votes = (SELECT COUNT(*) FROM public.user_votes WHERE user_votes.blueprint_id = target_blueprint_id)
  WHERE id = target_blueprint_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_blueprints_by_category(category_slug TEXT)
RETURNS SETOF public.blueprints AS $$
BEGIN
  RETURN QUERY
  SELECT r.*
  FROM public.blueprints r
  JOIN public.categories c ON r.category_id = c.id
  WHERE c.slug = category_slug
  ORDER BY r.votes DESC, r.downloads DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.validate_blueprint_schema(
  blueprint_id TEXT,
  schema_version TEXT DEFAULT '2.0.0'
)
RETURNS jsonb AS $$
DECLARE
  blueprint_record public.blueprints;
  validation_result jsonb;
  errors jsonb := '[]'::jsonb;
  warnings jsonb := '[]'::jsonb;
BEGIN
  SELECT * INTO blueprint_record FROM public.blueprints WHERE id = blueprint_id;
  IF NOT FOUND THEN
    RETURN jsonb_build_object(
      'status', 'error',
      'errors', jsonb_build_array('Blueprint not found')
    );
  END IF;
  IF blueprint_record.title IS NULL OR trim(blueprint_record.title) = '' THEN
    errors := errors || jsonb_build_array('Title is required');
  END IF;
  IF blueprint_record.description IS NULL OR trim(blueprint_record.description) = '' THEN
    errors := errors || jsonb_build_array('Description is required');
  END IF;
  IF blueprint_record.content IS NULL OR trim(blueprint_record.content) = '' THEN
    errors := errors || jsonb_build_array('Content is required');
  END IF;
  IF blueprint_record.complexity IS NOT NULL AND blueprint_record.complexity NOT IN ('simple', 'medium', 'complex') THEN
    errors := errors || jsonb_build_array('Invalid complexity value');
  END IF;
  IF blueprint_record.scope IS NOT NULL AND blueprint_record.scope NOT IN ('file', 'component', 'feature', 'project', 'system') THEN
    errors := errors || jsonb_build_array('Invalid scope value');
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.blueprint_platforms WHERE blueprint_id = blueprint_record.id) THEN
    warnings := warnings || jsonb_build_array('No platform compatibility defined');
  END IF;
  validation_result := jsonb_build_object(
    'status', CASE
      WHEN jsonb_array_length(errors) > 0 THEN 'error'
      WHEN jsonb_array_length(warnings) > 0 THEN 'warning'
      ELSE 'valid'
    END,
    'errors', errors,
    'warnings', warnings,
    'validated_at', NOW()
  );
  INSERT INTO public.blueprint_validations (blueprint_id, schema_version, validation_status, validation_errors, validation_warnings)
  VALUES (blueprint_id, schema_version, (validation_result->>'status'), errors, warnings)
  ON CONFLICT (blueprint_id, schema_version)
  DO UPDATE SET
    validation_status = EXCLUDED.validation_status,
    validation_errors = EXCLUDED.validation_errors,
    validation_warnings = EXCLUDED.validation_warnings,
    validated_at = NOW();
  RETURN validation_result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION upsert_user_platform_stats(
    p_user_id UUID,
    p_platform TEXT
)
RETURNS void AS $$
BEGIN
    INSERT INTO user_platform_stats (user_id, platform, usage_count, last_used)
    VALUES (p_user_id, p_platform, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (user_id, platform)
    DO UPDATE SET
        usage_count = user_platform_stats.usage_count + 1,
        last_used = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_popular_blueprints(limit_count INTEGER DEFAULT 10)
RETURNS SETOF public.blueprints AS $$
BEGIN
  RETURN QUERY
  SELECT r.*
  FROM public.blueprints r
  ORDER BY
    (r.votes * 2 + r.downloads) DESC,
    r.created_at DESC
  LIMIT limit_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.search_blueprints_enhanced(
  search_query TEXT DEFAULT NULL,
  category_slug TEXT DEFAULT NULL,
  tags TEXT[] DEFAULT '{}',
  platforms TEXT[] DEFAULT '{}',
  complexity TEXT DEFAULT NULL,
  scope TEXT DEFAULT NULL,
  audience TEXT DEFAULT NULL,
  maturity TEXT DEFAULT NULL,
  framework TEXT DEFAULT NULL,
  language TEXT DEFAULT NULL,
  stack TEXT DEFAULT NULL
)
RETURNS SETOF public.blueprints AS $$
BEGIN
  RETURN QUERY
  SELECT DISTINCT r.*
  FROM public.blueprints r
  LEFT JOIN public.categories c ON r.category_id = c.id
  LEFT JOIN public.blueprint_platforms rp ON r.id = rp.blueprint_id
  WHERE
    (search_query IS NULL OR
     to_tsvector('english', r.title || ' ' || r.description || ' ' || r.content) @@ plainto_tsquery('english', search_query)) AND
    (category_slug IS NULL OR c.slug = category_slug) AND
    (array_length(tags, 1) IS NULL OR r.tags && tags) AND
    (array_length(platforms, 1) IS NULL OR EXISTS (
      SELECT 1 FROM public.blueprint_platforms rp2
      WHERE rp2.blueprint_id = r.id AND rp2.platform_type = ANY(platforms) AND rp2.is_compatible = true
    )) AND
    (complexity IS NULL OR r.complexity = complexity) AND
    (scope IS NULL OR r.scope = scope) AND
    (audience IS NULL OR r.audience = audience) AND
    (maturity IS NULL OR r.maturity = maturity) AND
    (framework IS NULL OR r.framework = framework) AND
    (language IS NULL OR r.language = language) AND
    (stack IS NULL OR r.stack = stack)
  ORDER BY
    CASE WHEN search_query IS NOT NULL
    THEN ts_rank(to_tsvector('english', r.title || ' ' || r.description || ' ' || r.content), plainto_tsquery('english', search_query))
    ELSE 0 END DESC,
    r.votes DESC,
    r.downloads DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION get_cli_usage_summary(
  start_date TIMESTAMP WITH TIME ZONE DEFAULT NOW() - INTERVAL '30 days',
  end_date TIMESTAMP WITH TIME ZONE DEFAULT NOW()
)
RETURNS TABLE (
  total_events BIGINT,
  success_rate NUMERIC,
  avg_execution_time_ms NUMERIC,
  unique_sessions BIGINT,
  top_commands JSONB,
  platform_distribution JSONB
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    COUNT(*) as total_events,
    (COUNT(*) FILTER (WHERE success = true))::NUMERIC / NULLIF(COUNT(*), 0) * 100 as success_rate,
    AVG(execution_time_ms) as avg_execution_time_ms,
    COUNT(DISTINCT session_id) as unique_sessions,
    (
      SELECT jsonb_agg(
        jsonb_build_object('command', command, 'count', count)
      )
      FROM (
        SELECT command, COUNT(*) as count
        FROM cli_usage_events
        WHERE timestamp BETWEEN start_date AND end_date
        GROUP BY command
        ORDER BY count DESC
        LIMIT 10
      ) top_cmds
    ) as top_commands,
    (
      SELECT jsonb_agg(
        jsonb_build_object('platform', platform, 'count', count)
      )
      FROM (
        SELECT platform, COUNT(*) as count
        FROM cli_usage_events
        WHERE timestamp BETWEEN start_date AND end_date
        GROUP BY platform
        ORDER BY count DESC
      ) platforms
    ) as platform_distribution
  FROM cli_usage_events
  WHERE timestamp BETWEEN start_date AND end_date;
END;
$$;

CREATE OR REPLACE FUNCTION upsert_user_command_stats(
    p_user_id UUID,
    p_command TEXT
)
RETURNS void AS $$
BEGIN
    INSERT INTO user_command_stats (user_id, command, usage_count, last_used)
    VALUES (p_user_id, p_command, 1, CURRENT_TIMESTAMP)
    ON CONFLICT (user_id, command)
    DO UPDATE SET
        usage_count = user_command_stats.usage_count + 1,
        last_used = CURRENT_TIMESTAMP,
        updated_at = CURRENT_TIMESTAMP;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.get_table_stats()
RETURNS TABLE (
  table_name TEXT,
  row_count BIGINT,
  size_bytes BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    schemaname || '.' || tablename as table_name,
    COALESCE(n_tup_ins - n_tup_del, 0) as row_count,
    COALESCE(pg_total_relation_size(schemaname||'.'||tablename), 0) as size_bytes
  FROM pg_stat_user_tables
  WHERE schemaname = 'public'
  ORDER BY pg_total_relation_size(schemaname||'.'||tablename) DESC NULLS LAST;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION trigger_update_blueprint_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  IF OLD.content IS DISTINCT FROM NEW.content THEN
    NEW.last_updated = NOW();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.vote_for_blueprint(target_blueprint_id TEXT)
RETURNS VOID AS $$
BEGIN
  INSERT INTO public.user_votes (user_id, blueprint_id)
  VALUES (auth.uid(), target_blueprint_id)
  ON CONFLICT (user_id, blueprint_id) DO NOTHING;
  UPDATE public.blueprints
  SET votes = (SELECT COUNT(*) FROM public.user_votes WHERE user_votes.blueprint_id = target_blueprint_id)
  WHERE id = target_blueprint_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.increment_blueprint_downloads(target_blueprint_id TEXT)
RETURNS VOID AS $$
BEGIN
  UPDATE public.blueprints
  SET downloads = downloads + 1
  WHERE id = target_blueprint_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION generate_api_token()
RETURNS TEXT AS $$
DECLARE
    token_length INTEGER := 64;
    chars TEXT := 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
    result TEXT := '';
    i INTEGER := 0;
BEGIN
    FOR i IN 1..token_length LOOP
        result := result || substring(chars, floor(random() * char_length(chars) + 1)::integer, 1);
    END LOOP;
    RETURN 'vdk_' || result;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION trigger_sync_vote_count()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    UPDATE public.blueprints
    SET votes = votes + 1
    WHERE id = NEW.blueprint_id;
  ELSIF TG_OP = 'DELETE' THEN
    UPDATE public.blueprints
    SET votes = votes - 1
    WHERE id = OLD.blueprint_id;
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN AS $$
BEGIN
  RETURN auth.email() IN (SELECT email FROM public.admins);
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION recalculate_blueprint_stats(blueprint_uuid UUID)
RETURNS VOID AS $$
DECLARE
  new_usage_count INTEGER;
  new_success_rate DECIMAL(3,2);
  new_rating DECIMAL(3,2);
  new_vote_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO new_usage_count
  FROM blueprint_usage
  WHERE blueprint_id = blueprint_uuid;
  SELECT 
    CASE 
      WHEN COUNT(*) = 0 THEN 0
      ELSE ROUND(COUNT(*) FILTER (WHERE success = true)::DECIMAL / COUNT(*), 2)
    END INTO new_success_rate
  FROM blueprint_usage
  WHERE blueprint_id = blueprint_uuid;
  SELECT 
    CASE 
      WHEN COUNT(*) FILTER (WHERE rating IS NOT NULL) = 0 THEN 0
      ELSE ROUND(AVG(rating), 2)
    END INTO new_rating
  FROM blueprint_votes
  WHERE blueprint_id = blueprint_uuid;
  SELECT COUNT(*) INTO new_vote_count
  FROM blueprint_votes
  WHERE blueprint_id = blueprint_uuid AND vote_type = 'up';
  UPDATE community_blueprints
  SET 
    usage_count = new_usage_count,
    deployment_success_rate = new_success_rate,
    rating = new_rating,
    vote_count = new_vote_count,
    updated_at = NOW()
  WHERE id = blueprint_uuid;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION get_cli_integration_summary(
  timeframe_days INTEGER DEFAULT 7
)
RETURNS TABLE (
  integration_type TEXT,
  total_events BIGINT,
  detections BIGINT,
  activations BIGINT,
  errors BIGINT,
  error_rate NUMERIC
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT
    i.integration_type,
    COUNT(*) as total_events,
    COUNT(*) FILTER (WHERE action = 'detected') as detections,
    COUNT(*) FILTER (WHERE action = 'activated') as activations,
    COUNT(*) FILTER (WHERE success = false) as errors,
    (COUNT(*) FILTER (WHERE success = false))::NUMERIC / NULLIF(COUNT(*), 0) * 100 as error_rate
  FROM cli_integration_events i
  WHERE timestamp >= NOW() - (timeframe_days || ' days')::INTERVAL
  GROUP BY i.integration_type
  ORDER BY total_events DESC;
END;
$$;

CREATE OR REPLACE FUNCTION validate_api_token(p_token TEXT)
RETURNS TABLE(user_id UUID, token_id UUID, is_valid BOOLEAN) AS $$
DECLARE
    found_user_id UUID;
    found_token_id UUID;
    is_expired BOOLEAN;
    is_active BOOLEAN;
BEGIN
    SELECT t.user_id, t.id, t.is_active, (t.expires_at < CURRENT_TIMESTAMP)
    INTO found_user_id, found_token_id, is_active, is_expired
    FROM user_api_tokens t
    WHERE (t.token_hash = p_token OR t.token_hash = crypt(p_token, t.token_hash))
      AND t.is_active = TRUE
      AND (t.expires_at IS NULL OR t.expires_at > CURRENT_TIMESTAMP)
    LIMIT 1;
    IF found_user_id IS NOT NULL AND NOT is_expired AND is_active THEN
        UPDATE user_api_tokens
        SET last_used = CURRENT_TIMESTAMP
        WHERE id = found_token_id;
        RETURN QUERY SELECT found_user_id, found_token_id, TRUE;
    ELSE
        RETURN QUERY SELECT NULL::UUID, NULL::UUID, FALSE;
    END IF;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION public.search_blueprints(
  search_query TEXT,
  category_slug TEXT DEFAULT NULL,
  tags TEXT[] DEFAULT '{}')
RETURNS SETOF public.blueprints AS $$
BEGIN
  RETURN QUERY
  SELECT r.*
  FROM public.blueprints r
  LEFT JOIN public.categories c ON r.category_id = c.id
  WHERE
    (search_query IS NULL OR
     to_tsvector('english', r.title || ' ' || r.description || ' ' || r.content) @@ plainto_tsquery('english', search_query)) AND
    (category_slug IS NULL OR c.slug = category_slug) AND
    (array_length(tags, 1) IS NULL OR r.tags && tags)
  ORDER BY
    CASE WHEN search_query IS NOT NULL
    THEN ts_rank(to_tsvector('english', r.title || ' ' || r.description || ' ' || r.content), plainto_tsquery('english', search_query))
    ELSE 0 END DESC,
    r.votes DESC,
    r.downloads DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION increment_blueprint_usage(blueprint_id TEXT)
RETURNS void AS $$
BEGIN
    UPDATE blueprints
    SET downloads = COALESCE(downloads, 0) + 1,
        updated_at = CURRENT_TIMESTAMP
    WHERE id = blueprint_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION create_user_api_token(
    p_user_id UUID,
    p_token_name TEXT DEFAULT 'CLI Token',
    p_expires_in_days INTEGER DEFAULT 365
)
RETURNS TABLE(token TEXT, token_id UUID, prefix TEXT) AS $$
DECLARE
    new_token TEXT;
    token_id UUID;
    token_prefix TEXT;
    token_hash TEXT;
BEGIN
    new_token := generate_api_token();
    token_prefix := LEFT(new_token, 8) || '...';
    BEGIN
        token_hash := crypt(new_token, gen_salt('bf'));
    EXCEPTION
        WHEN undefined_function THEN
            token_hash := new_token;
    END;
    INSERT INTO user_api_tokens (user_id, token_name, token_hash, token_prefix, expires_at)
    VALUES (
        p_user_id,
        p_token_name,
        token_hash,
        token_prefix,
        CURRENT_TIMESTAMP + (p_expires_in_days * INTERVAL '1 day')
    )
    RETURNING id INTO token_id;
    RETURN QUERY SELECT new_token, token_id, token_prefix;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE FUNCTION trigger_recalculate_stats_usage()
RETURNS TRIGGER AS $$
BEGIN
  PERFORM recalculate_blueprint_stats(NEW.blueprint_id);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION trigger_recalculate_stats_votes()
RETURNS TRIGGER AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    PERFORM recalculate_blueprint_stats(OLD.blueprint_id);
    RETURN OLD;
  ELSE
    PERFORM recalculate_blueprint_stats(NEW.blueprint_id);
    RETURN NEW;
  END IF;
END;
$$ LANGUAGE plpgsql;


-- === TRIGGERS OBJECTS ===

CREATE TRIGGER trigger_categories_set_updated_at
BEFORE UPDATE ON public.categories
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER trigger_commands_set_updated_at
BEFORE UPDATE ON public.commands
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER update_user_blueprint_usage_updated_at BEFORE UPDATE ON user_blueprint_usage
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_blueprints_set_updated_at
BEFORE UPDATE ON public.blueprints
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER update_user_project_stats_updated_at BEFORE UPDATE ON user_project_stats
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_command_stats_updated_at BEFORE UPDATE ON user_command_stats
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_vote_count_update
AFTER INSERT OR DELETE ON public.user_votes
FOR EACH ROW EXECUTE FUNCTION trigger_sync_vote_count();

CREATE TRIGGER update_vdk_versions_updated_at BEFORE UPDATE ON vdk_versions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_team_configurations_updated_at BEFORE UPDATE ON team_configurations
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_profiles_set_updated_at
BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER recalculate_stats_on_votes
  AFTER INSERT OR UPDATE OR DELETE ON blueprint_votes
  FOR EACH ROW EXECUTE FUNCTION trigger_recalculate_stats_votes();

CREATE TRIGGER update_cli_deployments_updated_at BEFORE UPDATE ON cli_deployments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_user_api_tokens_updated_at BEFORE UPDATE ON user_api_tokens
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER recalculate_stats_on_usage
  AFTER INSERT ON blueprint_usage
  FOR EACH ROW EXECUTE FUNCTION trigger_recalculate_stats_usage();

CREATE TRIGGER trigger_blueprint_content_update
BEFORE UPDATE ON public.blueprints
FOR EACH ROW EXECUTE FUNCTION trigger_update_blueprint_timestamp();

CREATE TRIGGER update_user_platform_stats_updated_at BEFORE UPDATE ON user_platform_stats
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_collections_set_updated_at
BEFORE UPDATE ON public.collections
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER update_community_blueprints_updated_at 
  BEFORE UPDATE ON community_blueprints 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_blueprint_platforms_set_updated_at
BEFORE UPDATE ON public.blueprint_platforms
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER trigger_platform_commands_set_updated_at
BEFORE UPDATE ON public.platform_commands
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();

CREATE TRIGGER update_blueprint_votes_updated_at 
  BEFORE UPDATE ON blueprint_votes 
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER trigger_generation_templates_set_updated_at
BEFORE UPDATE ON public.generation_templates
FOR EACH ROW EXECUTE FUNCTION trigger_set_updated_at();


-- === INDEXES OBJECTS ===

CREATE INDEX IF NOT EXISTS idx_categories_type ON public.categories (category_type);

CREATE INDEX IF NOT EXISTS idx_user_blueprint_usage_blueprint_id ON user_blueprint_usage(blueprint_id);

CREATE INDEX idx_cli_usage_events_timestamp ON cli_usage_events(timestamp);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_platforms ON community_blueprints USING GIN(platforms);

CREATE INDEX IF NOT EXISTS idx_team_configurations_updated_at ON team_configurations(updated_at);

CREATE INDEX IF NOT EXISTS idx_generated_packages_configuration_id ON public.generated_packages (configuration_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_content_search ON public.blueprints USING GIN(to_tsvector('english', title || ' ' || description || ' ' || content));

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_success ON blueprint_usage(success);

CREATE INDEX IF NOT EXISTS idx_blueprints_complexity ON public.blueprints (complexity);

CREATE INDEX IF NOT EXISTS idx_user_api_tokens_token_hash ON user_api_tokens(token_hash);

CREATE INDEX IF NOT EXISTS idx_blueprints_category_id ON public.blueprints (category_id);

CREATE INDEX IF NOT EXISTS idx_wizard_configurations_session_id ON public.wizard_configurations (session_id);

CREATE INDEX IF NOT EXISTS idx_cli_deployment_blueprints_deployment_id ON cli_deployment_blueprints(deployment_id);

CREATE INDEX idx_cli_performance_events_timestamp ON cli_performance_events(timestamp);

CREATE INDEX IF NOT EXISTS idx_blueprints_language ON public.blueprints (language);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_category ON community_blueprints(category);

CREATE INDEX IF NOT EXISTS idx_vdk_error_logs_error_type ON vdk_error_logs(error_type);

CREATE INDEX IF NOT EXISTS idx_generated_packages_expires_at ON public.generated_packages (expires_at);

CREATE INDEX IF NOT EXISTS idx_blueprint_platforms_config ON public.blueprint_platforms USING GIN (platform_config);

CREATE INDEX IF NOT EXISTS idx_platform_commands_platform ON public.platform_commands (platform_type);

CREATE INDEX IF NOT EXISTS idx_blueprint_validations_blueprint_id ON public.blueprint_validations (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_vdk_analytics_created_at ON vdk_analytics(created_at);

CREATE INDEX IF NOT EXISTS idx_user_platform_stats_platform ON user_platform_stats(platform);

CREATE INDEX IF NOT EXISTS idx_blueprints_framework ON public.blueprints (framework);

CREATE INDEX IF NOT EXISTS idx_blueprint_versions_blueprint_id ON public.blueprint_versions (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_collection_items_blueprint_id ON public.collection_items (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_framework ON community_blueprints(framework);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_rating ON community_blueprints(rating DESC);

CREATE INDEX IF NOT EXISTS idx_blueprints_author ON public.blueprints (author);

CREATE INDEX IF NOT EXISTS idx_generation_templates_active ON public.generation_templates (is_active) WHERE is_active = TRUE;

CREATE INDEX IF NOT EXISTS idx_categories_slug ON public.categories (slug);

CREATE INDEX IF NOT EXISTS idx_vdk_versions_component ON vdk_versions(component);

CREATE INDEX IF NOT EXISTS idx_user_api_tokens_is_active ON user_api_tokens(is_active);

CREATE INDEX IF NOT EXISTS idx_commands_category ON public.commands (category);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_status_usage ON community_blueprints(status, usage_count DESC);

CREATE INDEX idx_collection_items_item_type ON collection_items(item_type);

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_session_id ON blueprint_usage(session_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_platforms_blueprint_id ON public.blueprint_platforms (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_vdk_error_logs_user_id ON vdk_error_logs(user_id);

CREATE INDEX IF NOT EXISTS idx_cli_deployment_blueprints_blueprint_name ON cli_deployment_blueprints(blueprint_name);

CREATE INDEX idx_cli_error_events_error_type ON cli_error_events(error_type);

CREATE INDEX IF NOT EXISTS idx_wizard_configurations_user_id ON public.wizard_configurations (user_id);

CREATE INDEX IF NOT EXISTS idx_commands_scope ON public.commands (scope);

CREATE INDEX idx_cli_usage_events_user_id ON cli_usage_events(user_id) WHERE user_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_blueprint_usage_last_used ON user_blueprint_usage(last_used);

CREATE INDEX IF NOT EXISTS idx_categories_parent_id ON public.categories (parent_id);

CREATE INDEX IF NOT EXISTS idx_team_configurations_team_id ON team_configurations(team_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_validations_status ON public.blueprint_validations (validation_status);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_published_at ON community_blueprints(published_at DESC);

CREATE INDEX idx_cli_performance_events_command ON cli_performance_events(command);

CREATE INDEX idx_cli_performance_events_operation ON cli_performance_events(operation);

CREATE INDEX IF NOT EXISTS idx_blueprint_platforms_compatible ON public.blueprint_platforms (is_compatible) WHERE is_compatible = true;

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_blueprint_deployed ON blueprint_usage(blueprint_id, deployed_at DESC);

CREATE INDEX IF NOT EXISTS idx_blueprints_subcategory ON public.blueprints (subcategory);

CREATE INDEX IF NOT EXISTS idx_commands_active ON public.commands (is_active) WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_user_platform_stats_user_id ON user_platform_stats(user_id);

CREATE INDEX IF NOT EXISTS idx_commands_command_type ON public.commands (command_type);

CREATE INDEX IF NOT EXISTS idx_vdk_versions_version ON vdk_versions(version);

CREATE INDEX IF NOT EXISTS idx_user_api_tokens_expires_at ON user_api_tokens(expires_at);

CREATE INDEX IF NOT EXISTS idx_vdk_analytics_event_type ON vdk_analytics(event_type);

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_framework ON blueprint_usage(framework);

CREATE INDEX IF NOT EXISTS idx_blueprints_repository_url ON public.blueprints(repository_url) WHERE repository_url IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_blueprint_relationships_platforms ON public.blueprint_relationships USING GIN (condition_platforms);

CREATE INDEX IF NOT EXISTS idx_collection_items_collection_id ON public.collection_items (collection_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_frontmatter ON public.blueprints USING GIN (frontmatter);

CREATE INDEX IF NOT EXISTS idx_blueprint_relationships_type ON public.blueprint_relationships (relationship_type);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_author_username ON community_blueprints(author_username);

CREATE INDEX IF NOT EXISTS idx_vdk_analytics_user_id ON vdk_analytics(user_id);

CREATE INDEX idx_cli_error_events_command ON cli_error_events(command);

CREATE INDEX IF NOT EXISTS idx_cli_deployments_deployment_id ON cli_deployments(deployment_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_blueprint_id ON blueprint_usage(blueprint_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_tags ON public.blueprints USING GIN (tags);

CREATE INDEX IF NOT EXISTS idx_commands_tags ON public.commands USING GIN (tags);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_status_category ON community_blueprints(status, category);

CREATE INDEX IF NOT EXISTS idx_vdk_analytics_project_id ON vdk_analytics(project_id);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_status_rating ON community_blueprints(status, rating DESC);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_tags ON community_blueprints USING GIN(tags);

CREATE INDEX IF NOT EXISTS idx_cli_deployments_team_name ON cli_deployments(team_name);

CREATE INDEX idx_cli_integration_events_integration_type ON cli_integration_events(integration_type);

CREATE INDEX IF NOT EXISTS idx_blueprint_votes_created_at ON blueprint_votes(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_user_command_stats_user_id ON user_command_stats(user_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_always_apply ON public.blueprints (always_apply) WHERE always_apply = TRUE;

CREATE INDEX idx_collection_items_command_id ON collection_items(command_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_compatibility_technology ON public.blueprint_compatibility (technology);

CREATE INDEX IF NOT EXISTS idx_blueprint_platforms_platform_type ON public.blueprint_platforms (platform_type);

CREATE INDEX IF NOT EXISTS idx_cli_recommendations_recommendation_id ON cli_recommendations(recommendation_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_scope ON public.blueprints (scope);

CREATE INDEX IF NOT EXISTS idx_cli_deployments_deployed_at ON cli_deployments(deployed_at);

CREATE INDEX IF NOT EXISTS idx_commands_blueprint_id ON public.commands (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_deployed_at ON blueprint_usage(deployed_at DESC);

CREATE INDEX IF NOT EXISTS idx_blueprint_dependencies_blueprint_id ON public.blueprint_dependencies (blueprint_id);

CREATE INDEX idx_cli_performance_events_session_id ON cli_performance_events(session_id);

CREATE INDEX IF NOT EXISTS idx_vdk_versions_status ON vdk_versions(status);

CREATE INDEX IF NOT EXISTS idx_blueprints_license ON public.blueprints(license) WHERE license IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_categories_supported_platforms ON public.categories USING GIN (supported_platforms);

CREATE INDEX IF NOT EXISTS idx_team_configurations_user_id ON team_configurations(user_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_votes_vote_type ON blueprint_votes(vote_type);

CREATE INDEX idx_cli_error_events_timestamp ON cli_error_events(timestamp);

CREATE INDEX IF NOT EXISTS idx_blueprint_usage_platform ON blueprint_usage(platform);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_search 
ON community_blueprints 
USING GIN(to_tsvector('english', title || ' ' || COALESCE(description, '') || ' ' || COALESCE(tags::text, '')));

CREATE INDEX IF NOT EXISTS idx_platform_commands_active ON public.platform_commands (is_active) WHERE is_active = true;

CREATE INDEX idx_cli_usage_events_command ON cli_usage_events(command);

CREATE INDEX idx_cli_integration_events_session_id ON cli_integration_events(session_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_stack ON public.blueprints (stack);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_usage_count ON community_blueprints(usage_count DESC);

CREATE INDEX idx_cli_integration_events_action ON cli_integration_events(action);

CREATE INDEX IF NOT EXISTS idx_user_api_tokens_user_id ON user_api_tokens(user_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_relationships_related_id ON public.blueprint_relationships (related_blueprint_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_votes_user_id ON blueprint_votes(user_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_compatibility_blueprint_id ON public.blueprint_compatibility (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_language ON community_blueprints(language);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_status ON community_blueprints(status);

CREATE INDEX IF NOT EXISTS idx_blueprints_slug ON public.blueprints (slug);

CREATE INDEX IF NOT EXISTS idx_categories_platform_specific ON public.categories (platform_specific);

CREATE INDEX IF NOT EXISTS idx_blueprints_contributors ON public.blueprints USING GIN (contributors);

CREATE INDEX IF NOT EXISTS idx_blueprint_dependencies_depends_on ON public.blueprint_dependencies (depends_on_blueprint_id);

CREATE INDEX IF NOT EXISTS idx_user_command_stats_command ON user_command_stats(command);

CREATE INDEX IF NOT EXISTS idx_blueprints_maturity ON public.blueprints (maturity);

CREATE INDEX IF NOT EXISTS idx_blueprint_votes_blueprint_id ON blueprint_votes(blueprint_id);

CREATE INDEX IF NOT EXISTS idx_user_project_stats_user_id ON user_project_stats(user_id);

CREATE INDEX IF NOT EXISTS idx_cli_deployments_project_name ON cli_deployments(project_name);

CREATE INDEX IF NOT EXISTS idx_blueprints_audience ON public.blueprints (audience);

CREATE INDEX IF NOT EXISTS idx_blueprint_relationships_blueprint_id ON public.blueprint_relationships (blueprint_id);

CREATE INDEX IF NOT EXISTS idx_blueprints_schema_version ON public.blueprints(schema_version) WHERE schema_version IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_user_project_stats_project_id ON user_project_stats(project_id);

CREATE INDEX IF NOT EXISTS idx_blueprint_votes_rating ON blueprint_votes(rating);

CREATE INDEX IF NOT EXISTS idx_platform_commands_blueprint_id ON public.platform_commands (blueprint_id);

CREATE INDEX idx_cli_usage_events_session_id ON cli_usage_events(session_id);

CREATE INDEX idx_cli_integration_events_timestamp ON cli_integration_events(timestamp);

CREATE INDEX IF NOT EXISTS idx_commands_target ON public.commands (target);

CREATE INDEX IF NOT EXISTS idx_user_blueprint_usage_user_id ON user_blueprint_usage(user_id);

CREATE INDEX IF NOT EXISTS idx_community_blueprints_created_at ON community_blueprints(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_blueprint_validations_validated_at ON public.blueprint_validations (validated_at);

CREATE INDEX idx_cli_error_events_session_id ON cli_error_events(session_id);

CREATE INDEX IF NOT EXISTS idx_cli_recommendations_created_at ON cli_recommendations(created_at);

CREATE INDEX IF NOT EXISTS idx_collections_user_id ON public.collections (user_id);

CREATE INDEX IF NOT EXISTS idx_vdk_error_logs_created_at ON vdk_error_logs(created_at);

CREATE INDEX idx_cli_usage_events_platform ON cli_usage_events(platform);


-- === SECURITY OBJECTS ===

CREATE POLICY "Users can update their own platform stats" ON user_platform_stats
    FOR UPDATE USING (auth.uid()::text = user_id::text);

CREATE POLICY "Public read access for votes" ON blueprint_votes
  FOR SELECT USING (true);

CREATE POLICY "Admins can manage all data" ON public.categories
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Authenticated users can read profiles" ON public.profiles
FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Admins can manage platform commands" ON public.platform_commands
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Service role full access on usage" ON blueprint_usage
  FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Authors can read their own blueprints" ON community_blueprints
  FOR SELECT USING (auth.uid() = author_id);

CREATE POLICY "Public read access for active commands" ON public.commands 
FOR SELECT USING (is_active = true);

CREATE POLICY "Users can update their own collection items with commands" ON collection_items
  FOR UPDATE USING (
    collection_id IN (
      SELECT id FROM collections WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can read public collections" ON public.collections
FOR SELECT USING (is_public = TRUE OR auth.uid() = user_id);

CREATE POLICY "Users can view their own command stats" ON user_command_stats
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Public read access for categories" ON public.categories FOR SELECT USING (true);

CREATE POLICY "Users can insert their own team configurations" ON team_configurations
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Authenticated users can insert recommendations" ON cli_recommendations
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Anonymous users can read generated packages" ON public.generated_packages
FOR SELECT USING (true);

CREATE POLICY "Allow package cleanup" ON storage.objects
FOR DELETE USING (bucket_id = 'generated-packages');

CREATE POLICY "Users can update their own votes" ON blueprint_votes
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Anonymous users can create wizard configs" ON public.wizard_configurations
FOR INSERT WITH CHECK (true);

CREATE POLICY "Users can delete their own votes" ON blueprint_votes
  FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Anyone can upload generated packages" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'generated-packages');

CREATE POLICY "Authenticated users can insert CLI integration events" ON cli_integration_events
  FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Public read access for generated packages" ON storage.objects
FOR SELECT USING (bucket_id = 'generated-packages');

CREATE POLICY "Users can create commands" ON public.commands
FOR INSERT WITH CHECK (
  auth.uid() IS NOT NULL AND 
  is_active = false -- New commands start inactive for moderation
);

CREATE POLICY "Admins can manage blueprint platforms" ON public.blueprint_platforms
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Users can insert their own profile" ON public.profiles
FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Public read access for published blueprints" ON community_blueprints
  FOR SELECT USING (status = 'published');

CREATE POLICY "Users can update their own profiles" ON public.profiles
FOR UPDATE USING (auth.uid() = id);

CREATE POLICY "Users can delete their own collection items with commands" ON collection_items
  FOR DELETE USING (
    collection_id IN (
      SELECT id FROM collections WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Service role full access" ON community_blueprints
  FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Public read access for blueprint relationships" ON public.blueprint_relationships FOR SELECT USING (true);

CREATE POLICY "Admins can manage blueprint relationships" ON public.blueprint_relationships
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Users can insert their own platform stats" ON user_platform_stats
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Admins can manage all commands" ON public.commands
FOR ALL USING (
  EXISTS (
    SELECT 1 FROM public.admins a
    JOIN public.profiles p ON p.email = a.email
    WHERE p.id = auth.uid()
  )
);

CREATE POLICY "Public read access for usage analytics" ON blueprint_usage
  FOR SELECT USING (true);

CREATE POLICY "Users can update their own avatars" ON storage.objects
FOR UPDATE USING (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Authenticated users can view deployment blueprints" ON cli_deployment_blueprints
    FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Authors can update their own blueprints" ON community_blueprints
  FOR UPDATE USING (auth.uid() = author_id);

CREATE POLICY "Users can upload their own avatars" ON storage.objects
FOR INSERT WITH CHECK (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Users can view their own team configurations" ON team_configurations
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Authenticated users can view deployments" ON cli_deployments
    FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can update their own team configurations" ON team_configurations
    FOR UPDATE USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can update their own project stats" ON user_project_stats
    FOR UPDATE USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can insert their own analytics" ON vdk_analytics
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Public read access for blueprints" ON public.blueprints FOR SELECT USING (true);

CREATE POLICY "Users can view their own project stats" ON user_project_stats
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Authenticated users can insert deployment blueprints" ON cli_deployment_blueprints
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Users can read items in public collections" ON public.collection_items
FOR SELECT USING (EXISTS (SELECT 1 FROM public.collections c WHERE c.id = collection_id AND (c.is_public OR c.user_id = auth.uid())));

CREATE POLICY "Users can insert their own blueprint usage" ON user_blueprint_usage
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Service role can access all CLI integration events" ON cli_integration_events
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Users can insert their own API tokens" ON user_api_tokens
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can insert their own project stats" ON user_project_stats
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Anyone can insert usage records" ON blueprint_usage
  FOR INSERT WITH CHECK (true);

CREATE POLICY "Service role full access on votes" ON blueprint_votes
  FOR ALL USING (auth.jwt() ->> 'role' = 'service_role');

CREATE POLICY "Users can read their own wizard configs" ON public.wizard_configurations
FOR SELECT USING (auth.uid() = user_id OR user_id IS NULL);

CREATE POLICY "Users can insert their own error logs" ON vdk_error_logs
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Authenticated users can insert CLI usage events" ON cli_usage_events
  FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Authenticated users can insert deployments" ON cli_deployments
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "Authenticated users can view recommendations" ON cli_recommendations
    FOR SELECT USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can delete their own avatars" ON storage.objects
FOR DELETE USING (
  bucket_id = 'avatars' AND
  auth.uid()::text = (storage.foldername(name))[1]
);

CREATE POLICY "Public read access for blueprint platforms" ON public.blueprint_platforms FOR SELECT USING (true);

CREATE POLICY "Users can manage their own collections" ON public.collections
FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Admins can view sync logs" ON public.sync_logs
FOR SELECT USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Users can view their own analytics" ON vdk_analytics
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can view their own collection items with commands" ON collection_items
  FOR SELECT USING (
    collection_id IN (
      SELECT id FROM collections WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Users can insert their own votes" ON blueprint_votes
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Authors can insert blueprints" ON community_blueprints
  FOR INSERT WITH CHECK (auth.uid() = author_id);

CREATE POLICY "Service role can access all CLI error events" ON cli_error_events
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Users can view their own blueprint usage" ON user_blueprint_usage
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can insert their own command stats" ON user_command_stats
    FOR INSERT WITH CHECK (auth.uid()::text = user_id::text);

CREATE POLICY "Users can view their own error logs" ON vdk_error_logs
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can view their own platform stats" ON user_platform_stats
    FOR SELECT USING (auth.uid()::text = user_id::text);

CREATE POLICY "Public read access for avatars" ON storage.objects
FOR SELECT USING (bucket_id = 'avatars');

CREATE POLICY "Users can manage items in their collections" ON public.collection_items
FOR ALL USING (EXISTS (SELECT 1 FROM public.collections c WHERE c.id = collection_id AND c.user_id = auth.uid()));

CREATE POLICY "Public read access for blueprint validations" ON public.blueprint_validations FOR SELECT USING (true);

CREATE POLICY "Admins can manage blueprint validations" ON public.blueprint_validations
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Users can view their own API tokens" ON user_api_tokens
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own profiles" ON public.profiles
FOR DELETE USING (auth.uid() = id);

CREATE POLICY "Public read access for platform commands" ON public.platform_commands FOR SELECT USING (true);

CREATE POLICY "Service role can access all CLI usage events" ON cli_usage_events
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Users can update their own API tokens" ON user_api_tokens
    FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage all blueprints" ON public.blueprints
FOR ALL USING (auth.email() IN (SELECT email FROM public.admins));

CREATE POLICY "Allow updating download counts" ON public.generated_packages
FOR UPDATE USING (true)
WITH CHECK (true);

CREATE POLICY "Authenticated users can insert CLI performance events" ON cli_performance_events
  FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Users can delete their own API tokens" ON user_api_tokens
    FOR DELETE USING (auth.uid() = user_id);

CREATE POLICY "Users can insert their own collection items with commands" ON collection_items
  FOR INSERT WITH CHECK (
    collection_id IN (
      SELECT id FROM collections WHERE user_id = auth.uid()
    )
  );

CREATE POLICY "Service role can access all CLI performance events" ON cli_performance_events
  FOR ALL USING (auth.role() = 'service_role');

CREATE POLICY "Anonymous users can create generated packages" ON public.generated_packages
FOR INSERT WITH CHECK (true);

CREATE POLICY "Authenticated users can insert CLI error events" ON cli_error_events
  FOR INSERT WITH CHECK (auth.role() = 'authenticated' OR auth.role() = 'anon');

CREATE POLICY "Users can update their own blueprint usage" ON user_blueprint_usage
    FOR UPDATE USING (auth.uid()::text = user_id::text);

CREATE POLICY "Public read access for blueprint versions" ON public.blueprint_versions FOR SELECT USING (true);

CREATE POLICY "Anyone can view version information" ON vdk_versions
    FOR SELECT USING (true);

CREATE POLICY "Users can manage their votes" ON public.user_votes
FOR ALL USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own team configurations" ON team_configurations
    FOR DELETE USING (auth.uid()::text = user_id::text);

CREATE POLICY "Users can update their own command stats" ON user_command_stats
    FOR UPDATE USING (auth.uid()::text = user_id::text);


-- === UNCATEGORIZED OBJECTS ===

COMMENT ON TABLE public.blueprint_relationships IS 'Enhanced blueprint dependency relationships with conditional logic';

COMMENT ON COLUMN public.commands.claude_code_config IS 'Claude Code specific configuration including slashCommand, arguments, fileReferences, etc.';

COMMENT ON COLUMN public.blueprints.schema_version IS 'AI Context Schema version used by this blueprint (AI Context Schema v2.1.0)';

COMMENT ON TABLE cli_integration_events IS 'Tracks IDE and AI assistant integration events';

COMMENT ON POLICY "Allow updating download counts" ON public.generated_packages
IS 'Allows incrementing download counters for analytics and tracking';

COMMENT ON POLICY "Anonymous users can create generated packages" ON public.generated_packages
IS 'Allows anonymous users to create package records when generating blueprint packages from wizard';

COMMENT ON TABLE public.blueprint_platforms IS 'Platform-specific configurations for AI assistants (Claude Code, Cursor, Windsurf, GitHub Copilot)';

COMMENT ON TABLE public.admins IS 'RLS disabled - security handled by is_admin() function and admin email verification';

COMMENT ON COLUMN collection_items.command_id IS 'Reference to commands table. Mutually exclusive with blueprint_id.';

COMMENT ON TABLE cli_performance_events IS 'Monitors CLI performance metrics for optimization';

COMMENT ON COLUMN public.commands.permissions IS 'Command permissions including allowedTools and requiredApproval';

COMMENT ON COLUMN public.blueprints.license IS 'License identifier, preferably SPDX format (AI Context Schema v2.1.0)';

COMMENT ON COLUMN public.commands.examples IS 'Array of usage examples with context and expected outcomes';

COMMENT ON COLUMN public.commands.installation IS 'Installation requirements including dependencies and setup steps';

COMMENT ON TABLE public.blueprint_validations IS 'Schema validation tracking for quality assurance';

COMMENT ON TABLE public.commands IS 'Claude Code commands with rich metadata based on command-schema.json';

COMMENT ON TABLE public.platform_commands IS 'Platform-specific command implementations';

COMMENT ON COLUMN public.blueprints.compatibility IS 'Legacy compatibility field - migrating to platform_config';

COMMENT ON TABLE public.blueprints IS 'Enhanced blueprints table supporting .ai/ structure with multi-platform AI assistant integration';

COMMENT ON TABLE cli_error_events IS 'Records CLI errors for debugging and improvement';

COMMENT ON COLUMN collection_items.item_type IS 'Computed column indicating whether this item is a blueprint or command.';

COMMENT ON COLUMN public.blueprints.repository_url IS 'Source repository URL for the blueprint (AI Context Schema v2.1.0)';

COMMENT ON TABLE collection_items IS 'Collection items can contain either blueprints or commands, but not both. Use item_type column to distinguish.';

COMMENT ON TABLE cli_usage_events IS 'Tracks VDK CLI command usage, execution times, and success rates';

COMMENT ON VIEW collection_contents IS 'Unified view of collection contents with both blueprints and commands data.';

-- Original object: anonymous_block::DO_BLOCK
DO $$
BEGIN
  RAISE NOTICE 'Community Blueprint tables created successfully!';
  RAISE NOTICE 'Tables: community_blueprints, blueprint_usage, blueprint_votes';
  RAISE NOTICE 'Indexes: % total indexes created', (
    SELECT COUNT(*) 
    FROM pg_indexes 
    WHERE tablename IN ('community_blueprints', 'blueprint_usage', 'blueprint_votes')
  );
  RAISE NOTICE 'RLS policies: Enabled on all tables';
  RAISE NOTICE 'Sample data: 2 blueprints, 3 usage records, 3 votes inserted';
END $$;

